-- ============================================================
-- DRAFT — generated by scripts/migration/schema-from-openapi.mts from egpixaunlnzauztbrnuz on 2026-09-02T22:34:42.998Z.
-- Column types, defaults, NOT NULL, PK and FK only. Indexes, CHECK/UNIQUE
-- constraints, triggers, functions and RLS are NOT here: take them from
-- supabase/migrations/*.sql (repo history) and review before applying.
-- Replace with `pg_dump --schema-only` output as soon as the legacy DB
-- password is available. Do not apply this file blindly.
-- ============================================================

create table if not exists public.agent_config (
  key text not null,
  value text not null,
  updated_at timestamp with time zone default now(),
  primary key (key)
);
alter table public.agent_config enable row level security;

create table if not exists public.agent_cycles (
  id uuid not null default gen_random_uuid(),
  started_at timestamp with time zone default now(),
  completed_at timestamp with time zone,
  signals_found integer,
  signals_filtered integer,
  llm_decisions integer,
  trades_executed integer,
  trades_blocked integer,
  total_usd_deployed numeric,
  latency_ms integer,
  llm_model text,
  llm_reasoning text,
  error text,
  status text default running,
  trades_successful integer,
  mood text default confident,
  dynamic_conviction numeric,
  safe_mode_active boolean,
  vibe_phrase text,
  user_id uuid,
  owner_address text,
  state text default IDLE,
  state_version integer default 1,
  idempotency_key text,
  locked_until timestamp with time zone,
  cost_tokens integer,
  cost_usd numeric,
  idle_cash_usd numeric,
  yield_debate_triggered boolean not null,
  yield_recommendation_status text not null default none,
  yield_position_id uuid,
  primary key (id)
);
alter table public.agent_cycles enable row level security;

create table if not exists public.agent_events (
  id uuid not null default gen_random_uuid(),
  run_id text not null,
  thread_id text,
  agent text not null,
  event_type text not null,
  tool text,
  symbol text,
  direction text,
  decision text,
  conviction real,
  risk_score real,
  policy_hits jsonb,
  reason text,
  payment_tx text,
  trade_tx text,
  latency_ms integer,
  tokens_in integer,
  tokens_out integer,
  meta jsonb,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.agent_events enable row level security;

create table if not exists public.agent_macro_events (
  event_key text not null,
  source text not null,
  event_type text not null,
  country text default US,
  title text not null,
  scheduled_at timestamp with time zone not null,
  severity smallint default 3,
  risk_window_before_min integer default 120,
  risk_window_after_min integer default 60,
  state text default upcoming,
  actual jsonb,
  consensus jsonb,
  previous jsonb,
  updated_at timestamp with time zone default now(),
  primary key (event_key)
);
alter table public.agent_macro_events enable row level security;

create table if not exists public.agent_market_snapshots (
  symbol text not null,
  venue text not null default okx,
  ts timestamp with time zone not null default now(),
  price numeric,
  funding_rate numeric,
  next_funding_time timestamp with time zone,
  open_interest numeric,
  oi_ccy numeric,
  top_trader_long_pct numeric,
  top_trader_short_pct numeric,
  taker_buy_volume numeric,
  taker_sell_volume numeric,
  regime text,
  source_quality jsonb,
  derived jsonb,
  primary key (symbol, venue, ts)
);
alter table public.agent_market_snapshots enable row level security;

create table if not exists public.agent_memory (
  id bigint generated by default as identity,
  agent text not null,
  user_id uuid,
  owner_address text,
  memory_type text not null,
  content text not null,
  embedding public.vector(1536),
  importance smallint default 5,
  source_cycle_id uuid,
  tags text[],
  decay_after timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.agent_memory enable row level security;

create table if not exists public.agent_messages (
  id uuid not null default gen_random_uuid(),
  wallet_address text not null,
  advisor_name text not null,
  message text not null,
  read boolean,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.agent_messages enable row level security;

create table if not exists public.agent_positions (
  id uuid not null default gen_random_uuid(),
  chain text not null,
  token_address text not null,
  token_symbol text not null,
  entry_price numeric not null,
  amount numeric not null,
  amount_usd numeric not null,
  current_price numeric,
  unrealized_pnl numeric,
  stop_loss_pct numeric default 15,
  take_profit_pct numeric default 50,
  opened_at timestamp with time zone default now(),
  closed_at timestamp with time zone,
  close_reason text,
  primary key (id)
);
alter table public.agent_positions enable row level security;

create table if not exists public.agent_profiles (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  wallet_address text not null,
  agent_name text not null,
  voice text not null default male,
  personality text not null default analytical,
  cadence_hours integer not null default 6,
  markets jsonb not null,
  delivery jsonb not null,
  status text not null default active,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  last_run_at timestamp with time zone,
  next_run_at timestamp with time zone,
  last_error text,
  mascot jsonb,
  primary key (id)
);
alter table public.agent_profiles enable row level security;

create table if not exists public.agent_source_health (
  source text not null,
  checked_at timestamp with time zone not null default now(),
  ok boolean not null default true,
  latency_ms integer,
  freshness_s integer,
  records integer,
  quality_score numeric,
  error text,
  payload jsonb,
  primary key (source, checked_at)
);
alter table public.agent_source_health enable row level security;

create table if not exists public.api_cache (
  cache_key text not null,
  payload jsonb not null,
  expires_at timestamp with time zone not null,
  updated_at timestamp with time zone not null default now(),
  primary key (cache_key)
);
alter table public.api_cache enable row level security;

create table if not exists public.bobby_control (
  id text not null default global,
  write_freeze boolean not null,
  canary boolean not null,
  note text,
  updated_at timestamp with time zone not null default now(),
  primary key (id)
);
alter table public.bobby_control enable row level security;

create table if not exists public.bobby_early_access (
  id uuid not null default gen_random_uuid(),
  email text not null,
  email_normalized text,
  consent boolean not null default true,
  consent_text text not null,
  consent_at timestamp with time zone not null default now(),
  source_page text not null default /app,
  language text not null default en,
  campaign text not null default bobby-ios-early-access,
  referrer text,
  user_agent text,
  ip_hash text,
  unsubscribed_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (id)
);
alter table public.bobby_early_access enable row level security;

create table if not exists public.cycle_transitions (
  id bigint generated by default as identity,
  cycle_id uuid not null,
  from_state text,
  to_state text not null,
  payload jsonb,
  actor text,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.cycle_transitions enable row level security;

create table if not exists public.dm_conversations (
  telegram_user_id bigint not null,
  bot_key text not null default default,
  last_symbol text,
  last_inst_id text,
  last_verdict jsonb,
  turns jsonb not null,
  updated_at timestamp with time zone not null default now(),
  primary key (telegram_user_id, bot_key)
);
alter table public.dm_conversations enable row level security;

create table if not exists public.forum_publish_receipts (
  receipt_id uuid not null,
  wallet text not null,
  thread_id uuid,
  consumed_at timestamp with time zone not null default now(),
  primary key (receipt_id)
);
alter table public.forum_publish_receipts enable row level security;

create table if not exists public.hardness_agents (
  id bigint generated by default as identity,
  agent_id text not null,
  owner_address text not null,
  name text not null,
  agent_type text not null default trading-agent,
  version text,
  capabilities jsonb not null,
  mcp_endpoint text,
  webhook_url text,
  metadata_json jsonb not null,
  risk_policy_json jsonb not null,
  status text not null default active,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (id)
);
alter table public.hardness_agents enable row level security;

create table if not exists public.hardness_agent_sessions (
  id bigint generated by default as identity,
  session_id text not null,
  agent_id text not null,
  intent text not null,
  symbol text,
  direction text,
  request_json jsonb not null,
  context_json jsonb not null,
  decision_json jsonb not null,
  policy_result text,
  hardness_score integer,
  status text not null default received,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (id)
);
alter table public.hardness_agent_sessions enable row level security;

create table if not exists public.hardness_agent_proofs (
  id bigint generated by default as identity,
  session_id text not null,
  prediction_hash text,
  commit_tx_hash text,
  signal_tx_hash text,
  resolve_tx_hash text,
  chain_id integer not null default 196,
  created_at timestamp with time zone not null default now(),
  primary key (id)
);
alter table public.hardness_agent_proofs enable row level security;

create table if not exists public.indicator_cache (
  id uuid not null default gen_random_uuid(),
  inst_id text not null,
  timeframe text not null default 1H,
  indicators jsonb not null,
  composite_score real,
  signal text,
  conviction real,
  agreement real,
  trade_plan jsonb,
  breakdown jsonb,
  source text default OKX Agent Trade Kit,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.indicator_cache enable row level security;

create table if not exists public.llm_calls (
  id bigint generated by default as identity,
  cycle_id uuid,
  provider text not null,
  model text not null,
  agent text,
  endpoint text,
  tokens_in integer,
  tokens_out integer,
  cached_tokens integer,
  cost_usd numeric,
  cache_hit boolean,
  latency_ms integer,
  status text,
  error text,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.llm_calls enable row level security;

create table if not exists public.mcp_payment_challenges (
  challenge_id uuid not null default gen_random_uuid(),
  tool_name text not null,
  request_hash text,
  price_wei text not null default 1000000000000000,
  status text not null default pending,
  expires_at timestamp with time zone not null default (now() + '00:10:00'::interval),
  payer_address text,
  tx_hash text,
  external_agent text,
  metadata jsonb,
  created_at timestamp with time zone not null default now(),
  consumed_at timestamp with time zone,
  primary key (challenge_id)
);
alter table public.mcp_payment_challenges enable row level security;

create table if not exists public.memory_objects (
  id uuid not null default gen_random_uuid(),
  kind text not null,
  thread_id text,
  symbol text,
  direction text,
  regime text,
  conviction real,
  outcome text,
  pnl_pct real,
  lesson text not null,
  tags jsonb,
  source_events jsonb,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.memory_objects enable row level security;

create table if not exists public.sandbox_runs (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  playbook_slug text not null,
  ticker text not null,
  market_snapshot jsonb,
  alpha_text text,
  red_text text,
  cio_text text,
  cio_action text,
  cio_conviction numeric,
  judge_scores jsonb,
  guardrail_results jsonb,
  verdict_action text,
  guardrails_passed integer,
  guardrails_failed integer,
  guardrails_total integer,
  verdict_reason text,
  status text not null default completed,
  error_phase text,
  error_message text,
  ip_hash text,
  user_agent text,
  primary key (id)
);
alter table public.sandbox_runs enable row level security;

create table if not exists public.telegram_groups (
  id uuid not null default gen_random_uuid(),
  telegram_group_id bigint not null,
  telegram_group_name text,
  telegram_group_username text,
  added_by_telegram_user_id bigint,
  added_by_telegram_username text,
  bot_status text not null default pending_payment,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  last_seen_at timestamp with time zone,
  primary key (id)
);
alter table public.telegram_groups enable row level security;

create table if not exists public.trade_intents (
  id bigint generated by default as identity,
  intent_hash text not null,
  cycle_id uuid,
  user_id uuid,
  owner_address text,
  chain_id integer not null default 196,
  symbol text not null,
  direction text not null,
  size_usd numeric,
  entry_ref numeric,
  slippage_max_bps integer,
  treasury text,
  nonce bigint,
  expires_at timestamp with time zone,
  cio_signature text,
  arbiter_signature text,
  verification_status text default pending,
  rejection_reason text,
  commit_tx_hash text,
  verify_tx_hash text,
  execute_tx_hash text,
  resolve_tx_hash text,
  attestation_id text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.trade_intents enable row level security;

create table if not exists public.user_feedback (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone default now(),
  user_email text,
  wallet_address text,
  type text not null default bug,
  message text not null,
  page text,
  context jsonb,
  status text default new,
  resolution text,
  primary key (id)
);
alter table public.user_feedback enable row level security;

create table if not exists public.user_interests (
  id uuid not null default gen_random_uuid(),
  wallet_address text not null,
  asset text not null,
  context text,
  target_threshold numeric default 0.75,
  last_conviction numeric,
  last_notified_at timestamp with time zone,
  active boolean default true,
  created_at timestamp with time zone default now(),
  primary key (id)
);
alter table public.user_interests enable row level security;

create table if not exists public.agent_signals (
  id uuid not null default gen_random_uuid(),
  cycle_id uuid,
  source text not null,
  chain text,
  token_symbol text,
  token_address text,
  signal_type text,
  amount_usd numeric,
  sold_ratio_pct numeric,
  confidence numeric,
  raw_data jsonb,
  created_at timestamp with time zone default now(),
  primary key (id),
  foreign key (cycle_id) references public.agent_cycles (id)
);
alter table public.agent_signals enable row level security;

create table if not exists public.agent_trades (
  id uuid not null default gen_random_uuid(),
  cycle_id uuid,
  chain text not null,
  token_address text not null,
  token_symbol text not null,
  direction text not null,
  amount_usd numeric not null,
  entry_price numeric,
  tx_hash text,
  status text default pending,
  llm_reasoning text,
  confidence numeric,
  signal_sources text[],
  created_at timestamp with time zone default now(),
  stop_price numeric,
  target_price numeric,
  exit_price numeric,
  outcome text,
  realized_pnl_pct numeric,
  settled_at timestamp with time zone,
  expires_at timestamp with time zone,
  user_id uuid,
  owner_address text,
  intent_hash text,
  idempotency_key text,
  cio_signature text,
  arbiter_signature text,
  primary key (id),
  foreign key (cycle_id) references public.agent_cycles (id)
);
alter table public.agent_trades enable row level security;

create table if not exists public.user_digests (
  id uuid not null default gen_random_uuid(),
  cycle_id uuid,
  thread_id uuid,
  wallet_address text,
  summary text not null,
  highlights jsonb,
  positions_snapshot jsonb,
  market_snapshot jsonb,
  language text default en,
  kind text default scheduled,
  delivered_at timestamp with time zone,
  viewed_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  primary key (id),
  foreign key (cycle_id) references public.agent_cycles (id)
);
alter table public.user_digests enable row level security;

create table if not exists public.forum_threads (
  id uuid not null default gen_random_uuid(),
  topic text not null,
  trigger_reason text not null,
  trigger_data jsonb,
  status text not null default active,
  language text not null default en,
  conviction_score real,
  price_at_creation jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  symbol text,
  direction text default long,
  entry_price real,
  stop_price real,
  target_price real,
  resolution text default pending,
  resolution_price real,
  resolved_at timestamp with time zone,
  resolution_pnl_pct real,
  expires_at timestamp with time zone,
  cycle_id uuid,
  kind text default scheduled,
  execution_status text default pending,
  execution_reason text,
  resolution_tx_hash text,
  scope text not null default public,
  owner_user_id uuid,
  agent_profile_id uuid,
  owner_wallet text,
  debate_quality jsonb,
  primary key (id),
  foreign key (agent_profile_id) references public.agent_profiles (id)
);
alter table public.forum_threads enable row level security;

create table if not exists public.forum_posts (
  id uuid not null default gen_random_uuid(),
  thread_id uuid not null,
  agent text not null,
  content text not null,
  data_snapshot jsonb,
  upvotes integer not null,
  created_at timestamp with time zone not null default now(),
  primary key (id),
  foreign key (thread_id) references public.forum_threads (id)
);
alter table public.forum_posts enable row level security;

create table if not exists public.agent_position_rechecks (
  id uuid not null default gen_random_uuid(),
  thread_id uuid,
  symbol text not null,
  direction text not null,
  checked_at timestamp with time zone default now(),
  trigger_type text not null,
  hard_invalidated boolean,
  action text default hold,
  reason text,
  metrics jsonb,
  primary key (id),
  foreign key (thread_id) references public.forum_threads (id)
);
alter table public.agent_position_rechecks enable row level security;

create table if not exists public.mcp_payment_receipts (
  tx_hash text not null,
  challenge_id uuid not null,
  payer_address text not null,
  tool_name text not null,
  block_number bigint not null,
  value_wei text not null,
  value_okb text not null,
  verified_at timestamp with time zone not null default now(),
  response_hash text,
  explorer_url text,
  primary key (tx_hash),
  foreign key (challenge_id) references public.mcp_payment_challenges (challenge_id)
);
alter table public.mcp_payment_receipts enable row level security;

create table if not exists public.telegram_connections (
  id uuid not null default gen_random_uuid(),
  wallet_address text,
  agent_profile_id uuid,
  telegram_user_id bigint not null,
  telegram_chat_id bigint not null,
  telegram_username text,
  connect_token text,
  status text not null default active,
  message_count integer not null,
  is_premium boolean not null,
  premium_until timestamp with time zone,
  connected_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (id),
  foreign key (agent_profile_id) references public.agent_profiles (id)
);
alter table public.telegram_connections enable row level security;

create table if not exists public.telegram_activation_sessions (
  id uuid not null default gen_random_uuid(),
  telegram_group_id bigint not null,
  telegram_user_id bigint not null,
  payer_wallet_address text,
  x402_reference text not null,
  resource text not null,
  payment_asset text not null default USDT,
  payment_amount_atomic text not null default 10000,
  pay_to text not null default 0xF841b428E6d743187D7BE2242eccC1078fdE2395,
  valid_until timestamp with time zone not null,
  payment_payload_hash text,
  status text not null default pending,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (id),
  foreign key (telegram_group_id) references public.telegram_groups (telegram_group_id)
);
alter table public.telegram_activation_sessions enable row level security;

create table if not exists public.telegram_subscriptions (
  id uuid not null default gen_random_uuid(),
  telegram_group_id bigint not null,
  payer_wallet_address text not null,
  payment_tx_hash text,
  payment_asset text not null default USDT,
  payment_amount_atomic text not null,
  chain_id integer not null default 196,
  x402_reference text not null,
  verification_response jsonb,
  settlement_response jsonb,
  activated_at timestamp with time zone not null default now(),
  expires_at timestamp with time zone not null,
  status text not null default active,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (id),
  foreign key (telegram_group_id) references public.telegram_groups (telegram_group_id)
);
alter table public.telegram_subscriptions enable row level security;
