// GENERATED by scripts/gen-hardness-abi.mts from contracts/out/BobbyAdversarialBounties.sol/BobbyAdversarialBounties.json — do not edit by hand.
// scripts/test-bounties-abi-anvil.mts fails if this file drifts from the artifact.
export const ADVERSARIAL_BOUNTIES_ABI = [
 {
  "type": "constructor",
  "inputs": [
   {
    "name": "_resolver",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "_absoluteMinBounty",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "_initialMinBounty",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "receive",
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "ABSOLUTE_MIN_BOUNTY",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_BOND_MULTIPLIER",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_DISPUTE_WINDOW",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_SETTLEMENT_TIMEOUT",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MIN_DISPUTE_WINDOW",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MIN_SETTLEMENT_TIMEOUT",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "acceptOwnership",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "bounties",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "threadHash",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "poster",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "reward",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "winner",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "createdAt",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "claimWindowSecs",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "dimension",
    "type": "uint8",
    "internalType": "enum BobbyAdversarialBounties.Dimension"
   },
   {
    "name": "status",
    "type": "uint8",
    "internalType": "enum BobbyAdversarialBounties.BountyStatus"
   },
   {
    "name": "challengeCount",
    "type": "uint16",
    "internalType": "uint16"
   },
   {
    "name": "gracePeriodSnapshot",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyBond",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "challengeBond",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "challengeBondOf",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "challengeCount",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "challengeGracePeriod",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "defaultClaimWindow",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "disputeBondOf",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "disputeResolution",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "disputeSettlementTimeout",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "disputeWindow",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "disputedAt",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "disputedBy",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "finalizeResolution",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "getBounty",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct BobbyAdversarialBounties.Bounty",
    "components": [
     {
      "name": "threadHash",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "poster",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "reward",
      "type": "uint96",
      "internalType": "uint96"
     },
     {
      "name": "winner",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "createdAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "claimWindowSecs",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "dimension",
      "type": "uint8",
      "internalType": "enum BobbyAdversarialBounties.Dimension"
     },
     {
      "name": "status",
      "type": "uint8",
      "internalType": "enum BobbyAdversarialBounties.BountyStatus"
     },
     {
      "name": "challengeCount",
      "type": "uint16",
      "internalType": "uint16"
     },
     {
      "name": "gracePeriodSnapshot",
      "type": "uint32",
      "internalType": "uint32"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getChallenges",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "_offset",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "_limit",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "page",
    "type": "tuple[]",
    "internalType": "struct BobbyAdversarialBounties.Challenge[]",
    "components": [
     {
      "name": "challenger",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "evidenceHash",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "submittedAt",
      "type": "uint64",
      "internalType": "uint64"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "hasChallenged",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "maxChallenges",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint16",
    "internalType": "uint16"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "minBounty",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "nextBountyId",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pause",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "paused",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingOwner",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingWithdrawals",
  "inputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "postBounty",
  "inputs": [
   {
    "name": "_threadId",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "_dimension",
    "type": "uint8",
    "internalType": "enum BobbyAdversarialBounties.Dimension"
   },
   {
    "name": "_claimWindowSecs",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "resolutionFinalizeAfter",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "resolutionProposedAt",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "resolveBounty",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "_winner",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "resolveStalledDispute",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "resolver",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "setChallengeBond",
  "inputs": [
   {
    "name": "_bond",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setChallengeGracePeriod",
  "inputs": [
   {
    "name": "_grace",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setDefaultClaimWindow",
  "inputs": [
   {
    "name": "_window",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setDisputeSettlementTimeout",
  "inputs": [
   {
    "name": "_seconds",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setDisputeWindow",
  "inputs": [
   {
    "name": "_seconds",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMaxChallenges",
  "inputs": [
   {
    "name": "_max",
    "type": "uint16",
    "internalType": "uint16"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMinBounty",
  "inputs": [
   {
    "name": "_min",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setResolver",
  "inputs": [
   {
    "name": "_newResolver",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setTreasury",
  "inputs": [
   {
    "name": "_treasury",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "settleDispute",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "_winner",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "settlementAfter",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "submitChallenge",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "_evidenceHash",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "transferOwnership",
  "inputs": [
   {
    "name": "_new",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "treasury",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "unpause",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "withdraw",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "withdrawBounty",
  "inputs": [
   {
    "name": "_bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "event",
  "name": "BountyDisputeSettled",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "refundedToPoster",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyDisputeTimedOut",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyPosted",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "poster",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "threadHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "dimension",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum BobbyAdversarialBounties.Dimension"
   },
   {
    "name": "reward",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   },
   {
    "name": "claimWindowSecs",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolutionDisputed",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolutionProposed",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "reward",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   },
   {
    "name": "finalizeAfter",
    "type": "uint64",
    "indexed": false,
    "internalType": "uint64"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolved",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "reward",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyWithdrawn",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "poster",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ChallengeBondUpdated",
  "inputs": [
   {
    "name": "oldBond",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   },
   {
    "name": "newBond",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ChallengeSubmitted",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "challenger",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "evidenceHash",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "challengeIndex",
    "type": "uint16",
    "indexed": false,
    "internalType": "uint16"
   },
   {
    "name": "submittedAt",
    "type": "uint64",
    "indexed": false,
    "internalType": "uint64"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "DisputeSettlementTimeoutUpdated",
  "inputs": [
   {
    "name": "oldTimeout",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "newTimeout",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "DisputeWindowUpdated",
  "inputs": [
   {
    "name": "oldWindow",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "newWindow",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OwnershipTransferStarted",
  "inputs": [
   {
    "name": "from",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "to",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OwnershipTransferred",
  "inputs": [
   {
    "name": "from",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "to",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Paused",
  "inputs": [
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ResolverUpdated",
  "inputs": [
   {
    "name": "oldResolver",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "newResolver",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "TreasuryUpdated",
  "inputs": [
   {
    "name": "oldTreasury",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "newTreasury",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Unpaused",
  "inputs": [
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Withdrawal",
  "inputs": [
   {
    "name": "to",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 }
] as const;
