// GENERATED by scripts/gen-hardness-abi.mts from contracts/out/HardnessRegistry.sol/HardnessRegistry.json — do not edit by hand.
// scripts/test-hardness-abi-anvil.mts fails if this file drifts from the artifact.
export const HARDNESS_REGISTRY_ABI = [
 {
  "type": "constructor",
  "inputs": [
   {
    "name": "initialResolvers",
    "type": "address[]",
    "internalType": "address[]"
   },
   {
    "name": "initialThreshold",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "_absoluteMinBounty",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "_registrationStake",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "_initialMinBounty",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "ABSOLUTE_MIN_BOUNTY",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_BOUNTY_BOND_MULTIPLIER",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_BOUNTY_DISPUTE_WINDOW",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_BOUNTY_SETTLEMENT_TIMEOUT",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MIN_BOUNTY_DISPUTE_WINDOW",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MIN_BOUNTY_SETTLEMENT_TIMEOUT",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "PNL_TOLERANCE_BPS",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "REGISTRATION_STAKE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "acceptOwnership",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "agentProfiles",
  "inputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "registered",
    "type": "bool",
    "internalType": "bool"
   },
   {
    "name": "registeredAt",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "stake",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "metadataURI",
    "type": "string",
    "internalType": "string"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "approveBountyResolution",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "bounties",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "threadHash",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "poster",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "winner",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "reward",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "createdAt",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "claimWindowSecs",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "challengeCount",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "approvalCount",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "approvalThreshold",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "gracePeriodSnapshot",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "dimension",
    "type": "uint8",
    "internalType": "enum HardnessRegistry.BountyDimension"
   },
   {
    "name": "status",
    "type": "uint8",
    "internalType": "enum HardnessRegistry.BountyStatus"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyBond",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyChallengeBond",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyChallengeBondOf",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyDisputeBondOf",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyDisputeSettlementTimeout",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyDisputeWindow",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyDisputedAt",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyDisputedBy",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyResolutionFinalizeAfter",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountyResolutionProposedAt",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bountySettlementAfter",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "certifyHardness",
  "inputs": [
   {
    "name": "predictionHash",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "hardnessScore",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "challengeConsumed",
  "inputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "challengeGracePeriod",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "commitPrediction",
  "inputs": [
   {
    "name": "predictionHash",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "conviction",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "entry",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "target",
    "type": "uint96",
    "internalType": "uint96"
   },
   {
    "name": "stop",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "defaultClaimWindow",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "defaultSignalTTL",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "disputeBountyResolution",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "expirePrediction",
  "inputs": [
   {
    "name": "predictionHash",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "finalizeBountyResolution",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "getAgentStats",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "wins",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "losses",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "winRateBps",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getAgentStatsFull",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct HardnessRegistry.AgentStats",
    "components": [
     {
      "name": "wins",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "losses",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "breakEvens",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "expired",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "totalResolved",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "winRateBps",
      "type": "uint32",
      "internalType": "uint32"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getBounty",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct HardnessRegistry.Bounty",
    "components": [
     {
      "name": "threadHash",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "poster",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "winner",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "reward",
      "type": "uint96",
      "internalType": "uint96"
     },
     {
      "name": "createdAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "claimWindowSecs",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "challengeCount",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "approvalCount",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "approvalThreshold",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "gracePeriodSnapshot",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "dimension",
      "type": "uint8",
      "internalType": "enum HardnessRegistry.BountyDimension"
     },
     {
      "name": "status",
      "type": "uint8",
      "internalType": "enum HardnessRegistry.BountyStatus"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getChallenges",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "offset",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "limit",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "page",
    "type": "tuple[]",
    "internalType": "struct HardnessRegistry.Challenge[]",
    "components": [
     {
      "name": "challenger",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "evidenceHash",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "submittedAt",
      "type": "uint64",
      "internalType": "uint64"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getPrediction",
  "inputs": [
   {
    "name": "predictionHash",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct HardnessRegistry.Prediction",
    "components": [
     {
      "name": "agent",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "committedAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "minResolveAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "resolvedAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "conviction",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "result",
      "type": "uint8",
      "internalType": "enum HardnessRegistry.PredictionResult"
     },
     {
      "name": "entryPrice",
      "type": "uint96",
      "internalType": "uint96"
     },
     {
      "name": "hardnessScore",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "targetPrice",
      "type": "uint96",
      "internalType": "uint96"
     },
     {
      "name": "stopPrice",
      "type": "uint96",
      "internalType": "uint96"
     },
     {
      "name": "exitPrice",
      "type": "uint96",
      "internalType": "uint96"
     },
     {
      "name": "pnlBps",
      "type": "int32",
      "internalType": "int32"
     },
     {
      "name": "symbol",
      "type": "string",
      "internalType": "string"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getService",
  "inputs": [
   {
    "name": "serviceId",
    "type": "string",
    "internalType": "string"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct HardnessRegistry.Service",
    "components": [
     {
      "name": "owner",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "recipient",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "priceWei",
      "type": "uint128",
      "internalType": "uint128"
     },
     {
      "name": "totalRevenue",
      "type": "uint128",
      "internalType": "uint128"
     },
     {
      "name": "totalCalls",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "createdAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "active",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "serviceId",
      "type": "string",
      "internalType": "string"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getSignal",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct HardnessRegistry.Signal",
    "components": [
     {
      "name": "agent",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "timestamp",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "expiresAt",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "conviction",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "hardnessScore",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "direction",
      "type": "uint8",
      "internalType": "enum HardnessRegistry.Direction"
     },
     {
      "name": "context",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "symbol",
      "type": "string",
      "internalType": "string"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "hardnessScorer",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "hasApprovedResolution",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "hasChallenged",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "maxChallengesPerBounty",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "minBounty",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "minPredictionAge",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "nextBountyId",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pause",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "paused",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "payForService",
  "inputs": [
   {
    "name": "challengeId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "serviceId",
    "type": "string",
    "internalType": "string"
   }
  ],
  "outputs": [],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "pendingOwner",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingWithdrawals",
  "inputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "postBounty",
  "inputs": [
   {
    "name": "threadId",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "dimension",
    "type": "uint8",
    "internalType": "enum HardnessRegistry.BountyDimension"
   },
   {
    "name": "claimWindowSecs",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "predictionTTL",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "proposedWinner",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "publishSignal",
  "inputs": [
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "hardnessScore",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "direction",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "conviction",
    "type": "uint8",
    "internalType": "uint8"
   },
   {
    "name": "context",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "registerAgent",
  "inputs": [
   {
    "name": "metadataURI",
    "type": "string",
    "internalType": "string"
   }
  ],
  "outputs": [],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "registerService",
  "inputs": [
   {
    "name": "serviceId",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "priceWei",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "recipient",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "resolutionRound",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "resolvePrediction",
  "inputs": [
   {
    "name": "predictionHash",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "pnlBps",
    "type": "int32",
    "internalType": "int32"
   },
   {
    "name": "result",
    "type": "uint8",
    "internalType": "enum HardnessRegistry.PredictionResult"
   },
   {
    "name": "exitPrice",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "resolveStalledBountyDispute",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "resolverCount",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "resolverThreshold",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "resolvers",
  "inputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "serviceKeys",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "setBountyChallengeBond",
  "inputs": [
   {
    "name": "bond",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setBountyDisputeSettlementTimeout",
  "inputs": [
   {
    "name": "secondsTimeout",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setBountyDisputeWindow",
  "inputs": [
   {
    "name": "secondsWindow",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setChallengeGracePeriod",
  "inputs": [
   {
    "name": "newGracePeriod",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setDefaultClaimWindow",
  "inputs": [
   {
    "name": "newWindow",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setDefaultSignalTTL",
  "inputs": [
   {
    "name": "newTTL",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setHardnessScorer",
  "inputs": [
   {
    "name": "newScorer",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMaxChallengesPerBounty",
  "inputs": [
   {
    "name": "newMax",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMinBounty",
  "inputs": [
   {
    "name": "newMinBounty",
    "type": "uint96",
    "internalType": "uint96"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMinPredictionAge",
  "inputs": [
   {
    "name": "newAge",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setPredictionTTL",
  "inputs": [
   {
    "name": "newTTL",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setResolverThreshold",
  "inputs": [
   {
    "name": "newThreshold",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setServiceStatus",
  "inputs": [
   {
    "name": "serviceId",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "active",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setTreasury",
  "inputs": [
   {
    "name": "newTreasury",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "settleBountyDispute",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "signalSymbolIndex",
  "inputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "signalSymbols",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "slashAgent",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "reason",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "submitChallenge",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "evidenceHash",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "symbolAgentSeen",
  "inputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "symbolName",
  "inputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "string",
    "internalType": "string"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "transferOwnership",
  "inputs": [
   {
    "name": "newOwner",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "treasury",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "unpause",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "updateResolver",
  "inputs": [
   {
    "name": "resolver",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "active",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "withdraw",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "withdrawBounty",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "event",
  "name": "AgentMetadataUpdated",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "metadataURI",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "AgentRegistered",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "metadataURI",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "AgentSlashed",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "reason",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyChallengeBondUpdated",
  "inputs": [
   {
    "name": "oldBond",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   },
   {
    "name": "newBond",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyDisputeSettled",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "refundedToPoster",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyDisputeSettlementTimeoutUpdated",
  "inputs": [
   {
    "name": "oldTimeout",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "newTimeout",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyDisputeTimedOut",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "poster",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyDisputeWindowUpdated",
  "inputs": [
   {
    "name": "oldWindow",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "newWindow",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyPosted",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "poster",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "threadHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "dimension",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum HardnessRegistry.BountyDimension"
   },
   {
    "name": "reward",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolutionApproved",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "round",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "resolver",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   },
   {
    "name": "approvals",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   },
   {
    "name": "threshold",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolutionDisputed",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolutionProposed",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "reward",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   },
   {
    "name": "finalizeAfter",
    "type": "uint64",
    "indexed": false,
    "internalType": "uint64"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyResolved",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "winner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "reward",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BountyWithdrawn",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "poster",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint96",
    "indexed": false,
    "internalType": "uint96"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ChallengeSubmitted",
  "inputs": [
   {
    "name": "bountyId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "challenger",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "evidenceHash",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "HardnessCertified",
  "inputs": [
   {
    "name": "predictionHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "score",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OwnershipTransferStarted",
  "inputs": [
   {
    "name": "currentOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "pendingOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OwnershipTransferred",
  "inputs": [
   {
    "name": "previousOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "newOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Paused",
  "inputs": [
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PredictionCommitted",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "predictionHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "symbol",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "conviction",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PredictionExpired",
  "inputs": [
   {
    "name": "caller",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "predictionHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PredictionResolved",
  "inputs": [
   {
    "name": "resolver",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "predictionHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "result",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum HardnessRegistry.PredictionResult"
   },
   {
    "name": "pnlBps",
    "type": "int32",
    "indexed": false,
    "internalType": "int32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ResolverThresholdUpdated",
  "inputs": [
   {
    "name": "oldThreshold",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   },
   {
    "name": "newThreshold",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ResolverUpdated",
  "inputs": [
   {
    "name": "resolver",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "active",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ServicePayment",
  "inputs": [
   {
    "name": "payer",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "recipient",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "serviceId",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ServiceRegistered",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "serviceId",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "priceWei",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "recipient",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ServiceUpdated",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "serviceId",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "priceWei",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "recipient",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   },
   {
    "name": "active",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "SignalPublished",
  "inputs": [
   {
    "name": "agent",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "symbolHash",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "symbol",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "hardnessScore",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   },
   {
    "name": "direction",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   },
   {
    "name": "conviction",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   },
   {
    "name": "context",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "TreasuryUpdated",
  "inputs": [
   {
    "name": "oldTreasury",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "newTreasury",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Unpaused",
  "inputs": [
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Withdrawal",
  "inputs": [
   {
    "name": "account",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "error",
  "name": "AlreadyApproved",
  "inputs": []
 },
 {
  "type": "error",
  "name": "AlreadyChallenged",
  "inputs": []
 },
 {
  "type": "error",
  "name": "AlreadyExists",
  "inputs": []
 },
 {
  "type": "error",
  "name": "AlreadyResolved",
  "inputs": []
 },
 {
  "type": "error",
  "name": "ChallengeConsumed",
  "inputs": []
 },
 {
  "type": "error",
  "name": "ContractPaused",
  "inputs": []
 },
 {
  "type": "error",
  "name": "Expired",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InsufficientPayment",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InsufficientStake",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidAddress",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidResult",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidValue",
  "inputs": []
 },
 {
  "type": "error",
  "name": "MaxChallenges",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NoResolvers",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotAuthorized",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotFound",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotOwner",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotRegistered",
  "inputs": []
 },
 {
  "type": "error",
  "name": "Reentrancy",
  "inputs": []
 },
 {
  "type": "error",
  "name": "ServiceInactive",
  "inputs": []
 },
 {
  "type": "error",
  "name": "ThresholdTooHigh",
  "inputs": []
 },
 {
  "type": "error",
  "name": "TooSoon",
  "inputs": []
 },
 {
  "type": "error",
  "name": "TransferFailed",
  "inputs": []
 },
 {
  "type": "error",
  "name": "WindowExpired",
  "inputs": []
 }
] as const;
