
/* ============================================================
   Strings (en / es), selected by session.language. Read-derived
   copy (verdicts, satellites, thesis rows, failures, XP) comes
   from NucleoReadModel; everything the onboarding itself says
   lives here. No advice or outcome language (lint: nucleo.lint()).
   '|' in a spoken line is a caption page break (never spoken).
   ============================================================ */
var STR = {
  en: {
    'hello': 'I’m Bobby. Before you trade anything,|three of me argue about it. Then you decide.',
    'pick.prompt': 'Who lives in here?',
    'pick.count': '{i} of {n}',
    'pick.choose': 'Choose {name}',
    'pick.hint': 'Swipe the sphere · Tap to choose',
    'pick.chosen': '{name} it is.',
    'pick.failed': 'That didn’t stick · Tap to choose again',
    'ask.title': 'Ask before you trade.',
    'ask.sub': 'Hold the button and talk, or tap a question.',
    'chip.look': 'How is {sym} looking?',
    'chip.move': 'Why is {sym} moving today?',
    'chip.again': 'Try another question',
    'perm.title': 'I only listen while you hold.',
    'perm.body': 'iOS will ask for the microphone and speech recognition once.',
    "perm.bodyWeb": "Your browser will ask for the microphone once. Its speech service turns your voice into text.",
    'perm.go': 'Continue',
    'ask.gotIt': 'Got it. Hold and ask.',
    'hint.hold': 'Hold to ask',
    'hint.release': 'Release to send',
    'hint.type': 'Type your question',
    "hint.micOff": "Mic is off · tap to type",
    'hint.sttEmpty': 'I didn’t catch that · Hold and try again',
    'hint.sttError': 'The mic stopped · Hold to try again',
    'type.placeholder': 'Ask about a stock or a crypto',
    'type.send': 'Send',
    'risk.intro': 'Before I answer, one thing.',
    'risk.introOnly': 'One thing before we go on.',
    'risk.hold': 'Hold to agree',
    'risk.notice': 'Read the full notice',
    'risk.failed': 'That didn’t go through · Hold again',
    'think.elapsed': '{s} s',
    'think.still': 'Still weighing · deep reads take up to a minute',
    'think.long': 'Taking longer than usual · tap to cancel',
    'think.forming': 'Verdict forming',
    'hint.conviction': 'Conviction = how sure Bobby is in this read',
    'hint.pull': 'Pull down for the full read',
    'pill.fullRead': 'See the full read',
    'save.failed': 'Couldn’t save · Try again',
    'evolution': 'Level {n} · {name}',
    'unlocked': 'Unlocked · {names}',
    'sheet.title': 'Keep your theses.',
    'sheet.body': 'Back up your theses and XP so they survive a new phone.',
    'sheet.apple': 'Sign in with Apple',
    'sheet.notnow': 'Not now',
    'sheet.unavailable': 'Sign-in isn’t available right now. Your thesis stays on this device.',
    'sheet.failed': 'Sign-in didn’t finish. You can try again later.',
    'isla.seed': 'Your island got its first seed.',
    'isla.seedSub': 'It grows when this read closes.',
    'isla.bloom': 'Your island grew its first piece.',
    'isla.card.title': 'Island · size {size}',
    'isla.card.body': '{pieces} pieces · {seeds} growing',
    'home.morning': 'Good morning.', 'home.afternoon': 'Good afternoon.', 'home.evening': 'Good evening.',
    'home.saved': 'Your {sym} thesis is saved.',
    'home.none': 'Ask me about any stock or crypto.',
    'home.hint': 'Hold to ask · Swipe the sphere',
    'gsat': '{sym} · {word}',
    'chart.now': 'NOW',
    'asof': 'as of {time}',
    'aria.listening': 'Bobby is listening',
    'aria.debate': 'Three agents debating',
    'aria.bobby': 'Bobby',
    'aria.pill': 'Ask Bobby, hold to talk',
    'aria.close': 'Close read',
    'pause': 'Paused'
  },
  es: {
    'hello': 'Soy Bobby. Antes de que operes,|tres de mí lo discuten. Luego tú decides.',
    'pick.prompt': '¿Quién vive aquí?',
    'pick.count': '{i} de {n}',
    'pick.choose': 'Elegir a {name}',
    'pick.hint': 'Desliza la esfera · Toca para elegir',
    'pick.chosen': 'Elegiste a {name}.',
    'pick.failed': 'No se guardó · Toca para elegir otra vez',
    'ask.title': 'Pregunta antes de operar.',
    'ask.sub': 'Mantén el botón y habla, o toca una pregunta.',
    'chip.look': '¿Cómo se ve {sym}?',
    'chip.move': '¿Por qué se mueve {sym} hoy?',
    'chip.again': 'Prueba otra pregunta',
    'perm.title': 'Solo escucho mientras mantienes.',
    'perm.body': 'iOS te pedirá una vez el micrófono y el reconocimiento de voz.',
    "perm.bodyWeb": "Tu navegador pedirá el micrófono una vez. Su servicio de voz convierte tu voz en texto.",
    'perm.go': 'Continuar',
    'ask.gotIt': 'Listo. Mantén y pregunta.',
    'hint.hold': 'Mantén para preguntar',
    'hint.release': 'Suelta para enviar',
    'hint.type': 'Escribe tu pregunta',
    "hint.micOff": "Micrófono apagado · toca para escribir",
    'hint.sttEmpty': 'No te escuché · Mantén e intenta de nuevo',
    'hint.sttError': 'El micrófono se detuvo · Mantén para intentar',
    'type.placeholder': 'Pregunta por una acción o una cripto',
    'type.send': 'Enviar',
    'risk.intro': 'Antes de responder, una cosa.',
    'risk.introOnly': 'Una cosa antes de seguir.',
    'risk.hold': 'Mantén para aceptar',
    'risk.notice': 'Leer el aviso completo',
    'risk.failed': 'No se registró · Mantén otra vez',
    'think.elapsed': '{s} s',
    'think.still': 'Sigue deliberando · una lectura a fondo tarda hasta un minuto',
    'think.long': 'Tarda más de lo normal · toca para cancelar',
    'think.forming': 'Veredicto en camino',
    'hint.conviction': 'Convicción = qué tan seguro está Bobby de esta lectura',
    'hint.pull': 'Desliza hacia abajo para la lectura completa',
    'pill.fullRead': 'Ver la lectura',
    'save.failed': 'No se pudo guardar · Intenta de nuevo',
    'evolution': 'Nivel {n} · {name}',
    'unlocked': 'Desbloqueado · {names}',
    'sheet.title': 'Conserva tus tesis.',
    'sheet.body': 'Respalda tus tesis y tu XP para no perderlos al cambiar de teléfono.',
    'sheet.apple': 'Iniciar sesión con Apple',
    'sheet.notnow': 'Ahora no',
    'sheet.unavailable': 'Ahora no se puede iniciar sesión. Tu tesis se queda en este dispositivo.',
    'sheet.failed': 'No se completó el inicio de sesión. Puedes intentarlo más tarde.',
    'isla.seed': 'Tu isla recibió su primera semilla.',
    'isla.seedSub': 'Crece cuando esta lectura se cierre.',
    'isla.bloom': 'Tu isla creció su primera pieza.',
    'isla.card.title': 'Isla · tamaño {size}',
    'isla.card.body': '{pieces} piezas · {seeds} creciendo',
    'home.morning': 'Buenos días.', 'home.afternoon': 'Buenas tardes.', 'home.evening': 'Buenas noches.',
    'home.saved': 'Tu tesis de {sym} está guardada.',
    'home.none': 'Pregúntame por cualquier acción o cripto.',
    'home.hint': 'Mantén para preguntar · Desliza la esfera',
    'gsat': '{sym} · {word}',
    'chart.now': 'AHORA',
    'asof': 'a las {time}',
    'aria.listening': 'Bobby está escuchando',
    'aria.debate': 'Tres agentes debatiendo',
    'aria.bobby': 'Bobby',
    'aria.pill': 'Pregunta a Bobby, mantén para hablar',
    'aria.close': 'Cerrar lectura',
    'pause': 'Pausa'
  }
,
  fr: {
    "hello": "Je suis Bobby. Avant toute opération,|trois versions de moi en débattent. Ensuite, vous décidez.",
    "pick.prompt": "Qui habite ici ?",
    "pick.count": "{i} sur {n}",
    "pick.choose": "Choisir {name}",
    "pick.hint": "Balayez la sphère · touchez pour choisir",
    "pick.chosen": "Vous avez choisi {name}.",
    "pick.failed": "Non enregistré · touchez pour réessayer",
    "ask.title": "Demandez avant d’agir.",
    "ask.sub": "Maintenez le bouton et parlez, ou touchez une question.",
    "chip.look": "Que penser de {sym} ?",
    "chip.move": "Pourquoi {sym} bouge aujourd’hui ?",
    "chip.again": "Poser une autre question",
    "perm.title": "J’écoute seulement pendant l’appui.",
    "perm.body": "iOS demandera une fois l’accès au micro et à la reconnaissance vocale.",
    "perm.bodyWeb": "Votre navigateur demandera une fois l’accès au micro. Son service vocal transcrit votre voix.",
    "perm.go": "Continuer",
    "ask.gotIt": "Compris. Maintenez et demandez.",
    "hint.hold": "Maintenez pour demander",
    "hint.release": "Relâchez pour envoyer",
    "hint.type": "Écrivez votre question",
    "hint.micOff": "Micro désactivé · touchez pour écrire",
    "hint.sttEmpty": "Je n’ai pas compris · maintenez et réessayez",
    "hint.sttError": "Le micro s’est arrêté · maintenez pour réessayer",
    "type.placeholder": "Une question sur une action ou une crypto",
    "type.send": "Envoyer",
    "risk.intro": "Avant de répondre, une précision.",
    "risk.introOnly": "Une précision avant de continuer.",
    "risk.hold": "Maintenez pour accepter",
    "risk.notice": "Lire l’avertissement complet",
    "risk.failed": "Non enregistré · maintenez à nouveau",
    "think.elapsed": "{s} s",
    "think.still": "L’analyse continue · jusqu’à une minute",
    "think.long": "Plus long que prévu · touchez pour annuler",
    "think.forming": "Conclusion en préparation",
    "hint.conviction": "Conviction = degré de confiance de Bobby dans cette analyse",
    "hint.pull": "Glissez vers le bas pour l’analyse complète",
    "pill.fullRead": "Voir l’analyse complète",
    "save.failed": "Enregistrement impossible · réessayez",
    "evolution": "Niveau {n} · {name}",
    "unlocked": "Débloqué · {names}",
    "sheet.title": "Conservez vos thèses.",
    "sheet.body": "Sauvegardez vos thèses et votre XP pour les retrouver sur un nouveau téléphone.",
    "sheet.apple": "Se connecter avec Apple",
    "sheet.notnow": "Plus tard",
    "sheet.unavailable": "La connexion est indisponible. Votre thèse reste sur cet appareil.",
    "sheet.failed": "La connexion n’a pas abouti. Vous pourrez réessayer plus tard.",
    "isla.seed": "Votre île a reçu sa première graine.",
    "isla.seedSub": "Elle grandit à la clôture de cette analyse.",
    "isla.bloom": "Votre île a gagné son premier élément.",
    "isla.card.title": "Île · taille {size}",
    "isla.card.body": "{pieces} éléments · {seeds} en croissance",
    "home.morning": "Bonjour.",
    "home.afternoon": "Bon après-midi.",
    "home.evening": "Bonsoir.",
    "home.saved": "Votre thèse sur {sym} est enregistrée.",
    "home.none": "Interrogez-moi sur une action ou une crypto.",
    "home.hint": "Maintenez pour demander · balayez la sphère",
    "gsat": "{sym} · {word}",
    "chart.now": "ACTUEL",
    "asof": "au {time}",
    "aria.listening": "Bobby écoute",
    "aria.debate": "Trois agents débattent",
    "aria.bobby": "Bobby",
    "aria.pill": "Demandez à Bobby, maintenez pour parler",
    "aria.close": "Fermer l’analyse",
    "pause": "En pause"
  },
  pt: {
    "hello": "Sou o Bobby. Antes de qualquer operação,|três versões de mim discutem a questão. Depois, decide.",
    "pick.prompt": "Quem vive aqui?",
    "pick.count": "{i} de {n}",
    "pick.choose": "Escolher {name}",
    "pick.hint": "Deslize a esfera · toque para escolher",
    "pick.chosen": "Escolheu {name}.",
    "pick.failed": "Não foi guardado · toque para tentar novamente",
    "ask.title": "Pergunte antes de negociar.",
    "ask.sub": "Mantenha o botão e fale, ou toque numa pergunta.",
    "chip.look": "Como está {sym}?",
    "chip.move": "Porque está {sym} a mover-se hoje?",
    "chip.again": "Fazer outra pergunta",
    "perm.title": "Só ouço enquanto mantém o botão.",
    "perm.body": "O iOS pedirá uma vez acesso ao microfone e ao reconhecimento de voz.",
    "perm.bodyWeb": "O navegador pedirá uma vez acesso ao microfone. O serviço de voz transforma a sua voz em texto.",
    "perm.go": "Continuar",
    "ask.gotIt": "Entendido. Mantenha e pergunte.",
    "hint.hold": "Mantenha para perguntar",
    "hint.release": "Solte para enviar",
    "hint.type": "Escreva a sua pergunta",
    "hint.micOff": "Microfone desligado · toque para escrever",
    "hint.sttEmpty": "Não percebi · mantenha e tente novamente",
    "hint.sttError": "O microfone parou · mantenha para tentar novamente",
    "type.placeholder": "Pergunte sobre uma ação ou cripto",
    "type.send": "Enviar",
    "risk.intro": "Antes de responder, uma coisa.",
    "risk.introOnly": "Uma coisa antes de continuar.",
    "risk.hold": "Mantenha para aceitar",
    "risk.notice": "Ler o aviso completo",
    "risk.failed": "Não foi registado · mantenha novamente",
    "think.elapsed": "{s} s",
    "think.still": "A análise continua · pode demorar até um minuto",
    "think.long": "Mais demorado que o habitual · toque para cancelar",
    "think.forming": "Conclusão em preparação",
    "hint.conviction": "Convicção = grau de confiança do Bobby nesta análise",
    "hint.pull": "Deslize para baixo para a análise completa",
    "pill.fullRead": "Ver a análise completa",
    "save.failed": "Não foi possível guardar · tente novamente",
    "evolution": "Nível {n} · {name}",
    "unlocked": "Desbloqueado · {names}",
    "sheet.title": "Conserve as suas teses.",
    "sheet.body": "Guarde uma cópia das teses e do XP para os manter ao mudar de telefone.",
    "sheet.apple": "Iniciar sessão com Apple",
    "sheet.notnow": "Agora não",
    "sheet.unavailable": "O início de sessão não está disponível. A sua tese fica neste dispositivo.",
    "sheet.failed": "O início de sessão não foi concluído. Pode tentar mais tarde.",
    "isla.seed": "A sua ilha recebeu a primeira semente.",
    "isla.seedSub": "Cresce quando esta análise terminar.",
    "isla.bloom": "A sua ilha ganhou a primeira peça.",
    "isla.card.title": "Ilha · tamanho {size}",
    "isla.card.body": "{pieces} peças · {seeds} a crescer",
    "home.morning": "Bom dia.",
    "home.afternoon": "Boa tarde.",
    "home.evening": "Boa noite.",
    "home.saved": "A sua tese de {sym} foi guardada.",
    "home.none": "Pergunte sobre qualquer ação ou cripto.",
    "home.hint": "Mantenha para perguntar · deslize a esfera",
    "gsat": "{sym} · {word}",
    "chart.now": "AGORA",
    "asof": "às {time}",
    "aria.listening": "O Bobby está a ouvir",
    "aria.debate": "Três agentes a debater",
    "aria.bobby": "Bobby",
    "aria.pill": "Pergunte ao Bobby, mantenha para falar",
    "aria.close": "Fechar análise",
    "pause": "Em pausa"
  }
,
  it: {
    "hello": "Sono Bobby. Prima di ogni operazione,|tre versioni di me ne discutono. Poi decidi tu.",
    "pick.prompt": "Chi vive qui?",
    "pick.count": "{i} di {n}",
    "pick.choose": "Scegli {name}",
    "pick.hint": "Scorri la sfera · tocca per scegliere",
    "pick.chosen": "Hai scelto {name}.",
    "pick.failed": "Non salvato · tocca per riprovare",
    "ask.title": "Chiedi prima di operare.",
    "ask.sub": "Tieni premuto e parla, oppure tocca una domanda.",
    "chip.look": "Come sta andando {sym}?",
    "chip.move": "Perché {sym} si muove oggi?",
    "chip.again": "Fai un’altra domanda",
    "perm.title": "Ascolto solo mentre tieni premuto.",
    "perm.body": "iOS chiederà una volta l’accesso al microfono e al riconoscimento vocale.",
    "perm.bodyWeb": "Il browser chiederà una volta l’accesso al microfono. Il servizio vocale trascrive la tua voce.",
    "perm.go": "Continua",
    "ask.gotIt": "Capito. Tieni premuto e chiedi.",
    "hint.hold": "Tieni premuto per chiedere",
    "hint.release": "Rilascia per inviare",
    "hint.type": "Scrivi la tua domanda",
    "hint.micOff": "Microfono spento · tocca per scrivere",
    "hint.sttEmpty": "Non ho capito · tieni premuto e riprova",
    "hint.sttError": "Il microfono si è fermato · tieni premuto per riprovare",
    "type.placeholder": "Chiedi di un’azione o una cripto",
    "type.send": "Invia",
    "risk.intro": "Prima di rispondere, una cosa.",
    "risk.introOnly": "Una cosa prima di continuare.",
    "risk.hold": "Tieni premuto per accettare",
    "risk.notice": "Leggi l’avvertenza completa",
    "risk.failed": "Non registrato · tieni premuto di nuovo",
    "think.elapsed": "{s} s",
    "think.still": "Analisi in corso · fino a un minuto",
    "think.long": "Più tempo del solito · tocca per annullare",
    "think.forming": "Conclusione in preparazione",
    "hint.conviction": "Convinzione = quanto Bobby è sicuro di questa analisi",
    "hint.pull": "Scorri verso il basso per l’analisi completa",
    "pill.fullRead": "Vedi l’analisi completa",
    "save.failed": "Impossibile salvare · riprova",
    "evolution": "Livello {n} · {name}",
    "unlocked": "Sbloccato · {names}",
    "sheet.title": "Conserva le tue tesi.",
    "sheet.body": "Salva una copia delle tue tesi e dei tuoi XP per ritrovarli su un nuovo telefono.",
    "sheet.apple": "Accedi con Apple",
    "sheet.notnow": "Non ora",
    "sheet.unavailable": "L’accesso non è disponibile. La tua tesi resta su questo dispositivo.",
    "sheet.failed": "L’accesso non è stato completato. Puoi riprovare più tardi.",
    "isla.seed": "La tua isola ha ricevuto il primo seme.",
    "isla.seedSub": "Cresce quando questa analisi si conclude.",
    "isla.bloom": "La tua isola ha ottenuto il primo elemento.",
    "isla.card.title": "Isola · dimensione {size}",
    "isla.card.body": "{pieces} elementi · {seeds} in crescita",
    "home.morning": "Buongiorno.",
    "home.afternoon": "Buon pomeriggio.",
    "home.evening": "Buonasera.",
    "home.saved": "La tua tesi su {sym} è salvata.",
    "home.none": "Chiedimi di qualsiasi azione o cripto.",
    "home.hint": "Tieni premuto per chiedere · scorri la sfera",
    "gsat": "{sym} · {word}",
    "chart.now": "ORA",
    "asof": "al {time}",
    "aria.listening": "Bobby sta ascoltando",
    "aria.debate": "Tre agenti discutono",
    "aria.bobby": "Bobby",
    "aria.pill": "Chiedi a Bobby, tieni premuto per parlare",
    "aria.close": "Chiudi analisi",
    "pause": "In pausa"
  },
  de: {
    "hello": "Ich bin Bobby. Vor jedem Handel|diskutieren drei Versionen von mir darüber. Dann entscheidest du.",
    "pick.prompt": "Wer wohnt hier?",
    "pick.count": "{i} von {n}",
    "pick.choose": "{name} wählen",
    "pick.hint": "Kugel wischen · zum Wählen tippen",
    "pick.chosen": "Du hast {name} gewählt.",
    "pick.failed": "Nicht gespeichert · zum Wiederholen tippen",
    "ask.title": "Frag vor dem Handel.",
    "ask.sub": "Halte die Taste und sprich, oder tippe auf eine Frage.",
    "chip.look": "Wie steht es um {sym}?",
    "chip.move": "Warum bewegt sich {sym} heute?",
    "chip.again": "Eine andere Frage stellen",
    "perm.title": "Ich höre nur zu, solange du hältst.",
    "perm.body": "iOS fragt einmal nach Mikrofon und Spracherkennung.",
    "perm.bodyWeb": "Dein Browser fragt einmal nach dem Mikrofon. Sein Sprachdienst wandelt deine Stimme in Text um.",
    "perm.go": "Weiter",
    "ask.gotIt": "Verstanden. Halte und frage.",
    "hint.hold": "Zum Fragen halten",
    "hint.release": "Zum Senden loslassen",
    "hint.type": "Gib deine Frage ein",
    "hint.micOff": "Mikrofon aus · zum Schreiben tippen",
    "hint.sttEmpty": "Nicht verstanden · halten und erneut versuchen",
    "hint.sttError": "Mikrofon gestoppt · zum Wiederholen halten",
    "type.placeholder": "Frage zu einer Aktie oder Kryptowährung",
    "type.send": "Senden",
    "risk.intro": "Vor meiner Antwort noch eines.",
    "risk.introOnly": "Bevor es weitergeht, noch eines.",
    "risk.hold": "Zum Zustimmen halten",
    "risk.notice": "Vollständigen Hinweis lesen",
    "risk.failed": "Nicht erfasst · erneut halten",
    "think.elapsed": "{s} s",
    "think.still": "Analyse läuft · bis zu einer Minute",
    "think.long": "Dauert länger als üblich · zum Abbrechen tippen",
    "think.forming": "Fazit entsteht",
    "hint.conviction": "Überzeugung = wie sicher Bobby sich bei dieser Analyse ist",
    "hint.pull": "Für die vollständige Analyse nach unten ziehen",
    "pill.fullRead": "Vollständige Analyse ansehen",
    "save.failed": "Speichern fehlgeschlagen · erneut versuchen",
    "evolution": "Stufe {n} · {name}",
    "unlocked": "Freigeschaltet · {names}",
    "sheet.title": "Bewahre deine Thesen auf.",
    "sheet.body": "Sichere deine Thesen und XP, damit sie auf einem neuen Telefon erhalten bleiben.",
    "sheet.apple": "Mit Apple anmelden",
    "sheet.notnow": "Jetzt nicht",
    "sheet.unavailable": "Die Anmeldung ist nicht verfügbar. Deine These bleibt auf diesem Gerät.",
    "sheet.failed": "Die Anmeldung wurde nicht abgeschlossen. Versuche es später erneut.",
    "isla.seed": "Deine Insel hat ihren ersten Samen erhalten.",
    "isla.seedSub": "Er wächst, wenn diese Analyse abgeschlossen ist.",
    "isla.bloom": "Deine Insel hat ihr erstes Element erhalten.",
    "isla.card.title": "Insel · Größe {size}",
    "isla.card.body": "{pieces} Elemente · {seeds} wachsen",
    "home.morning": "Guten Morgen.",
    "home.afternoon": "Guten Tag.",
    "home.evening": "Guten Abend.",
    "home.saved": "Deine These zu {sym} wurde gespeichert.",
    "home.none": "Frag mich zu einer Aktie oder Kryptowährung.",
    "home.hint": "Zum Fragen halten · Kugel wischen",
    "gsat": "{sym} · {word}",
    "chart.now": "JETZT",
    "asof": "Stand {time}",
    "aria.listening": "Bobby hört zu",
    "aria.debate": "Drei Agenten diskutieren",
    "aria.bobby": "Bobby",
    "aria.pill": "Frag Bobby, zum Sprechen halten",
    "aria.close": "Analyse schließen",
    "pause": "Pausiert"
  }
};
var LANG = 'en', LOCALE = 'en-US';
function Ls(key, vars){
  var s = STR[LANG][key]; if (s == null) s = STR.en[key]; if (s == null) return key;
  return s.replace(/\{(\w+)\}/g, function(_, k){ return vars && vars[k] != null ? String(vars[k]) : ''; });
}
/* same rule as tests/read-model.test.mjs: no advice or outcome words in any table this page ships */
var LINT_RE = /\b(buy|sell|compra|vende|profit|ganancias?|win|wins|winning|returns|guarantee\w*|garantiz\w*)\b/i;
function lintStrings(){
  var bad = [];
  ['en', 'es', 'fr', 'pt', 'it', 'de'].forEach(function(l){ Object.keys(STR[l]).forEach(function(k){ if (LINT_RE.test(STR[l][k])) bad.push(l + '.' + k + ': ' + STR[l][k]); }); });
  ['es', 'fr', 'pt', 'it', 'de'].forEach(function(l){
    if (Object.keys(STR.en).length !== Object.keys(STR[l]).length) bad.push(l + ' key count differs');
    Object.keys(STR.en).forEach(function(k){ if (STR[l][k] == null) bad.push(l + ' missing ' + k); });
  });
  return bad;
}
