#!/usr/bin/env -S npx tsx
// ============================================================
// DRAFT schema generator — turns the source's PostgREST OpenAPI into
// CREATE TABLE statements for the approved tables: column types, defaults,
// NOT NULL, primary keys and foreign keys. It is a fallback for when
// `pg_dump --schema-only` is not possible (we hold no database password for
// the legacy project). What it CANNOT see: indexes, CHECK/UNIQUE
// constraints, triggers, functions and RLS policies — those come from the
// repo migrations and must be reviewed by hand. Output is marked DRAFT.
//   SOURCE_SUPABASE_URL=… SOURCE_SUPABASE_SERVICE_KEY=… npx tsx scripts/migration/schema-from-openapi.mts --out <file.sql>
// ============================================================
import { writeFileSync } from 'node:fs';
import { APPROVED_TABLES } from './tables.js';
import { headers, project } from './lib.js';

const args = process.argv.slice(2);
const out = args[args.indexOf('--out') + 1] || 'supabase/bobby-protocol/supabase/migrations/DRAFT_bobby_schema_from_legacy.sql';
const p = project('source');

interface Col { type?: string; format?: string; default?: string; description?: string; items?: { type?: string; format?: string } }
function pgType(c: Col): string {
  const f = (c.format || '').trim();
  if (f.endsWith('[]')) return f;
  if (f === 'character varying') return 'text';
  if (f) return f.replace(/^character varying\(\d+\)$/, 'text');
  return c.type === 'integer' ? 'integer' : c.type === 'number' ? 'numeric' : c.type === 'boolean' ? 'boolean' : c.type === 'array' ? 'jsonb' : 'text';
}

(async () => {
  const r = await fetch(`${p.url}/rest/v1/`, { headers: headers(p) });
  if (!r.ok) throw new Error(`openapi HTTP ${r.status}`);
  const spec = (await r.json()) as { definitions: Record<string, { properties: Record<string, Col>; required?: string[] }> };
  const lines: string[] = [
    '-- ============================================================',
    `-- DRAFT — generated by scripts/migration/schema-from-openapi.mts from ${p.ref} on ${new Date().toISOString()}.`,
    '-- Column types, defaults, NOT NULL, PK and FK only. Indexes, CHECK/UNIQUE',
    '-- constraints, triggers, functions and RLS are NOT here: take them from',
    '-- supabase/migrations/*.sql (repo history) and review before applying.',
    '-- Replace with `pg_dump --schema-only` output as soon as the legacy DB',
    '-- password is available. Do not apply this file blindly.',
    '-- ============================================================',
    '',
  ];
  for (const t of APPROVED_TABLES) {
    const d = spec.definitions[t.name];
    if (!d) { lines.push(`-- ${t.name}: not exposed on the source`, ''); continue; }
    const req = new Set(d.required || []);
    const cols = Object.entries(d.properties).map(([name, c]) => {
      const isIdentity = t.identity === name;
      const type = isIdentity ? 'bigint generated by default as identity' : pgType(c);
      const notNull = req.has(name) && !isIdentity ? ' not null' : '';
      const def = c.default && !isIdentity ? ` default ${c.default}` : '';
      return `  ${name} ${type}${notNull}${def}`;
    });
    cols.push(`  primary key (${t.pk.join(', ')})`);
    for (const fk of t.fks) {
      const [col, ref] = fk.split('->'); const [pt, pc] = ref.split('.');
      cols.push(`  foreign key (${col}) references public.${pt} (${pc})`);
    }
    lines.push(`create table if not exists public.${t.name} (`, cols.join(',\n'), ');', `alter table public.${t.name} enable row level security;`, '');
  }
  writeFileSync(out, lines.join('\n'));
  console.log(`draft written → ${out} (${APPROVED_TABLES.length} tables)`);
})().catch((e) => { console.error(e); process.exit(1); });
