
/* ============================================================
   Strings (en / es), selected by session.language. Read-derived
   copy (verdicts, satellites, thesis rows, failures, XP) comes
   from NucleoReadModel; everything the onboarding itself says
   lives here. No advice or outcome language (lint: nucleo.lint()).
   '|' in a spoken line is a caption page break (never spoken).
   ============================================================ */
var STR = {
  en: {
    "risk.notNow": "Not now",
    "risk.kept": "Nothing was sent. Your question is still here.",
    "risk.later": "Bobby answers after you accept the notice.",
    "risk.holdHint": "Press and hold to agree",
    "ex.1": "What is investing?",
    "ex.2": "What is a stock?",
    "ex.3": "What is inflation?",
    "ex.4": "What is an index fund?",
    "ex.5": "What does risk mean?",
    "ex.6": "Why do prices move?",
    "cap.listening": "I’m listening · tap to send",
    "cap.cancel": "Tap to cancel",
    "cap.costCancel": "{cost} · tap to cancel",
    "cap.stillWorking": "Still working · tap to cancel",
    "cap.stopVoice": "Tap to stop the voice",
    "cap.tapToTalk": "Tap to talk",
    "cap.holdToTalk": "Hold to talk",
    "cap.empty": "I didn’t catch that · tap and try again",
    "cap.minute": "That was one minute. Your question is still here.",
    "cap.stopped": "I stopped listening. Your question is still here.",
    "cap.voiceUnavailable": "Voice unavailable · here is the text",
    "aria.talk": "Talk",
    "aria.type": "Type",
    "aria.sendSpoken": "Send what I said",
    "aria.discardSpoken": "Discard what I said",
    "aria.cancelQuestion": "Cancel the question",
    "aria.closeAnswer": "Close the answer",
    "aria.preparing": "Bobby is preparing your answer",
    "aria.ask": "Ask: {question}",
    "aria.answer": "Bobby’s answer",

    "hello": "I’m Bobby.|I help you understand before you decide.",
    'pick.prompt': 'Who lives in here?',
    'pick.count': '{i} of {n}',
    "ask.title": "What do you want to understand?",
    "ask.sub": "About money and investing. No question is too basic.",
    'chip.look': 'How is {sym} looking?',
    'chip.move': 'Why is {sym} moving today?',
    'chip.again': 'Try another question',
    "perm.title": "I listen only after you tap, until you send.",
    'perm.body': 'iOS will ask for the microphone and speech recognition once.',
    'perm.go': 'Continue',
    'ask.gotIt': 'Got it. Hold and ask.',
    'hint.hold': 'Hold to ask',
    'hint.release': 'Release to send',
    'hint.type': 'Type your question',
    'hint.micOff': 'Voice input isn’t available right now · tap to type',
    'hint.sttEmpty': 'I didn’t catch that · Hold and try again',
    'hint.sttError': 'The mic stopped · Hold to try again',
    "type.placeholder": "Ask anything…",
    'type.send': 'Send',
    'risk.intro': 'Before I answer, one thing.',
    'risk.introOnly': 'One thing before we go on.',
    'risk.hold': 'Hold to agree',
    'risk.activate': 'I agree to the risk notice and AI processing',
    'risk.notice': 'Read the full notice',
    'risk.profile': 'Profile',
    'risk.failed': 'That didn’t go through · Hold again',
    'think.elapsed': '{s} s',
    'think.still': 'Still weighing · deep reads take up to a minute',
    'think.long': 'Taking longer than usual · tap to cancel',
    'think.forming': 'Verdict forming',
    'hint.conviction': 'Conviction = how sure Bobby is in this read',
    'hint.pull': 'Pull down for the full read',
    'pill.fullRead': 'See the full read',
    'save.failed': 'Couldn’t save · Try again',
    'evolution': 'Level {n} · {name}',
    'unlocked': 'Unlocked · {names}',
    'sheet.title': 'Keep your theses.',
    'sheet.body': 'Back up your theses and XP so they survive a new phone.',
    'sheet.apple': 'Sign in with Apple',
    'sheet.notnow': 'Not now',
    'sheet.unavailable': 'Sign-in isn’t available right now. Your thesis stays on this device.',
    'sheet.failed': 'Sign-in didn’t finish. You can try again later.',
    'isla.seed': 'Your island got its first seed.',
    'isla.seedSub': 'It grows when this read closes.',
    'isla.bloom': 'Your island grew its first piece.',
    'isla.card.title': 'Island · size {size}',
    'isla.card.body': '{pieces} pieces · {seeds} growing',
    'home.morning': 'Good morning.', 'home.afternoon': 'Good afternoon.', 'home.evening': 'Good evening.',
    'home.saved': 'Your {sym} thesis is saved.',
    'home.none': 'Ask me about any stock or crypto.',
    'home.hint': 'Hold to ask · Swipe the sphere',
    'gsat': '{sym} · {word}',
    'chart.now': 'NOW',
    'asof': 'as of {time}',
    'aria.listening': 'Bobby is listening',
    'aria.debate': 'Three agents debating',
    'aria.bobby': 'Bobby',
    'aria.pill': 'Ask Bobby, hold to talk',
    'aria.close': 'Close read',
    'pause': 'Paused'
  },
  es: {
    "risk.notNow": "Ahora no",
    "risk.kept": "No se envió nada. Tu pregunta sigue aquí.",
    "risk.later": "Bobby responde cuando aceptes el aviso.",
    "risk.holdHint": "Mantén presionado para aceptar",
    "ex.1": "¿Qué es invertir?",
    "ex.2": "¿Qué es una acción?",
    "ex.3": "¿Qué es la inflación?",
    "ex.4": "¿Qué es un fondo indexado?",
    "ex.5": "¿Qué significa riesgo?",
    "ex.6": "¿Por qué se mueven los precios?",
    "cap.listening": "Te escucho · toca para enviar",
    "cap.cancel": "Toca para cancelar",
    "cap.costCancel": "{cost} · toca para cancelar",
    "cap.stillWorking": "Sigo en ello · toca para cancelar",
    "cap.stopVoice": "Toca para detener la voz",
    "cap.tapToTalk": "Toca para hablar",
    "cap.holdToTalk": "Mantén para hablar",
    "cap.empty": "No te escuché · toca y vuelve a intentar",
    "cap.minute": "Ya pasó un minuto. Tu pregunta sigue aquí.",
    "cap.stopped": "Dejé de escuchar. Tu pregunta sigue aquí.",
    "cap.voiceUnavailable": "Voz no disponible · aquí está el texto",
    "aria.talk": "Hablar",
    "aria.type": "Escribir",
    "aria.sendSpoken": "Enviar lo que dije",
    "aria.discardSpoken": "Descartar lo que dije",
    "aria.cancelQuestion": "Cancelar la pregunta",
    "aria.closeAnswer": "Cerrar la respuesta",
    "aria.preparing": "Bobby está preparando tu respuesta",
    "aria.ask": "Preguntar: {question}",
    "aria.answer": "Respuesta de Bobby",

    "hello": "Soy Bobby.|Te ayudo a entender antes de decidir.",
    'pick.prompt': '¿Quién vive aquí?',
    'pick.count': '{i} de {n}',
    "ask.title": "¿Qué quieres entender?",
    "ask.sub": "Sobre dinero e inversiones. Ninguna pregunta es demasiado básica.",
    'chip.look': '¿Cómo se ve {sym}?',
    'chip.move': '¿Por qué se mueve {sym} hoy?',
    'chip.again': 'Prueba otra pregunta',
    "perm.title": "Solo escucho desde que tocas hasta que envías.",
    'perm.body': 'iOS te pedirá una vez el micrófono y el reconocimiento de voz.',
    'perm.go': 'Continuar',
    'ask.gotIt': 'Listo. Mantén y pregunta.',
    'hint.hold': 'Mantén para preguntar',
    'hint.release': 'Suelta para enviar',
    'hint.type': 'Escribe tu pregunta',
    'hint.micOff': 'La entrada de voz no está disponible ahora · toca para escribir',
    'hint.sttEmpty': 'No te escuché · Mantén e intenta de nuevo',
    'hint.sttError': 'El micrófono se detuvo · Mantén para intentar',
    "type.placeholder": "Pregunta lo que quieras…",
    'type.send': 'Enviar',
    'risk.intro': 'Antes de responder, una cosa.',
    'risk.introOnly': 'Una cosa antes de seguir.',
    'risk.hold': 'Mantén para aceptar',
    'risk.activate': 'Acepto el aviso de riesgo y el procesamiento con IA',
    'risk.notice': 'Leer el aviso completo',
    'risk.profile': 'Perfil',
    'risk.failed': 'No se registró · Mantén otra vez',
    'think.elapsed': '{s} s',
    'think.still': 'Sigue deliberando · una lectura a fondo tarda hasta un minuto',
    'think.long': 'Tarda más de lo normal · toca para cancelar',
    'think.forming': 'Veredicto en camino',
    'hint.conviction': 'Convicción = qué tan seguro está Bobby de esta lectura',
    'hint.pull': 'Desliza hacia abajo para la lectura completa',
    'pill.fullRead': 'Ver la lectura',
    'save.failed': 'No se pudo guardar · Intenta de nuevo',
    'evolution': 'Nivel {n} · {name}',
    'unlocked': 'Desbloqueado · {names}',
    'sheet.title': 'Conserva tus tesis.',
    'sheet.body': 'Respalda tus tesis y tu XP para no perderlos al cambiar de teléfono.',
    'sheet.apple': 'Iniciar sesión con Apple',
    'sheet.notnow': 'Ahora no',
    'sheet.unavailable': 'Ahora no se puede iniciar sesión. Tu tesis se queda en este dispositivo.',
    'sheet.failed': 'No se completó el inicio de sesión. Puedes intentarlo más tarde.',
    'isla.seed': 'Tu isla recibió su primera semilla.',
    'isla.seedSub': 'Crece cuando esta lectura se cierre.',
    'isla.bloom': 'Tu isla creció su primera pieza.',
    'isla.card.title': 'Isla · tamaño {size}',
    'isla.card.body': '{pieces} piezas · {seeds} creciendo',
    'home.morning': 'Buenos días.', 'home.afternoon': 'Buenas tardes.', 'home.evening': 'Buenas noches.',
    'home.saved': 'Tu tesis de {sym} está guardada.',
    'home.none': 'Pregúntame por cualquier acción o cripto.',
    'home.hint': 'Mantén para preguntar · Desliza la esfera',
    'gsat': '{sym} · {word}',
    'chart.now': 'AHORA',
    'asof': 'a las {time}',
    'aria.listening': 'Bobby está escuchando',
    'aria.debate': 'Tres agentes debatiendo',
    'aria.bobby': 'Bobby',
    'aria.pill': 'Pregunta a Bobby, mantén para hablar',
    'aria.close': 'Cerrar lectura',
    'pause': 'Pausa'
  }
,
  fr: {
    "risk.notNow": "Pas maintenant",
    "risk.kept": "Rien n’a été envoyé. Ta question est toujours là.",
    "risk.later": "Bobby répond dès que tu acceptes l’avis.",
    "risk.holdHint": "Maintiens appuyé pour accepter",
    "ex.1": "C’est quoi, investir ?",
    "ex.2": "C’est quoi, une action ?",
    "ex.3": "C’est quoi, l’inflation ?",
    "ex.4": "C’est quoi, un fonds indiciel ?",
    "ex.5": "Que veut dire « risque » ?",
    "ex.6": "Pourquoi les prix bougent ?",
    "cap.listening": "Je t’écoute · touche pour envoyer",
    "cap.cancel": "Touche pour annuler",
    "cap.costCancel": "{cost} · touche pour annuler",
    "cap.stillWorking": "J’y travaille encore · touche pour annuler",
    "cap.stopVoice": "Touche pour arrêter la voix",
    "cap.tapToTalk": "Touche pour parler",
    "cap.holdToTalk": "Maintiens pour parler",
    "cap.empty": "Je n’ai pas compris · touche et réessaie",
    "cap.minute": "Une minute est passée. Ta question est toujours là.",
    "cap.stopped": "J’ai arrêté d’écouter. Ta question est toujours là.",
    "cap.voiceUnavailable": "Voix indisponible · voici le texte",
    "aria.talk": "Parler",
    "aria.type": "Écrire",
    "aria.sendSpoken": "Envoyer ce que j’ai dit",
    "aria.discardSpoken": "Effacer ce que j’ai dit",
    "aria.cancelQuestion": "Annuler la question",
    "aria.closeAnswer": "Fermer la réponse",
    "aria.preparing": "Bobby prépare ta réponse",
    "aria.ask": "Demander : {question}",
    "aria.answer": "Réponse de Bobby",

    "hello": "Je suis Bobby.|Je t’aide à comprendre avant de décider.",
    "pick.prompt": "Qui habite ici ?",
    "pick.count": "{i} sur {n}",
    "ask.title": "Que veux-tu comprendre ?",
    "ask.sub": "Sur l’argent et l’investissement. Aucune question n’est trop simple.",
    "chip.look": "Que penser de {sym} ?",
    "chip.move": "Pourquoi {sym} bouge aujourd’hui ?",
    "chip.again": "Poser une autre question",
    "perm.title": "J’écoute seulement de ton appui jusqu’à l’envoi.",
    "perm.body": "iOS demandera une fois l’accès au micro et à la reconnaissance vocale.",
    "perm.go": "Continuer",
    "ask.gotIt": "Compris. Maintiens et demande.",
    "hint.hold": "Maintiens pour demander",
    "hint.release": "Relâche pour envoyer",
    "hint.type": "Écris ta question",
    "hint.micOff": "Saisie vocale indisponible pour l’instant · touche pour écrire",
    "hint.sttEmpty": "Je n’ai pas compris · maintiens et réessaie",
    "hint.sttError": "Le micro s’est arrêté · maintiens pour réessayer",
    "type.placeholder": "Demande ce que tu veux…",
    "type.send": "Envoyer",
    "risk.intro": "Avant de répondre, une précision.",
    "risk.introOnly": "Une précision avant de continuer.",
    "risk.hold": "Maintiens pour accepter",
    "risk.activate": "J’accepte l’avertissement sur les risques et le traitement par IA",
    "risk.notice": "Lire l’avertissement complet",
    "risk.profile": "Ton profil",
    "risk.failed": "Non enregistré · maintiens à nouveau",
    "think.elapsed": "{s} s",
    "think.still": "L’analyse continue · jusqu’à une minute",
    "think.long": "Plus long que prévu · touche pour annuler",
    "think.forming": "Conclusion en préparation",
    "hint.conviction": "Conviction = degré de confiance de Bobby dans cette analyse",
    "hint.pull": "Glisse vers le bas pour l’analyse complète",
    "pill.fullRead": "Voir l’analyse complète",
    "save.failed": "Enregistrement impossible · réessaie",
    "evolution": "Niveau {n} · {name}",
    "unlocked": "Débloqué · {names}",
    "sheet.title": "Conserve tes thèses.",
    "sheet.body": "Sauvegarde tes thèses et ton XP pour les retrouver sur un nouveau téléphone.",
    "sheet.apple": "Se connecter avec Apple",
    "sheet.notnow": "Plus tard",
    "sheet.unavailable": "La connexion est indisponible. Ta thèse reste sur cet appareil.",
    "sheet.failed": "La connexion n’a pas abouti. Tu pourras réessayer plus tard.",
    "isla.seed": "Ton île a reçu sa première graine.",
    "isla.seedSub": "Elle grandit à la clôture de cette analyse.",
    "isla.bloom": "Ton île a gagné son premier élément.",
    "isla.card.title": "Île · taille {size}",
    "isla.card.body": "{pieces} éléments · {seeds} en croissance",
    "home.morning": "Bonjour.",
    "home.afternoon": "Bonjour.",
    "home.evening": "Bonsoir.",
    "home.saved": "Ta thèse sur {sym} est enregistrée.",
    "home.none": "Interroge-moi sur une action ou une crypto.",
    "home.hint": "Maintiens pour demander · balaie la sphère",
    "gsat": "{sym} · {word}",
    "chart.now": "ACTUEL",
    "asof": "au {time}",
    "aria.listening": "Bobby écoute",
    "aria.debate": "Trois agents débattent",
    "aria.bobby": "Bobby",
    "aria.pill": "Demande à Bobby, maintiens pour parler",
    "aria.close": "Fermer l’analyse",
    "pause": "En pause"
  },
  pt: {
    "risk.notNow": "Agora não",
    "risk.kept": "Nada foi enviado. A tua pergunta continua aqui.",
    "risk.later": "O Bobby responde quando aceitares o aviso.",
    "risk.holdHint": "Mantém premido para aceitar",
    "ex.1": "O que é investir?",
    "ex.2": "O que é uma ação?",
    "ex.3": "O que é a inflação?",
    "ex.4": "O que é um fundo indexado?",
    "ex.5": "O que significa risco?",
    "ex.6": "Porque é que os preços se movem?",
    "cap.listening": "Estou a ouvir · toca para enviar",
    "cap.cancel": "Toca para cancelar",
    "cap.costCancel": "{cost} · toca para cancelar",
    "cap.stillWorking": "Ainda a preparar · toca para cancelar",
    "cap.stopVoice": "Toca para parar a voz",
    "cap.tapToTalk": "Toca para falar",
    "cap.holdToTalk": "Mantém para falar",
    "cap.empty": "Não percebi · toca e tenta novamente",
    "cap.minute": "Passou um minuto. A tua pergunta continua aqui.",
    "cap.stopped": "Deixei de ouvir. A tua pergunta continua aqui.",
    "cap.voiceUnavailable": "Voz indisponível · aqui está o texto",
    "aria.talk": "Falar",
    "aria.type": "Escrever",
    "aria.sendSpoken": "Enviar o que eu disse",
    "aria.discardSpoken": "Descartar o que eu disse",
    "aria.cancelQuestion": "Cancelar a pergunta",
    "aria.closeAnswer": "Fechar a resposta",
    "aria.preparing": "O Bobby está a preparar a tua resposta",
    "aria.ask": "Perguntar: {question}",
    "aria.answer": "Resposta do Bobby",

    "hello": "Sou o Bobby.|Ajudo-te a entender antes de decidires.",
    "pick.prompt": "Quem vive aqui?",
    "pick.count": "{i} de {n}",
    "ask.title": "O que queres entender?",
    "ask.sub": "Sobre dinheiro e investimentos. Nenhuma pergunta é demasiado básica.",
    "chip.look": "Como está {sym}?",
    "chip.move": "Porque está {sym} a mover-se hoje?",
    "chip.again": "Fazer outra pergunta",
    "perm.title": "Só ouço desde que tocas até enviares.",
    "perm.body": "O iOS pedirá uma vez acesso ao microfone e ao reconhecimento de voz.",
    "perm.go": "Continuar",
    "ask.gotIt": "Entendido. Mantém e pergunta.",
    "hint.hold": "Mantém para perguntar",
    "hint.release": "Solta para enviar",
    "hint.type": "Escreve a tua pergunta",
    "hint.micOff": "Entrada de voz indisponível de momento · toca para escrever",
    "hint.sttEmpty": "Não percebi · mantém e tenta novamente",
    "hint.sttError": "O microfone parou · mantém para tentar novamente",
    "type.placeholder": "Pergunta o que quiseres…",
    "type.send": "Enviar",
    "risk.intro": "Antes de responder, uma coisa.",
    "risk.introOnly": "Uma coisa antes de continuar.",
    "risk.hold": "Mantém para aceitar",
    "risk.activate": "Aceito o aviso de risco e o processamento por IA",
    "risk.notice": "Ler o aviso completo",
    "risk.profile": "O teu perfil",
    "risk.failed": "Não foi registado · mantém novamente",
    "think.elapsed": "{s} s",
    "think.still": "A análise continua · pode demorar até um minuto",
    "think.long": "Mais demorado que o habitual · toca para cancelar",
    "think.forming": "Conclusão em preparação",
    "hint.conviction": "Convicção = grau de confiança do Bobby nesta análise",
    "hint.pull": "Desliza para baixo para a análise completa",
    "pill.fullRead": "Ver a análise completa",
    "save.failed": "Não foi possível guardar · tenta novamente",
    "evolution": "Nível {n} · {name}",
    "unlocked": "Desbloqueado · {names}",
    "sheet.title": "Conserva as tuas teses.",
    "sheet.body": "Guarda uma cópia das teses e do XP para os manter ao mudar de telefone.",
    "sheet.apple": "Iniciar sessão com Apple",
    "sheet.notnow": "Agora não",
    "sheet.unavailable": "O início de sessão não está disponível. A tua tese fica neste dispositivo.",
    "sheet.failed": "O início de sessão não foi concluído. Podes tentar mais tarde.",
    "isla.seed": "A tua ilha recebeu a primeira semente.",
    "isla.seedSub": "Cresce quando esta análise terminar.",
    "isla.bloom": "A tua ilha ganhou a primeira peça.",
    "isla.card.title": "Ilha · tamanho {size}",
    "isla.card.body": "{pieces} peças · {seeds} a crescer",
    "home.morning": "Bom dia.",
    "home.afternoon": "Boa tarde.",
    "home.evening": "Boa noite.",
    "home.saved": "A tua tese de {sym} foi guardada.",
    "home.none": "Pergunta sobre qualquer ação ou cripto.",
    "home.hint": "Mantém para perguntar · desliza a esfera",
    "gsat": "{sym} · {word}",
    "chart.now": "AGORA",
    "asof": "às {time}",
    "aria.listening": "O Bobby está a ouvir",
    "aria.debate": "Três agentes a debater",
    "aria.bobby": "Bobby",
    "aria.pill": "Pergunta ao Bobby, mantém para falar",
    "aria.close": "Fechar análise",
    "pause": "Em pausa"
  }
,
  it: {
    "risk.notNow": "Non ora",
    "risk.kept": "Non è stato inviato nulla. La tua domanda è ancora qui.",
    "risk.later": "Bobby risponde quando accetti l’avviso.",
    "risk.holdHint": "Continua a tenere premuto per accettare",
    "ex.1": "Che cos’è investire?",
    "ex.2": "Che cos’è un’azione?",
    "ex.3": "Che cos’è l’inflazione?",
    "ex.4": "Che cos’è un fondo indicizzato?",
    "ex.5": "Cosa significa rischio?",
    "ex.6": "Perché i prezzi si muovono?",
    "cap.listening": "Ti ascolto · tocca per inviare",
    "cap.cancel": "Tocca per annullare",
    "cap.costCancel": "{cost} · tocca per annullare",
    "cap.stillWorking": "Ci sto ancora lavorando · tocca per annullare",
    "cap.stopVoice": "Tocca per fermare la voce",
    "cap.tapToTalk": "Tocca per parlare",
    "cap.holdToTalk": "Tieni premuto per parlare",
    "cap.empty": "Non ho capito · tocca e riprova",
    "cap.minute": "È passato un minuto. La tua domanda è ancora qui.",
    "cap.stopped": "Ho smesso di ascoltare. La tua domanda è ancora qui.",
    "cap.voiceUnavailable": "Voce non disponibile · ecco il testo",
    "aria.talk": "Parla",
    "aria.type": "Scrivi",
    "aria.sendSpoken": "Invia quello che ho detto",
    "aria.discardSpoken": "Scarta quello che ho detto",
    "aria.cancelQuestion": "Annulla la domanda",
    "aria.closeAnswer": "Chiudi la risposta",
    "aria.preparing": "Bobby sta preparando la tua risposta",
    "aria.ask": "Chiedi: {question}",
    "aria.answer": "Risposta di Bobby",

    "hello": "Sono Bobby.|Ti aiuto a capire prima di decidere.",
    "pick.prompt": "Chi vive qui?",
    "pick.count": "{i} di {n}",
    "ask.title": "Cosa vuoi capire?",
    "ask.sub": "Su soldi e investimenti. Nessuna domanda è troppo semplice.",
    "chip.look": "Come sta andando {sym}?",
    "chip.move": "Perché {sym} si muove oggi?",
    "chip.again": "Fai un’altra domanda",
    "perm.title": "Ascolto solo da quando tocchi a quando invii.",
    "perm.body": "iOS chiederà una volta l’accesso al microfono e al riconoscimento vocale.",
    "perm.go": "Continua",
    "ask.gotIt": "Capito. Tieni premuto e chiedi.",
    "hint.hold": "Tieni premuto per chiedere",
    "hint.release": "Rilascia per inviare",
    "hint.type": "Scrivi la tua domanda",
    "hint.micOff": "Input vocale non disponibile al momento · tocca per scrivere",
    "hint.sttEmpty": "Non ho capito · tieni premuto e riprova",
    "hint.sttError": "Il microfono si è fermato · tieni premuto per riprovare",
    "type.placeholder": "Chiedi quello che vuoi…",
    "type.send": "Invia",
    "risk.intro": "Prima di rispondere, una cosa.",
    "risk.introOnly": "Una cosa prima di continuare.",
    "risk.hold": "Tieni premuto per accettare",
    "risk.activate": "Accetto l’avviso sui rischi e l’elaborazione tramite IA",
    "risk.notice": "Leggi l’avvertenza completa",
    "risk.profile": "Il tuo profilo",
    "risk.failed": "Non registrato · tieni premuto di nuovo",
    "think.elapsed": "{s} s",
    "think.still": "Analisi in corso · fino a un minuto",
    "think.long": "Più tempo del solito · tocca per annullare",
    "think.forming": "Conclusione in preparazione",
    "hint.conviction": "Convinzione = quanto Bobby è sicuro di questa analisi",
    "hint.pull": "Scorri verso il basso per l’analisi completa",
    "pill.fullRead": "Vedi l’analisi completa",
    "save.failed": "Impossibile salvare · riprova",
    "evolution": "Livello {n} · {name}",
    "unlocked": "Sbloccato · {names}",
    "sheet.title": "Conserva le tue tesi.",
    "sheet.body": "Salva una copia delle tue tesi e dei tuoi XP per ritrovarli su un nuovo telefono.",
    "sheet.apple": "Accedi con Apple",
    "sheet.notnow": "Non ora",
    "sheet.unavailable": "L’accesso non è disponibile. La tua tesi resta su questo dispositivo.",
    "sheet.failed": "L’accesso non è stato completato. Puoi riprovare più tardi.",
    "isla.seed": "La tua isola ha ricevuto il primo seme.",
    "isla.seedSub": "Cresce quando questa analisi si conclude.",
    "isla.bloom": "La tua isola ha ottenuto il primo elemento.",
    "isla.card.title": "Isola · dimensione {size}",
    "isla.card.body": "{pieces} elementi · {seeds} in crescita",
    "home.morning": "Buongiorno.",
    "home.afternoon": "Buon pomeriggio.",
    "home.evening": "Buonasera.",
    "home.saved": "La tua tesi su {sym} è salvata.",
    "home.none": "Chiedimi di qualsiasi azione o cripto.",
    "home.hint": "Tieni premuto per chiedere · scorri la sfera",
    "gsat": "{sym} · {word}",
    "chart.now": "ORA",
    "asof": "al {time}",
    "aria.listening": "Bobby sta ascoltando",
    "aria.debate": "Tre agenti discutono",
    "aria.bobby": "Bobby",
    "aria.pill": "Chiedi a Bobby, tieni premuto per parlare",
    "aria.close": "Chiudi analisi",
    "pause": "In pausa"
  },
  de: {
    "risk.notNow": "Jetzt nicht",
    "risk.kept": "Es wurde nichts gesendet. Deine Frage ist noch da.",
    "risk.later": "Bobby antwortet, sobald du den Hinweis akzeptierst.",
    "risk.holdHint": "Gedrückt halten zum Zustimmen",
    "ex.1": "Was heißt investieren?",
    "ex.2": "Was ist eine Aktie?",
    "ex.3": "Was ist Inflation?",
    "ex.4": "Was ist ein Indexfonds?",
    "ex.5": "Was bedeutet Risiko?",
    "ex.6": "Warum bewegen sich Preise?",
    "cap.listening": "Ich höre zu · zum Senden tippen",
    "cap.cancel": "Zum Abbrechen tippen",
    "cap.costCancel": "{cost} · zum Abbrechen tippen",
    "cap.stillWorking": "Ich bin noch dran · zum Abbrechen tippen",
    "cap.stopVoice": "Zum Stoppen tippen",
    "cap.tapToTalk": "Zum Sprechen tippen",
    "cap.holdToTalk": "Zum Sprechen halten",
    "cap.empty": "Nicht verstanden · tippen und erneut versuchen",
    "cap.minute": "Das war eine Minute. Deine Frage ist noch da.",
    "cap.stopped": "Ich höre nicht mehr zu. Deine Frage ist noch da.",
    "cap.voiceUnavailable": "Stimme nicht verfügbar · hier ist der Text",
    "aria.talk": "Sprechen",
    "aria.type": "Schreiben",
    "aria.sendSpoken": "Senden, was ich gesagt habe",
    "aria.discardSpoken": "Verwerfen, was ich gesagt habe",
    "aria.cancelQuestion": "Frage abbrechen",
    "aria.closeAnswer": "Antwort schließen",
    "aria.preparing": "Bobby bereitet deine Antwort vor",
    "aria.ask": "Fragen: {question}",
    "aria.answer": "Bobbys Antwort",

    "hello": "Ich bin Bobby.|Ich helfe dir zu verstehen, bevor du entscheidest.",
    "pick.prompt": "Wer wohnt hier?",
    "pick.count": "{i} von {n}",
    "ask.title": "Was möchtest du verstehen?",
    "ask.sub": "Über Geld und Geldanlage. Keine Frage ist zu einfach.",
    "chip.look": "Wie steht es um {sym}?",
    "chip.move": "Warum bewegt sich {sym} heute?",
    "chip.again": "Eine andere Frage stellen",
    "perm.title": "Ich höre nur zu, vom Antippen bis zum Senden.",
    "perm.body": "iOS fragt einmal nach Mikrofon und Spracherkennung.",
    "perm.go": "Weiter",
    "ask.gotIt": "Verstanden. Halte und frage.",
    "hint.hold": "Zum Fragen halten",
    "hint.release": "Zum Senden loslassen",
    "hint.type": "Gib deine Frage ein",
    "hint.micOff": "Spracheingabe gerade nicht verfügbar · zum Schreiben tippen",
    "hint.sttEmpty": "Nicht verstanden · halten und erneut versuchen",
    "hint.sttError": "Mikrofon gestoppt · zum Wiederholen halten",
    "type.placeholder": "Frag, was du möchtest…",
    "type.send": "Senden",
    "risk.intro": "Vor meiner Antwort noch eines.",
    "risk.introOnly": "Bevor es weitergeht, noch eines.",
    "risk.hold": "Zum Zustimmen halten",
    "risk.activate": "Ich stimme dem Risikohinweis und der KI-Verarbeitung zu",
    "risk.notice": "Vollständigen Hinweis lesen",
    "risk.profile": "Dein Profil",
    "risk.failed": "Nicht erfasst · erneut halten",
    "think.elapsed": "{s} s",
    "think.still": "Analyse läuft · bis zu einer Minute",
    "think.long": "Dauert länger als üblich · zum Abbrechen tippen",
    "think.forming": "Fazit entsteht",
    "hint.conviction": "Überzeugung = wie sicher Bobby sich bei dieser Analyse ist",
    "hint.pull": "Für die vollständige Analyse nach unten ziehen",
    "pill.fullRead": "Vollständige Analyse ansehen",
    "save.failed": "Speichern fehlgeschlagen · erneut versuchen",
    "evolution": "Stufe {n} · {name}",
    "unlocked": "Freigeschaltet · {names}",
    "sheet.title": "Bewahre deine Thesen auf.",
    "sheet.body": "Sichere deine Thesen und XP, damit sie auf einem neuen Telefon erhalten bleiben.",
    "sheet.apple": "Mit Apple anmelden",
    "sheet.notnow": "Jetzt nicht",
    "sheet.unavailable": "Die Anmeldung ist nicht verfügbar. Deine These bleibt auf diesem Gerät.",
    "sheet.failed": "Die Anmeldung wurde nicht abgeschlossen. Versuche es später erneut.",
    "isla.seed": "Deine Insel hat ihren ersten Samen erhalten.",
    "isla.seedSub": "Er wächst, wenn diese Analyse abgeschlossen ist.",
    "isla.bloom": "Deine Insel hat ihr erstes Element erhalten.",
    "isla.card.title": "Insel · Größe {size}",
    "isla.card.body": "{pieces} Elemente · {seeds} wachsen",
    "home.morning": "Guten Morgen.",
    "home.afternoon": "Guten Tag.",
    "home.evening": "Guten Abend.",
    "home.saved": "Deine These zu {sym} wurde gespeichert.",
    "home.none": "Frag mich zu einer Aktie oder Kryptowährung.",
    "home.hint": "Zum Fragen halten · Kugel wischen",
    "gsat": "{sym} · {word}",
    "chart.now": "JETZT",
    "asof": "Stand {time}",
    "aria.listening": "Bobby hört zu",
    "aria.debate": "Drei Agenten diskutieren",
    "aria.bobby": "Bobby",
    "aria.pill": "Frag Bobby, zum Sprechen halten",
    "aria.close": "Analyse schließen",
    "pause": "Pausiert"
  }
};
var LANG = 'en', LOCALE = 'en-US';
function Ls(key, vars){
  var s = STR[LANG][key]; if (s == null) s = STR.en[key]; if (s == null) return key;
  return s.replace(/\{(\w+)\}/g, function(_, k){ return vars && vars[k] != null ? String(vars[k]) : ''; });
}
/* same rule as tests/read-model.test.mjs: no advice or outcome words in any table this page ships */
var LINT_RE = /\b(buy|sell|compra|vende|profit|ganancias?|win|wins|winning|returns|guarantee\w*|garantiz\w*)\b/i;
function lintStrings(){
  var bad = [];
  ['en', 'es', 'fr', 'pt', 'it', 'de'].forEach(function(l){ Object.keys(STR[l]).forEach(function(k){ if (LINT_RE.test(STR[l][k])) bad.push(l + '.' + k + ': ' + STR[l][k]); }); });
  ['es', 'fr', 'pt', 'it', 'de'].forEach(function(l){
    if (Object.keys(STR.en).length !== Object.keys(STR[l]).length) bad.push(l + ' key count differs');
    Object.keys(STR.en).forEach(function(k){ if (STR[l][k] == null) bad.push(l + ' missing ' + k); });
  });
  return bad;
}
