/* =====================================================================
   8. UI strings (engine chrome). Read-derived copy lives in NucleoReadModel.
   tests/read-model.test.mjs extracts this table between the markers and
   lints it (no advice / outcome language, en and es keys identical).
   ===================================================================== */
var STR = /*STRINGS-BEGIN*/{
  en: {
    "read.skipVoice": "Skip voice",
    "read.result": "Read analysis",
    "read.save": "Save reading",
    "read.saving": "Saving…",
    "read.saved": "Reading saved",
    "read.home": "Back to Bobby",
    "read.summary": "Read summary",
    "read.saveHelp": "Save this reading to pick it up later.",
    "read.returnTomorrow": "Tomorrow, open Bobby to revisit {name}.",
    "read.returnLater": "Open Bobby to revisit {name}.",
    "read.savedLocal": "Saved on this phone.",

    'greet.morning': 'Good morning.', 'greet.afternoon': 'Good afternoon.', 'greet.evening': 'Good evening.',
    'greet.sub.day': 'What are you weighing today?', 'greet.sub.night': 'What are you weighing tonight?',
    'greet.saved': '{symbol} is saved.',
    'hint.idleType': 'Tap to type', 'hint.hold': 'Hold to ask',
    'hint.release': 'Release to send', 'hint.debating': 'Three agents debating', 'hint.debatingS': 'Three agents debating · {s} s',
    'hint.still': 'Still weighing · deep reads take up to a minute', 'hint.long': 'Taking longer than usual · tap to cancel',
    'hint.pull': 'Pull down for the full read ⌄', 'hint.swipe': 'Swipe the sphere',
    'hint.empty': 'I didn’t catch that · hold and try again', 'hint.micStopped': 'The mic stopped · hold to try again',
    'hint.micOff': 'Voice input isn’t available right now · tap to type',
    'perm.title': 'I only listen while you hold.', 'perm.body': 'iOS will ask for the microphone and speech recognition once.', 'perm.cta': 'Continue',
    'type.placeholder': 'Ask about a stock or a crypto…', 'type.send': 'Send question',
    'think.forming': 'Verdict forming',
    'chips.eyebrow': 'You might want to ask',
    'face.desk': 'Desk', 'face.isla': 'Island', 'face.squad': 'Squad', "face.theses": "Saved reads",
    'face.isla.status': '{pieces} pieces · {seeds} seeds growing', 'face.isla.chip': 'Visit your island',
    'face.squad.status': '{name} · Level {level} · {streak}-day streak', 'face.squad.statusNew': '{name} · Level {level}', 'face.squad.chip': 'Change companion',
    'face.theses.one': '1 saved', 'face.theses.many': '{n} saved', "face.theses.chip": "Open latest reading",
    'save.evolution': 'Level {n} · {name}', 'save.unlock': 'Unlocked · {name}',
    'voice.failed': 'Bobby’s voice is unavailable. Your analysis is ready to read.',
    'save.stale': 'Account changed · this read was not saved', 'save.failed': 'Could not save this read',
    'isla.title': 'Your island', 'isla.pieces': 'Pieces', 'isla.seeds': 'Seeds growing', 'isla.ready': 'Ready to review', 'isla.cta': 'Visit your island',
    'meta.asOf': 'as of {when}', 'chart.x': '{tf} · {provider} · {inst} · as of {when}',
    'aria.waking': 'Bobby is waking up', 'aria.idle': 'Bobby is idle', 'aria.listening': 'Bobby is listening', 'aria.sending': 'Sending your question',
    'aria.thinking': 'Three agents debating', 'aria.speaking': 'Bobby is speaking', 'aria.cards': 'Full read: debate and thesis cards',
    'aria.faces': 'Sphere faces', 'aria.noVerdict': 'No verdict was issued',
    'aria.pill': 'Ask Bobby, hold to talk', 'aria.pillType': 'Type a question', 'aria.pillCancel': 'Cancel the read', 'aria.pillStop': 'Stop the voice',
    'aria.close': 'Close read', 'aria.companion': 'Your companion, {name}', 'aria.faceDots': 'Sphere faces: {list}', 'aria.wm': 'Bobby',
    'aria.account': '{name}. Account and progress', 'aria.accountPlain': 'Account and progress'
  },
  es: {
    "read.skipVoice": "Saltar voz",
    "read.result": "Ver análisis",
    "read.save": "Guardar lectura",
    "read.saving": "Guardando…",
    "read.saved": "Lectura guardada",
    "read.home": "Volver a Bobby",
    "read.summary": "Ver resumen",
    "read.saveHelp": "Guarda esta lectura para retomarla después.",
    "read.returnTomorrow": "Mañana, abre Bobby para retomar {name}.",
    "read.returnLater": "Abre Bobby para retomar {name}.",
    "read.savedLocal": "Guardada en este teléfono.",

    'greet.morning': 'Buenos días.', 'greet.afternoon': 'Buenas tardes.', 'greet.evening': 'Buenas noches.',
    'greet.sub.day': '¿Qué estás evaluando hoy?', 'greet.sub.night': '¿Qué estás evaluando esta noche?',
    'greet.saved': '{symbol} quedó guardada.',
    'hint.idleType': 'Toca para escribir', 'hint.hold': 'Mantén para preguntar',
    'hint.release': 'Suelta para enviar', 'hint.debating': 'Tres agentes debatiendo', 'hint.debatingS': 'Tres agentes debatiendo · {s} s',
    'hint.still': 'Sigue pensando · puede tardar hasta un minuto', 'hint.long': 'Tarda más de lo normal · toca para cancelar',
    'hint.pull': 'Desliza hacia abajo para verlo completo ⌄', 'hint.swipe': 'Desliza la esfera',
    'hint.empty': 'No te escuché · mantén y vuelve a intentar', 'hint.micStopped': 'El micrófono se detuvo · mantén para reintentar',
    'hint.micOff': 'La entrada de voz no está disponible ahora · toca para escribir',
    'perm.title': 'Solo escucho mientras mantienes.', 'perm.body': 'iOS pedirá el micrófono y el reconocimiento de voz una vez.', 'perm.cta': 'Continuar',
    'type.placeholder': 'Pregunta por una acción o cripto…', 'type.send': 'Enviar pregunta',
    'think.forming': 'Veredicto en formación',
    'chips.eyebrow': 'Quizá quieras preguntar',
    'face.desk': 'Escritorio', 'face.isla': 'Isla', 'face.squad': 'Escuadrón', "face.theses": "Tus lecturas",
    'face.isla.status': '{pieces} piezas · {seeds} semillas creciendo', 'face.isla.chip': 'Visitar Isla',
    'face.squad.status': '{name} · Nivel {level} · racha de {streak} días', 'face.squad.statusNew': '{name} · Nivel {level}', 'face.squad.chip': 'Cambiar compañero',
    'face.theses.one': '1 guardada', 'face.theses.many': '{n} guardadas', "face.theses.chip": "Abrir última lectura",
    'save.evolution': 'Nivel {n} · {name}', 'save.unlock': 'Desbloqueado · {name}',
    'voice.failed': 'La voz de Bobby no está disponible. Tu análisis está listo para leer.',
    'save.stale': 'Cambió la cuenta · esta lectura no se guardó', 'save.failed': 'No se pudo guardar esta lectura',
    'isla.title': 'Tu isla', 'isla.pieces': 'Piezas', 'isla.seeds': 'Semillas creciendo', 'isla.ready': 'Listas para revisar', 'isla.cta': 'Visitar Isla',
    'meta.asOf': 'a las {when}', 'chart.x': '{tf} · {provider} · {inst} · a las {when}',
    'aria.waking': 'Bobby está despertando', 'aria.idle': 'Bobby está en reposo', 'aria.listening': 'Bobby está escuchando', 'aria.sending': 'Enviando tu pregunta',
    'aria.thinking': 'Tres agentes debatiendo', 'aria.speaking': 'Bobby está hablando', 'aria.cards': 'Lectura completa: debate y tesis',
    'aria.faces': 'Caras de la esfera', 'aria.noVerdict': 'No se emitió veredicto',
    'aria.pill': 'Pregúntale a Bobby, mantén para hablar', 'aria.pillType': 'Escribe una pregunta', 'aria.pillCancel': 'Cancelar la lectura', 'aria.pillStop': 'Detener la voz',
    'aria.close': 'Cerrar lectura', 'aria.companion': 'Tu compañero, {name}', 'aria.faceDots': 'Caras de la esfera: {list}', 'aria.wm': 'Bobby',
    'aria.account': '{name}. Cuenta y progreso', 'aria.accountPlain': 'Cuenta y progreso'
  }
,
  fr: {
    "read.skipVoice": "Passer la voix",
    "read.result": "Lire l’analyse",
    "read.save": "Enregistrer l’analyse",
    "read.saving": "Enregistrement…",
    "read.saved": "Analyse enregistrée",
    "read.home": "Revenir à Bobby",
    "read.summary": "Voir le résumé",
    "read.saveHelp": "Enregistre cette analyse pour la reprendre plus tard.",
    "read.returnTomorrow": "Demain, ouvre Bobby pour reprendre {name}.",
    "read.returnLater": "Ouvre Bobby pour reprendre {name}.",
    "read.savedLocal": "Enregistrée sur ce téléphone.",

    "greet.morning": "Bonjour.",
    "greet.afternoon": "Bonjour.",
    "greet.evening": "Bonsoir.",
    "greet.sub.day": "Que veux-tu évaluer aujourd’hui ?",
    "greet.sub.night": "Que veux-tu évaluer ce soir ?",
    "greet.saved": "{symbol} est enregistré.",
    "hint.idleType": "Touche pour écrire",
    "hint.hold": "Maintiens pour demander",
    "hint.release": "Relâche pour envoyer",
    "hint.debating": "Trois agents débattent",
    "hint.debatingS": "Trois agents débattent · {s} s",
    "hint.still": "L’analyse continue · jusqu’à une minute",
    "hint.long": "Plus long que prévu · touche pour annuler",
    "hint.pull": "Glisse vers le bas pour l’analyse complète ⌄",
    "hint.swipe": "Balaie la sphère",
    "hint.empty": "Je n’ai pas compris · maintiens et réessaie",
    "hint.micStopped": "Le micro s’est arrêté · maintiens pour réessayer",
    "hint.micOff": "Saisie vocale indisponible pour l’instant · touche pour écrire",
    "perm.title": "J’écoute seulement pendant l’appui.",
    "perm.body": "iOS demandera une fois l’accès au micro et à la reconnaissance vocale.",
    "perm.cta": "Continuer",
    "type.placeholder": "Une question sur une action ou une crypto…",
    "type.send": "Envoyer la question",
    "think.forming": "Conclusion en préparation",
    "chips.eyebrow": "Tu pourrais demander",
    "face.desk": "Bureau",
    "face.isla": "Île",
    "face.squad": "Équipe",
    "face.theses": "Tes analyses",
    "face.isla.status": "{pieces} éléments · {seeds} graines en croissance",
    "face.isla.chip": "Visiter ton île",
    "face.squad.status": "{name} · Niveau {level} · série de {streak} jours",
    "face.squad.statusNew": "{name} · Niveau {level}",
    "face.squad.chip": "Changer de compagnon",
    "face.theses.one": "1 enregistrée",
    "face.theses.many": "{n} enregistrées",
    "face.theses.chip": "Ouvrir la dernière analyse",
    "save.evolution": "Niveau {n} · {name}",
    "save.unlock": "Débloqué · {name}",
    "voice.failed": "La voix de Bobby est indisponible. Ton analyse est prête à lire.",
    "save.stale": "Compte modifié · cette analyse n’a pas été enregistrée",
    "save.failed": "Impossible d’enregistrer cette analyse",
    "isla.title": "Ton île",
    "isla.pieces": "Éléments",
    "isla.seeds": "Graines en croissance",
    "isla.ready": "À réexaminer",
    "isla.cta": "Visiter ton île",
    "meta.asOf": "au {when}",
    "chart.x": "{tf} · {provider} · {inst} · au {when}",
    "aria.waking": "Bobby se réveille",
    "aria.idle": "Bobby est au repos",
    "aria.listening": "Bobby écoute",
    "aria.sending": "Envoi de ta question",
    "aria.thinking": "Trois agents débattent",
    "aria.speaking": "Bobby parle",
    "aria.cards": "Analyse complète : débat et thèses",
    "aria.faces": "Faces de la sphère",
    "aria.noVerdict": "Aucune conclusion n’a été rendue",
    "aria.pill": "Demande à Bobby, maintiens pour parler",
    "aria.pillType": "Écrire une question",
    "aria.pillCancel": "Annuler l’analyse",
    "aria.pillStop": "Arrêter la voix",
    "aria.close": "Fermer l’analyse",
    "aria.companion": "Ton compagnon, {name}",
    "aria.faceDots": "Faces de la sphère : {list}",
    "aria.wm": "Bobby",
    "aria.account": "{name}. Compte et progression",
    "aria.accountPlain": "Compte et progression"
  },
  pt: {
    "read.skipVoice": "Pular voz",
    "read.result": "Ver análise",
    "read.save": "Guardar análise",
    "read.saving": "Guardando…",
    "read.saved": "Análise guardada",
    "read.home": "Voltar ao Bobby",
    "read.summary": "Ver resumo",
    "read.saveHelp": "Guarda esta análise para retomá-la depois.",
    "read.returnTomorrow": "Amanhã, abre o Bobby para retomar {name}.",
    "read.returnLater": "Abre o Bobby para retomar {name}.",
    "read.savedLocal": "Guardada neste telefone.",

    "greet.morning": "Bom dia.",
    "greet.afternoon": "Boa tarde.",
    "greet.evening": "Boa noite.",
    "greet.sub.day": "O que queres avaliar hoje?",
    "greet.sub.night": "O que queres avaliar esta noite?",
    "greet.saved": "{symbol} foi guardado.",
    "hint.idleType": "Toca para escrever",
    "hint.hold": "Mantém para perguntar",
    "hint.release": "Solta para enviar",
    "hint.debating": "Três agentes a debater",
    "hint.debatingS": "Três agentes a debater · {s} s",
    "hint.still": "A análise continua · pode demorar até um minuto",
    "hint.long": "Mais demorado que o habitual · toca para cancelar",
    "hint.pull": "Desliza para baixo para a análise completa ⌄",
    "hint.swipe": "Desliza a esfera",
    "hint.empty": "Não percebi · mantém e tenta novamente",
    "hint.micStopped": "O microfone parou · mantém para tentar novamente",
    "hint.micOff": "Entrada de voz indisponível de momento · toca para escrever",
    "perm.title": "Só ouço enquanto manténs o botão.",
    "perm.body": "O iOS pedirá uma vez acesso ao microfone e ao reconhecimento de voz.",
    "perm.cta": "Continuar",
    "type.placeholder": "Pergunta sobre uma ação ou cripto…",
    "type.send": "Enviar pergunta",
    "think.forming": "Conclusão em preparação",
    "chips.eyebrow": "Talvez queiras perguntar",
    "face.desk": "Mesa",
    "face.isla": "Ilha",
    "face.squad": "Equipa",
    "face.theses": "Tuas análises",
    "face.isla.status": "{pieces} peças · {seeds} sementes a crescer",
    "face.isla.chip": "Visitar a tua ilha",
    "face.squad.status": "{name} · Nível {level} · sequência de {streak} dias",
    "face.squad.statusNew": "{name} · Nível {level}",
    "face.squad.chip": "Mudar de companheiro",
    "face.theses.one": "1 guardada",
    "face.theses.many": "{n} guardadas",
    "face.theses.chip": "Abrir última análise",
    "save.evolution": "Nível {n} · {name}",
    "save.unlock": "Desbloqueado · {name}",
    "voice.failed": "A voz do Bobby não está disponível. A tua análise está pronta para ler.",
    "save.stale": "A conta mudou · esta análise não foi guardada",
    "save.failed": "Não foi possível guardar esta análise",
    "isla.title": "A tua ilha",
    "isla.pieces": "Peças",
    "isla.seeds": "Sementes a crescer",
    "isla.ready": "Prontas para rever",
    "isla.cta": "Visitar a tua ilha",
    "meta.asOf": "às {when}",
    "chart.x": "{tf} · {provider} · {inst} · às {when}",
    "aria.waking": "O Bobby está a acordar",
    "aria.idle": "O Bobby está em repouso",
    "aria.listening": "O Bobby está a ouvir",
    "aria.sending": "A enviar a tua pergunta",
    "aria.thinking": "Três agentes a debater",
    "aria.speaking": "O Bobby está a falar",
    "aria.cards": "Análise completa: debate e teses",
    "aria.faces": "Faces da esfera",
    "aria.noVerdict": "Não foi emitida uma conclusão",
    "aria.pill": "Pergunta ao Bobby, mantém para falar",
    "aria.pillType": "Escrever uma pergunta",
    "aria.pillCancel": "Cancelar a análise",
    "aria.pillStop": "Parar a voz",
    "aria.close": "Fechar análise",
    "aria.companion": "O teu companheiro, {name}",
    "aria.faceDots": "Faces da esfera: {list}",
    "aria.wm": "Bobby",
    "aria.account": "{name}. Conta e progresso",
    "aria.accountPlain": "Conta e progresso"
  }
,
  it: {
    "read.skipVoice": "Salta la voce",
    "read.result": "Leggi l’analisi",
    "read.save": "Salva l’analisi",
    "read.saving": "Salvataggio…",
    "read.saved": "Analisi salvata",
    "read.home": "Torna a Bobby",
    "read.summary": "Vedi il riepilogo",
    "read.saveHelp": "Salva questa analisi per riprenderla più tardi.",
    "read.returnTomorrow": "Domani, apri Bobby per riprendere {name}.",
    "read.returnLater": "Apri Bobby per riprendere {name}.",
    "read.savedLocal": "Salvata su questo telefono.",

    "greet.morning": "Buongiorno.",
    "greet.afternoon": "Buon pomeriggio.",
    "greet.evening": "Buonasera.",
    "greet.sub.day": "Cosa vuoi valutare oggi?",
    "greet.sub.night": "Cosa vuoi valutare stasera?",
    "greet.saved": "{symbol} è stato salvato.",
    "hint.idleType": "Tocca per scrivere",
    "hint.hold": "Tieni premuto per chiedere",
    "hint.release": "Rilascia per inviare",
    "hint.debating": "Tre agenti discutono",
    "hint.debatingS": "Tre agenti discutono · {s} s",
    "hint.still": "Analisi in corso · fino a un minuto",
    "hint.long": "Più tempo del solito · tocca per annullare",
    "hint.pull": "Scorri verso il basso per l’analisi completa ⌄",
    "hint.swipe": "Scorri la sfera",
    "hint.empty": "Non ho capito · tieni premuto e riprova",
    "hint.micStopped": "Il microfono si è fermato · tieni premuto per riprovare",
    "hint.micOff": "Input vocale non disponibile al momento · tocca per scrivere",
    "perm.title": "Ascolto solo mentre tieni premuto.",
    "perm.body": "iOS chiederà una volta l’accesso al microfono e al riconoscimento vocale.",
    "perm.cta": "Continua",
    "type.placeholder": "Chiedi di un’azione o una cripto…",
    "type.send": "Invia domanda",
    "think.forming": "Conclusione in preparazione",
    "chips.eyebrow": "Potresti chiedere",
    "face.desk": "Scrivania",
    "face.isla": "Isola",
    "face.squad": "Squadra",
    "face.theses": "Le tue analisi",
    "face.isla.status": "{pieces} elementi · {seeds} semi in crescita",
    "face.isla.chip": "Visita la tua isola",
    "face.squad.status": "{name} · Livello {level} · serie di {streak} giorni",
    "face.squad.statusNew": "{name} · Livello {level}",
    "face.squad.chip": "Cambia compagno",
    "face.theses.one": "1 salvata",
    "face.theses.many": "{n} salvate",
    "face.theses.chip": "Apri l’ultima analisi",
    "save.evolution": "Livello {n} · {name}",
    "save.unlock": "Sbloccato · {name}",
    "voice.failed": "La voce di Bobby non è disponibile. La tua analisi è pronta da leggere.",
    "save.stale": "Account cambiato · questa analisi non è stata salvata",
    "save.failed": "Impossibile salvare questa analisi",
    "isla.title": "La tua isola",
    "isla.pieces": "Elementi",
    "isla.seeds": "Semi in crescita",
    "isla.ready": "Da riesaminare",
    "isla.cta": "Visita la tua isola",
    "meta.asOf": "al {when}",
    "chart.x": "{tf} · {provider} · {inst} · al {when}",
    "aria.waking": "Bobby si sta svegliando",
    "aria.idle": "Bobby è a riposo",
    "aria.listening": "Bobby sta ascoltando",
    "aria.sending": "Invio della domanda",
    "aria.thinking": "Tre agenti discutono",
    "aria.speaking": "Bobby sta parlando",
    "aria.cards": "Analisi completa: dibattito e tesi",
    "aria.faces": "Facce della sfera",
    "aria.noVerdict": "Nessuna conclusione è stata formulata",
    "aria.pill": "Chiedi a Bobby, tieni premuto per parlare",
    "aria.pillType": "Scrivi una domanda",
    "aria.pillCancel": "Annulla l’analisi",
    "aria.pillStop": "Ferma la voce",
    "aria.close": "Chiudi analisi",
    "aria.companion": "Il tuo compagno, {name}",
    "aria.faceDots": "Facce della sfera: {list}",
    "aria.wm": "Bobby",
    "aria.account": "{name}. Account e progressi",
    "aria.accountPlain": "Account e progressi"
  },
  de: {
    "read.skipVoice": "Stimme überspringen",
    "read.result": "Analyse lesen",
    "read.save": "Analyse speichern",
    "read.saving": "Wird gespeichert…",
    "read.saved": "Analyse gespeichert",
    "read.home": "Zurück zu Bobby",
    "read.summary": "Zusammenfassung",
    "read.saveHelp": "Speichere diese Analyse, um sie später fortzusetzen.",
    "read.returnTomorrow": "Öffne morgen Bobby, um {name} wieder aufzugreifen.",
    "read.returnLater": "Öffne Bobby, um {name} wieder aufzugreifen.",
    "read.savedLocal": "Auf diesem Telefon gespeichert.",

    "greet.morning": "Guten Morgen.",
    "greet.afternoon": "Guten Tag.",
    "greet.evening": "Guten Abend.",
    "greet.sub.day": "Was möchtest du heute bewerten?",
    "greet.sub.night": "Was möchtest du heute Abend bewerten?",
    "greet.saved": "{symbol} wurde gespeichert.",
    "hint.idleType": "Zum Schreiben tippen",
    "hint.hold": "Zum Fragen halten",
    "hint.release": "Zum Senden loslassen",
    "hint.debating": "Drei Agenten diskutieren",
    "hint.debatingS": "Drei Agenten diskutieren · {s} s",
    "hint.still": "Analyse läuft · bis zu einer Minute",
    "hint.long": "Dauert länger als üblich · zum Abbrechen tippen",
    "hint.pull": "Für die vollständige Analyse nach unten ziehen ⌄",
    "hint.swipe": "Über die Kugel wischen",
    "hint.empty": "Nicht verstanden · halten und erneut versuchen",
    "hint.micStopped": "Mikrofon gestoppt · zum Wiederholen halten",
    "hint.micOff": "Spracheingabe gerade nicht verfügbar · zum Schreiben tippen",
    "perm.title": "Ich höre nur zu, solange du hältst.",
    "perm.body": "iOS fragt einmal nach Mikrofon und Spracherkennung.",
    "perm.cta": "Weiter",
    "type.placeholder": "Frage zu einer Aktie oder Kryptowährung…",
    "type.send": "Frage senden",
    "think.forming": "Fazit entsteht",
    "chips.eyebrow": "Du könntest fragen",
    "face.desk": "Schreibtisch",
    "face.isla": "Insel",
    "face.squad": "Team",
    "face.theses": "Deine Analysen",
    "face.isla.status": "{pieces} Elemente · {seeds} wachsende Samen",
    "face.isla.chip": "Deine Insel besuchen",
    "face.squad.status": "{name} · Stufe {level} · {streak} Tage in Folge",
    "face.squad.statusNew": "{name} · Stufe {level}",
    "face.squad.chip": "Begleiter wechseln",
    "face.theses.one": "1 gespeichert",
    "face.theses.many": "{n} gespeichert",
    "face.theses.chip": "Letzte Analyse öffnen",
    "save.evolution": "Stufe {n} · {name}",
    "save.unlock": "Freigeschaltet · {name}",
    "voice.failed": "Bobbys Stimme ist nicht verfügbar. Deine Analyse ist bereit zum Lesen.",
    "save.stale": "Konto geändert · Analyse wurde nicht gespeichert",
    "save.failed": "Analyse konnte nicht gespeichert werden",
    "isla.title": "Deine Insel",
    "isla.pieces": "Elemente",
    "isla.seeds": "Wachsende Samen",
    "isla.ready": "Zur Überprüfung bereit",
    "isla.cta": "Deine Insel besuchen",
    "meta.asOf": "Stand {when}",
    "chart.x": "{tf} · {provider} · {inst} · Stand {when}",
    "aria.waking": "Bobby wacht auf",
    "aria.idle": "Bobby ruht",
    "aria.listening": "Bobby hört zu",
    "aria.sending": "Deine Frage wird gesendet",
    "aria.thinking": "Drei Agenten diskutieren",
    "aria.speaking": "Bobby spricht",
    "aria.cards": "Vollständige Analyse: Debatte und Thesen",
    "aria.faces": "Flächen der Kugel",
    "aria.noVerdict": "Es wurde kein Fazit erstellt",
    "aria.pill": "Frag Bobby, zum Sprechen halten",
    "aria.pillType": "Frage eingeben",
    "aria.pillCancel": "Analyse abbrechen",
    "aria.pillStop": "Stimme stoppen",
    "aria.close": "Analyse schließen",
    "aria.companion": "Dein Begleiter, {name}",
    "aria.faceDots": "Flächen der Kugel: {list}",
    "aria.wm": "Bobby",
    "aria.account": "{name}. Konto und Fortschritt",
    "aria.accountPlain": "Konto und Fortschritt"
  }
}/*STRINGS-END*/;
var LANG = 'en', LOCALE = 'en-US';
function tt(key, vars){
  var tbl = STR[LANG] || STR.en, s = tbl[key];
  if (s == null) s = STR.en[key];
  if (s == null) return key;
  return s.replace(/\{(\w+)\}/g, function(_, k){ return vars && vars[k] != null ? String(vars[k]) : ''; });
}
/* dates: local time, compact; the same day as `ref` shows the time only */
function whenLabel(iso, ref){
  var d = new Date(iso); if (isNaN(d.getTime())) return '';
  var r = new Date(fin(ref) ? ref : d.getTime()), loc = LOCALE;
  try {
    if (d.toDateString() === r.toDateString()) return d.toLocaleTimeString(loc, { hour: 'numeric', minute: '2-digit' });
    return d.toLocaleDateString(loc, { month: 'short', day: 'numeric' }) + ' ' + d.toLocaleTimeString(loc, { hour: 'numeric', minute: '2-digit' });
  } catch (e) { return d.toISOString().slice(0, 16).replace('T', ' '); }
}
