import Foundation

extension NativeTranslations18 {
    /// Memory: consent, receipts, the memory screen.
    /// The receipt rows (the last block) appear on the glass: each must stay within
    /// `NucleoNudge.textLimit` with a symbol of up to eight characters (Memory18NudgeTests measures them).
    static let memory: [String: [String: String]] = {
        var result: [String: [String: String]] = [:]
        // The consent sheet
        result["Should I remember what you ask about?"] = ["fr": "Veux-tu que je retienne ce que tu me demandes ?", "pt": "Queres que me lembre do que me perguntas?", "it": "Vuoi che ricordi quello che mi chiedi?", "de": "Soll ich mir merken, wonach du fragst?"]
        result["What I keep"] = ["fr": "Ce que je garde", "pt": "O que guardo", "it": "Cosa conservo", "de": "Was ich behalte"]
        result["The asset, the date, the time frame you mention and its price that day."] = ["fr": "L'actif, la date, l'horizon que tu mentionnes et son prix ce jour-là.", "pt": "O ativo, a data, o prazo que mencionas e o preço desse dia.", "it": "L'asset, la data, l'orizzonte che indichi e il suo prezzo di quel giorno.", "de": "Den Wert, das Datum, den Zeitraum, den du nennst, und seinen Kurs an diesem Tag."]
        result["What I do not keep"] = ["fr": "Ce que je ne garde pas", "pt": "O que não guardo", "it": "Cosa non conservo", "de": "Was ich nicht behalte"]
        result["Never your full question, never your name, nothing about your money."] = ["fr": "Jamais ta question complète, jamais ton nom, rien sur ton argent.", "pt": "Nunca a tua pergunta completa, nunca o teu nome, nada sobre o teu dinheiro.", "it": "Mai la tua domanda completa, mai il tuo nome, niente sui tuoi soldi.", "de": "Nie deine vollständige Frage, nie deinen Namen, nichts über dein Geld."]
        result["Where and how long"] = ["fr": "Où et combien de temps", "pt": "Onde e durante quanto tempo", "it": "Dove e per quanto tempo", "de": "Wo und wie lange"]
        result["On Bobby's servers, linked to your account, for {0} days after you last ask about it."] = ["fr": "Sur les serveurs de Bobby, lié à ton compte, pendant {0} jours après ta dernière question sur cet actif.", "pt": "Nos servidores do Bobby, associado à tua conta, durante {0} dias após a tua última pergunta sobre esse ativo.", "it": "Sui server di Bobby, collegato al tuo account, per {0} giorni dopo la tua ultima domanda su quell'asset.", "de": "Auf Bobbys Servern, mit deinem Konto verknüpft, {0} Tage lang nach deiner letzten Frage zu diesem Wert."]
        result["Who receives it"] = ["fr": "Qui le reçoit", "pt": "Quem o recebe", "it": "Chi lo riceve", "de": "Wer es erhält"]
        result["A short summary (for example: third time this week, up 4% since) reaches the AI provider that writes Bobby's answer, so the answer can pick up where you left off."] = ["fr": "Un bref résumé (par exemple : troisième fois cette semaine, +4 % depuis) parvient au fournisseur d'IA qui rédige la réponse de Bobby, pour qu'elle reprenne là où tu t'es arrêté.", "pt": "Um resumo curto (por exemplo: terceira vez esta semana, subiu 4% desde então) chega ao fornecedor de IA que escreve a resposta do Bobby, para que ela continue de onde ficaste.", "it": "Un breve riepilogo (per esempio: terza volta questa settimana, +4% da allora) arriva al fornitore di IA che scrive la risposta di Bobby, così la risposta riprende da dove eri rimasto.", "de": "Eine kurze Zusammenfassung (zum Beispiel: drittes Mal diese Woche, seitdem +4 %) geht an den KI-Anbieter, der Bobbys Antwort schreibt, damit sie dort anknüpft, wo du aufgehört hast."]
        result["Your control"] = ["fr": "Ton contrôle", "pt": "O teu controlo", "it": "Il tuo controllo", "de": "Deine Kontrolle"]
        result["See it, correct it, pause it or delete it any time in Memory."] = ["fr": "Consulte-le, corrige-le, mets-le en pause ou supprime-le à tout moment dans Mémoire.", "pt": "Vê, corrige, pausa ou elimina tudo isto quando quiseres em Memória.", "it": "Guardalo, correggilo, mettilo in pausa o eliminalo quando vuoi in Memoria.", "de": "Unter Gedächtnis kannst du es jederzeit ansehen, korrigieren, pausieren oder löschen."]
        result["Not now"] = ["fr": "Pas maintenant", "pt": "Agora não", "it": "Non ora", "de": "Nicht jetzt"]
        result["Remember"] = ["fr": "Retenir", "pt": "Lembrar", "it": "Ricorda", "de": "Merken"]
        result["Done. From your next question on, I will remember."] = ["fr": "C'est fait. Dès ta prochaine question, je m'en souviendrai.", "pt": "Feito. A partir da tua próxima pergunta, vou lembrar-me.", "it": "Fatto. Dalla tua prossima domanda, me ne ricorderò.", "de": "Erledigt. Ab deiner nächsten Frage merke ich es mir."]
        result["I could not turn memory on. Try again."] = ["fr": "Je n'ai pas pu activer la mémoire. Réessaie.", "pt": "Não consegui ativar a memória. Tenta novamente.", "it": "Non sono riuscito ad attivare la memoria. Riprova.", "de": "Ich konnte das Gedächtnis nicht einschalten. Versuch es noch einmal."]
        // The memory screen
        result["Off on this iPhone: what you ask here is not saved."] = ["fr": "Désactivée sur cet iPhone : ce que tu demandes ici n'est pas enregistré.", "pt": "Desativada neste iPhone: o que perguntas aqui não é guardado.", "it": "Disattivata su questo iPhone: ciò che chiedi qui non viene salvato.", "de": "Auf diesem iPhone aus: Was du hier fragst, wird nicht gespeichert."]
        result["Turn on"] = ["fr": "Activer", "pt": "Ativar", "it": "Attiva", "de": "Einschalten"]
        result["Opens the full explanation before anything is turned on."] = ["fr": "Ouvre l'explication complète avant toute activation.", "pt": "Abre a explicação completa antes de ativar seja o que for.", "it": "Apre la spiegazione completa prima di attivare qualsiasi cosa.", "de": "Öffnet die vollständige Erklärung, bevor etwas eingeschaltet wird."]
        result["On this iPhone only"] = ["fr": "Sur cet iPhone uniquement", "pt": "Apenas neste iPhone", "it": "Solo su questo iPhone", "de": "Nur auf diesem iPhone"]
        result["These never leave this iPhone. Forget and Delete everything clear them here too."] = ["fr": "Ces éléments ne quittent jamais cet iPhone. Oublier et Tout supprimer les effacent ici aussi.", "pt": "Isto nunca sai deste iPhone. Esquecer e Eliminar tudo também o apagam aqui.", "it": "Non lasciano mai questo iPhone. Dimentica ed Elimina tutto li cancellano anche qui.", "de": "Das verlässt dieses iPhone nie. Vergessen und Alles löschen entfernen es auch hier."]
        result["Recent assets shown as shortcuts"] = ["fr": "Actifs récents affichés comme raccourcis", "pt": "Ativos recentes mostrados como atalhos", "it": "Asset recenti mostrati come scorciatoie", "de": "Zuletzt gefragte Werte als Schnellzugriffe"]
        result["No shortcuts"] = ["fr": "Aucun raccourci", "pt": "Sem atalhos", "it": "Nessuna scorciatoia", "de": "Keine Schnellzugriffe"]
        result["Clear"] = ["fr": "Effacer", "pt": "Limpar", "it": "Cancella", "de": "Leeren"]
        result["Clear the shortcuts on this iPhone"] = ["fr": "Effacer les raccourcis de cet iPhone", "pt": "Limpar os atalhos deste iPhone", "it": "Cancella le scorciatoie su questo iPhone", "de": "Schnellzugriffe auf diesem iPhone leeren"]
        result["Theses you wrote"] = ["fr": "Thèses que tu as écrites", "pt": "Teses que escreveste", "it": "Tesi che hai scritto", "de": "Thesen, die du geschrieben hast"]
        result["No theses"] = ["fr": "Aucune thèse", "pt": "Sem teses", "it": "Nessuna tesi", "de": "Keine Thesen"]
        result["This deletes what Bobby's servers remember about your account, the shortcuts on this iPhone and the theses you wrote here. It cannot be undone."] = ["fr": "Cela supprime ce que les serveurs de Bobby retiennent sur ton compte, les raccourcis de cet iPhone et les thèses que tu as écrites ici. C'est irréversible.", "pt": "Isto elimina o que os servidores do Bobby recordam sobre a tua conta, os atalhos deste iPhone e as teses que escreveste aqui. Não pode ser anulado.", "it": "Questo elimina ciò che i server di Bobby ricordano del tuo account, le scorciatoie su questo iPhone e le tesi che hai scritto qui. Non si può annullare.", "de": "Das löscht, was Bobbys Server über dein Konto gespeichert haben, die Schnellzugriffe auf diesem iPhone und die Thesen, die du hier geschrieben hast. Das lässt sich nicht rückgängig machen."]
        result["Deleted: what Bobby's servers remembered, the shortcuts on this iPhone and the theses you wrote here."] = ["fr": "Supprimé : ce que les serveurs de Bobby retenaient, les raccourcis de cet iPhone et les thèses que tu as écrites ici.", "pt": "Eliminado: o que os servidores do Bobby recordavam, os atalhos deste iPhone e as teses que escreveste aqui.", "it": "Eliminato: ciò che i server di Bobby ricordavano, le scorciatoie su questo iPhone e le tesi che hai scritto qui.", "de": "Gelöscht: was Bobbys Server gespeichert hatten, die Schnellzugriffe auf diesem iPhone und die Thesen, die du hier geschrieben hast."]
        result["Deleted on this iPhone. Bobby's servers did not confirm, so what they remember is still there. Try again."] = ["fr": "Supprimé sur cet iPhone. Les serveurs de Bobby n'ont pas confirmé : ce qu'ils retiennent est toujours là. Réessaie.", "pt": "Eliminado neste iPhone. Os servidores do Bobby não confirmaram, por isso o que recordam continua lá. Tenta novamente.", "it": "Eliminato su questo iPhone. I server di Bobby non hanno confermato, quindi ciò che ricordano è ancora lì. Riprova.", "de": "Auf diesem iPhone gelöscht. Bobbys Server haben nicht bestätigt, daher ist dort noch vorhanden, was sie gespeichert haben. Versuch es noch einmal."]
        result["Forgotten on this iPhone. Bobby's servers did not confirm, so they still remember {0}. Try again."] = ["fr": "Oublié sur cet iPhone. Les serveurs de Bobby n'ont pas confirmé : ils retiennent encore {0}. Réessaie.", "pt": "Esquecido neste iPhone. Os servidores do Bobby não confirmaram, por isso ainda recordam {0}. Tenta novamente.", "it": "Dimenticato su questo iPhone. I server di Bobby non hanno confermato, quindi ricordano ancora {0}. Riprova.", "de": "Auf diesem iPhone vergessen. Bobbys Server haben nicht bestätigt, daher merken sie sich {0} noch. Versuch es noch einmal."]
        result["Memory is still on: your next question starts it again. You can pause it above."] = ["fr": "La mémoire reste activée : ta prochaine question la relance. Tu peux la mettre en pause ci-dessus.", "pt": "A memória continua ativa: a tua próxima pergunta recomeça-a. Podes pausá-la acima.", "it": "La memoria è ancora attiva: la tua prossima domanda la fa ripartire. Puoi metterla in pausa qui sopra.", "de": "Das Gedächtnis ist weiter eingeschaltet: Deine nächste Frage beginnt es neu. Du kannst es oben pausieren."]
        // On the glass: the offer and the receipt (46 characters at most for the line, 22 for the button)
        result["I can pick this up next time"] = ["fr": "Je peux reprendre ça la prochaine fois", "pt": "Posso retomar isto da próxima vez", "it": "Posso riprenderlo la prossima volta", "de": "Ich kann das nächstes Mal aufgreifen"]
        result["How it works"] = ["fr": "Comment ça marche", "pt": "Como funciona", "it": "Come funziona", "de": "So funktioniert es"]
        result["See memory"] = ["fr": "Voir la mémoire", "pt": "Ver memória", "it": "Vedi memoria", "de": "Gedächtnis ansehen"]
        result["Saved in memory"] = ["fr": "Enregistré en mémoire", "pt": "Guardado na memória", "it": "Salvato in memoria", "de": "Im Gedächtnis gemerkt"]
        result["{0}: saved in memory"] = ["fr": "{0} : enregistré en mémoire", "pt": "{0}: guardado na memória", "it": "{0}: salvato in memoria", "de": "{0}: im Gedächtnis gemerkt"]
        result["Saved: {0} is now in memory"] = ["fr": "Enregistré : {0} est en mémoire", "pt": "Guardado: {0} já está na memória", "it": "Salvato: {0} è ora in memoria", "de": "Gemerkt: {0} ist jetzt im Gedächtnis"]
        result["{0}: asked {1}× so far"] = ["fr": "{0} : {1} questions jusqu'ici", "pt": "{0}: {1} perguntas até agora", "it": "{0}: {1} domande finora", "de": "{0}: bisher {1}-mal gefragt"]
        result["{0}: {1}"] = ["fr": "{0} : {1}", "pt": "{0}: {1}", "it": "{0}: {1}", "de": "{0}: {1}"]
        result["asked less than a day ago"] = ["fr": "il y a moins d'un jour", "pt": "há menos de um dia", "it": "meno di un giorno fa", "de": "vor weniger als einem Tag"]
        result["asked 1 day ago"] = ["fr": "il y a 1 jour", "pt": "há 1 dia", "it": "1 giorno fa", "de": "vor 1 Tag"]
        result["asked {0} days ago"] = ["fr": "il y a {0} jours", "pt": "há {0} dias", "it": "{0} giorni fa", "de": "vor {0} Tagen"]
        result["flat since"] = ["fr": "stable depuis", "pt": "sem alteração", "it": "invariato", "de": "seitdem unverändert"]
        result["up {0}% since"] = ["fr": "+{0} % depuis", "pt": "subiu {0}%", "it": "in rialzo del {0}%", "de": "seitdem +{0} %"]
        result["down {0}% since"] = ["fr": "−{0} % depuis", "pt": "desceu {0}%", "it": "in calo del {0}%", "de": "seitdem −{0} %"]
        return result
    }()
}
