import Foundation

extension NativeTranslations18 {
    /// Memory: consent, receipts, the memory screen.
    /// The receipt rows (the last block) appear on the glass: each must stay within
    /// `NucleoNudge.textLimit` with a symbol of up to eight characters (Memory18NudgeTests measures them).
    static let memory: [String: [String: String]] = {
        var result: [String: [String: String]] = [:]
        // The consent sheet
        // What reaches the AI provider, as api/_lib/user-memory.ts (readerContext) sends it
        result["Not now"] = ["fr": "Pas maintenant", "pt": "Agora não", "it": "Non ora", "de": "Nicht jetzt"]
        result["Remember"] = ["fr": "Retenir", "pt": "Lembrar", "it": "Ricorda", "de": "Merken"]
        // The memory screen
        result["What I remember"] = ["fr": "Ce que je retiens", "pt": "O que recordo", "it": "Quello che ricordo", "de": "Was ich mir merke"]
        result["About you"] = ["fr": "À propos de toi", "pt": "Sobre ti", "it": "Su di te", "de": "Über dich"]
        result["Turn on"] = ["fr": "Activer", "pt": "Ativar", "it": "Attiva", "de": "Einschalten"]
        result["Opens the full explanation before anything is turned on."] = ["fr": "Ouvre l'explication complète avant toute activation.", "pt": "Abre a explicação completa antes de ativar seja o que for.", "it": "Apre la spiegazione completa prima di attivare qualsiasi cosa.", "de": "Öffnet die vollständige Erklärung, bevor etwas eingeschaltet wird."]
        result["Bobby keeps these on this iPhone, not on its servers. The text of a thesis is sent, with that question, only when you start a review: to Bobby and to the AI providers that write the answer."] = ["fr": "Bobby garde ces éléments sur cet iPhone, pas sur ses serveurs. Le texte d'une thèse est envoyé, avec cette question, seulement quand tu lances une révision : à Bobby et aux fournisseurs d'IA qui rédigent la réponse.", "pt": "O Bobby guarda isto neste iPhone, não nos seus servidores. O texto de uma tese é enviado, com essa pergunta, apenas quando inicias uma revisão: ao Bobby e aos fornecedores de IA que escrevem a resposta.", "it": "Bobby conserva questi dati su questo iPhone, non sui suoi server. Il testo di una tesi viene inviato, con quella domanda, solo quando avvii una revisione: a Bobby e ai fornitori di IA che scrivono la risposta.", "de": "Bobby speichert das auf diesem iPhone, nicht auf seinen Servern. Der Text einer These wird nur gesendet, wenn du eine Überprüfung startest, zusammen mit dieser Frage: an Bobby und an die KI-Anbieter, die die Antwort schreiben."]
        result["Forget removes an asset's shortcut. Delete everything clears the shortcuts, the theses you wrote and the follow-up notes."] = ["fr": "Oublier retire le raccourci d'un actif. Tout supprimer efface les raccourcis, les thèses que tu as écrites et les notes de suivi.", "pt": "Esquecer remove o atalho de um ativo. Eliminar tudo apaga os atalhos, as teses que escreveste e as notas de seguimento.", "it": "Dimentica rimuove la scorciatoia di un asset. Elimina tutto cancella le scorciatoie, le tesi che hai scritto e le note sugli aggiornamenti.", "de": "Vergessen entfernt den Schnellzugriff eines Werts. Alles löschen entfernt die Schnellzugriffe, die Thesen, die du geschrieben hast, und die Follow-up-Notizen."]
        result["Recent assets shown as shortcuts"] = ["fr": "Actifs récents affichés comme raccourcis", "pt": "Ativos recentes mostrados como atalhos", "it": "Asset recenti mostrati come scorciatoie", "de": "Zuletzt gefragte Werte als Schnellzugriffe"]
        result["No shortcuts"] = ["fr": "Aucun raccourci", "pt": "Sem atalhos", "it": "Nessuna scorciatoia", "de": "Keine Schnellzugriffe"]
        result["Clear"] = ["fr": "Effacer", "pt": "Limpar", "it": "Cancella", "de": "Leeren"]
        result["Clear the shortcuts on this iPhone"] = ["fr": "Effacer les raccourcis de cet iPhone", "pt": "Limpar os atalhos deste iPhone", "it": "Cancella le scorciatoie su questo iPhone", "de": "Schnellzugriffe auf diesem iPhone leeren"]
        result["Theses you wrote"] = ["fr": "Thèses que tu as écrites", "pt": "Teses que escreveste", "it": "Tesi che hai scritto", "de": "Thesen, die du geschrieben hast"]
        result["No theses"] = ["fr": "Aucune thèse", "pt": "Sem teses", "it": "Nessuna tesi", "de": "Keine Thesen"]
        result["This deletes what Bobby's servers remember about your account, the shortcuts on this iPhone and the theses you wrote here, with Bobby's follow-up notes. It cannot be undone."] = ["fr": "Cela supprime ce que les serveurs de Bobby retiennent sur ton compte, les raccourcis de cet iPhone et les thèses que tu as écrites ici, avec les notes de suivi de Bobby. C'est irréversible.", "pt": "Isto elimina o que os servidores do Bobby recordam sobre a tua conta, os atalhos deste iPhone e as teses que escreveste aqui, com as notas de seguimento do Bobby. Não pode ser anulado.", "it": "Questo elimina ciò che i server di Bobby ricordano del tuo account, le scorciatoie su questo iPhone e le tesi che hai scritto qui, con le note di Bobby sugli aggiornamenti. Non si può annullare.", "de": "Das löscht, was Bobbys Server über dein Konto gespeichert haben, die Schnellzugriffe auf diesem iPhone und die Thesen, die du hier geschrieben hast, samt Bobbys Follow-up-Notizen. Das lässt sich nicht rückgängig machen."]
        result["Deleted: what Bobby's servers remembered, the shortcuts on this iPhone and the theses you wrote here, with Bobby's follow-up notes."] = ["fr": "Supprimé : ce que les serveurs de Bobby retenaient, les raccourcis de cet iPhone et les thèses que tu as écrites ici, avec les notes de suivi de Bobby.", "pt": "Eliminado: o que os servidores do Bobby recordavam, os atalhos deste iPhone e as teses que escreveste aqui, com as notas de seguimento do Bobby.", "it": "Eliminato: ciò che i server di Bobby ricordavano, le scorciatoie su questo iPhone e le tesi che hai scritto qui, con le note di Bobby sugli aggiornamenti.", "de": "Gelöscht: was Bobbys Server gespeichert hatten, die Schnellzugriffe auf diesem iPhone und die Thesen, die du hier geschrieben hast, samt Bobbys Follow-up-Notizen."]
        result["Deleted on this iPhone. Bobby's servers did not confirm, so what they remember is still there. Try again."] = ["fr": "Supprimé sur cet iPhone. Les serveurs de Bobby n'ont pas confirmé : ce qu'ils retiennent est toujours là. Réessaie.", "pt": "Eliminado neste iPhone. Os servidores do Bobby não confirmaram, por isso o que recordam continua lá. Tenta novamente.", "it": "Eliminato su questo iPhone. I server di Bobby non hanno confermato, quindi ciò che ricordano è ancora lì. Riprova.", "de": "Auf diesem iPhone gelöscht. Bobbys Server haben nicht bestätigt, daher ist dort noch vorhanden, was sie gespeichert haben. Versuch es noch einmal."]
        result["Forgotten on this iPhone. Bobby's servers did not confirm, so they still remember {0}. Try again."] = ["fr": "Oublié sur cet iPhone. Les serveurs de Bobby n'ont pas confirmé : ils retiennent encore {0}. Réessaie.", "pt": "Esquecido neste iPhone. Os servidores do Bobby não confirmaram, por isso ainda recordam {0}. Tenta novamente.", "it": "Dimenticato su questo iPhone. I server di Bobby non hanno confermato, quindi ricordano ancora {0}. Riprova.", "de": "Auf diesem iPhone vergessen. Bobbys Server haben nicht bestätigt, daher merken sie sich {0} noch. Versuch es noch einmal."]
        // On the glass: the offer and the receipt (46 characters at most for the line, 22 for the button)
        result["I can pick this up next time"] = ["fr": "Je peux reprendre ça la prochaine fois", "pt": "Posso retomar isto da próxima vez", "it": "Posso riprenderlo la prossima volta", "de": "Ich kann das nächstes Mal aufgreifen"]
        result["How it works"] = ["fr": "Comment ça marche", "pt": "Como funciona", "it": "Come funziona", "de": "So funktioniert es"]
        result["See memory"] = ["fr": "Voir la mémoire", "pt": "Ver memória", "it": "Vedi memoria", "de": "Gedächtnis ansehen"]
        result["Saved in memory"] = ["fr": "Enregistré en mémoire", "pt": "Guardado na memória", "it": "Salvato in memoria", "de": "Im Gedächtnis gespeichert"]
        result["{0}: saved in memory"] = ["fr": "{0} : enregistré en mémoire", "pt": "{0}: guardado na memória", "it": "{0}: salvato in memoria", "de": "{0}: im Gedächtnis gespeichert"]
        result["Saved: {0} is now in memory"] = ["fr": "Enregistré : {0} est en mémoire", "pt": "Guardado: {0} já está na memória", "it": "Salvato: {0} è ora in memoria", "de": "Gespeichert: {0} ist jetzt im Gedächtnis"]
        result["{0}: asked {1}× so far"] = ["fr": "{0} : {1} questions jusqu'ici", "pt": "{0}: {1} perguntas até agora", "it": "{0}: {1} domande finora", "de": "{0}: bisher {1}-mal gefragt"]
        result["{0}: {1}"] = ["fr": "{0} : {1}", "pt": "{0}: {1}", "it": "{0}: {1}", "de": "{0}: {1}"]
        // When the previous question was: with its verb first, and a shorter form the line falls back to
        result["asked less than a day ago"] = ["fr": "demandé il y a moins d'un jour", "pt": "perguntaste há menos de um dia", "it": "chiesto meno di un giorno fa", "de": "vor weniger als einem Tag gefragt"]
        result["less than a day ago"] = ["fr": "il y a moins d'un jour", "pt": "há menos de um dia", "it": "meno di un giorno fa", "de": "vor weniger als einem Tag"]
        result["asked 1 day ago"] = ["fr": "demandé il y a 1 jour", "pt": "perguntaste há 1 dia", "it": "chiesto 1 giorno fa", "de": "vor 1 Tag gefragt"]
        result["1 day ago"] = ["fr": "il y a 1 jour", "pt": "há 1 dia", "it": "1 giorno fa", "de": "vor 1 Tag"]
        result["asked {0} days ago"] = ["fr": "demandé il y a {0} jours", "pt": "perguntaste há {0} dias", "it": "chiesto {0} giorni fa", "de": "vor {0} Tagen gefragt"]
        result["{0} days ago"] = ["fr": "il y a {0} jours", "pt": "há {0} dias", "it": "{0} giorni fa", "de": "vor {0} Tagen"]
        result["flat since"] = ["fr": "stable depuis", "pt": "sem alteração", "it": "invariato", "de": "seitdem unverändert"]
        result["up {0}% since"] = ["fr": "+{0} % depuis", "pt": "subiu {0}%", "it": "in rialzo del {0}%", "de": "seitdem +{0} %"]
        result["down {0}% since"] = ["fr": "−{0} % depuis", "pt": "desceu {0}%", "it": "in calo del {0}%", "de": "seitdem −{0} %"]
        result["Remember this?"] = ["fr": "Je m'en souviens ?", "pt": "Lembro-me disto?", "it": "Lo ricordo?", "de": "Soll ich mir das merken?"]
        result["Kept by Bobby"] = ["fr": "Bobby garde", "pt": "O Bobby guarda", "it": "Bobby conserva", "de": "Bobby speichert"]
        result["Asset · date · stated time frame · price that day"] = ["fr": "Actif · date · horizon indiqué · prix ce jour-là", "pt": "Ativo · data · prazo indicado · preço nesse dia", "it": "Asset · data · orizzonte indicato · prezzo di quel giorno", "de": "Wert · Datum · genannter Zeitraum · Kurs an diesem Tag"]
        result["Your question text is not kept."] = ["fr": "Le texte de ta question n'est pas gardé.", "pt": "O texto da tua pergunta não é guardado.", "it": "Il testo della tua domanda non viene conservato.", "de": "Der Text deiner Frage wird nicht gespeichert."]
        result["Sent to the AI that answers"] = ["fr": "Envoyé à l'IA qui répond", "pt": "Enviado à IA que responde", "it": "Inviato all'IA che risponde", "de": "An die antwortende KI gesendet"]
        result["Your first name · how often and when you asked about this asset · the time frame you named · its price that day and the change since · your preferences · your most-asked assets"] = ["fr": "Ton prénom · combien de fois et quand tu as posé une question sur cet actif · l'horizon que tu as indiqué · son prix ce jour-là et la variation depuis · tes préférences · les actifs sur lesquels tu poses le plus de questions", "pt": "O teu primeiro nome · quantas vezes e quando perguntaste por este ativo · o prazo que indicaste · o preço nesse dia e a variação desde então · as tuas preferências · os ativos sobre os quais mais perguntas", "it": "Il tuo nome · quante volte e quando hai chiesto di questo asset · l'orizzonte che hai indicato · il suo prezzo quel giorno e la variazione da allora · le tue preferenze · gli asset su cui chiedi più spesso", "de": "Dein Vorname · wie oft und wann du nach diesem Wert gefragt hast · der Zeitraum, den du genannt hast · sein Kurs an diesem Tag und die Änderung seitdem · deine Einstellungen · die Werte, nach denen du am häufigsten fragst"]
        result["Unused after {0} days without a question."] = ["fr": "N'est plus utilisé après {0} jours sans question.", "pt": "Deixa de ser usado após {0} dias sem perguntas.", "it": "Non viene più usato dopo {0} giorni senza domande.", "de": "Wird nach {0} Tagen ohne Frage nicht mehr verwendet."]
        result["Edit or delete in Memory."] = ["fr": "Modifie ou supprime dans Mémoire.", "pt": "Edita ou apaga em Memória.", "it": "Modifica o elimina in Memoria.", "de": "Bearbeite oder lösche es unter Gedächtnis."]
        result["On from your next question."] = ["fr": "Active dès ta prochaine question.", "pt": "Ativa a partir da tua próxima pergunta.", "it": "Attiva dalla tua prossima domanda.", "de": "Aktiv ab deiner nächsten Frage."]
        result["Could not enable memory."] = ["fr": "Impossible d'activer la mémoire.", "pt": "Não foi possível ativar a memória.", "it": "Impossibile attivare la memoria.", "de": "Gedächtnis konnte nicht aktiviert werden."]
        result["Memory stays on. Your next question restarts it."] = ["fr": "La mémoire reste active. Ta prochaine question la relance.", "pt": "A memória continua ativa. A tua próxima pergunta reinicia-a.", "it": "La memoria resta attiva. La tua prossima domanda la riavvia.", "de": "Das Gedächtnis bleibt aktiv. Deine nächste Frage startet es neu."]
        result["No remembered assets."] = ["fr": "Aucun actif mémorisé.", "pt": "Sem ativos memorizados.", "it": "Nessun asset ricordato.", "de": "Keine gemerkten Werte."]
        result["On this iPhone"] = ["fr": "Sur cet iPhone", "pt": "Neste iPhone", "it": "Su questo iPhone", "de": "Auf diesem iPhone"]
        result["Your preferences"] = ["fr": "Tes préférences", "pt": "As tuas preferências", "it": "Le tue preferenze", "de": "Deine Einstellungen"]
        result["iPhone questions are not added to account memory."] = ["fr": "Les questions de l'iPhone ne s'ajoutent pas à la mémoire du compte.", "pt": "As perguntas do iPhone não entram na memória da conta.", "it": "Le domande dell'iPhone non entrano nella memoria dell'account.", "de": "iPhone-Fragen kommen nicht ins Konto-Gedächtnis."]
        return result
    }()
}
