import Foundation

extension NativeTranslations18 {
    /// Credits: balances, how to get more, restore. Also the detail lines of the two profile rows
    /// this track adds for the theses and reminders tracks (their titles are the lead's shared keys).
    static let credits: [String: [String: String]] = {
        var result: [String: [String: String]] = [:]
        // The screen
        result["Credits"] = ["fr": "Crédits", "pt": "Créditos", "it": "Crediti", "de": "Credits"]
        result["Your credits"] = ["fr": "Tes crédits", "pt": "Os teus créditos", "it": "I tuoi crediti", "de": "Deine Credits"]
        result["A credit is one read: Bobby's three agents debate your question."] = ["fr": "Un crédit, c'est une analyse : les trois agents de Bobby débattent de ta question.", "pt": "Um crédito é uma análise: os três agentes do Bobby debatem a tua pergunta.", "it": "Un credito è un'analisi: i tre agenti di Bobby discutono la tua domanda.", "de": "Ein Credit ist eine Analyse: Bobbys drei Agenten diskutieren deine Frage."]
        result["What you have"] = ["fr": "Ce que tu as", "pt": "O que tens", "it": "Cosa hai", "de": "Was du hast"]
        result["Get more"] = ["fr": "En obtenir plus", "pt": "Obter mais", "it": "Ottieni di più", "de": "Mehr bekommen"]
        result["Already paid?"] = ["fr": "Déjà payé ?", "pt": "Já pagaste?", "it": "Hai già pagato?", "de": "Schon bezahlt?"]
        result["Accept the risk notice to see your credits."] = ["fr": "Accepte l'avis de risque pour voir tes crédits.", "pt": "Aceita o aviso de risco para veres os teus créditos.", "it": "Accetta l'avviso sui rischi per vedere i tuoi crediti.", "de": "Akzeptiere den Risikohinweis, um deine Credits zu sehen."]
        result["Bobby could not read your credits right now."] = ["fr": "Bobby n'a pas pu lire tes crédits pour le moment.", "pt": "O Bobby não conseguiu ler os teus créditos agora.", "it": "Bobby non è riuscito a leggere i tuoi crediti in questo momento.", "de": "Bobby konnte deine Credits gerade nicht abrufen."]
        result["Got a code from Bobby? Your reads are added to your account at once."] = ["fr": "Tu as un code de Bobby ? Tes analyses sont ajoutées à ton compte tout de suite.", "pt": "Tens um código do Bobby? As tuas análises são adicionadas à tua conta de imediato.", "it": "Hai un codice di Bobby? Le tue analisi vengono aggiunte subito al tuo account.", "de": "Du hast einen Code von Bobby? Deine Analysen werden sofort deinem Konto gutgeschrieben."]
        result["You get {0} days of Bobby Pro for each friend who joins with your link, up to {1} friends."] = ["fr": "Tu reçois {0} jours de Bobby Pro pour chaque ami qui s'inscrit avec ton lien, jusqu'à {1} amis.", "pt": "Recebes {0} dias de Bobby Pro por cada amigo que se junta com a tua ligação, até {1} amigos.", "it": "Ricevi {0} giorni di Bobby Pro per ogni amico che si iscrive con il tuo link, fino a {1} amici.", "de": "Du bekommst {0} Tage Bobby Pro für jeden Freund, der über deinen Link beitritt, bis zu {1} Freunde."]
        result["Use this if you paid for Bobby Pro with your Apple Account on another iPhone or after reinstalling. Codes and gifts never need restoring."] = ["fr": "À utiliser si tu as payé Bobby Pro avec ton compte Apple sur un autre iPhone ou après une réinstallation. Les codes et les cadeaux n'ont jamais besoin d'être restaurés.", "pt": "Usa isto se pagaste Bobby Pro com a tua Conta Apple noutro iPhone ou depois de reinstalares. Códigos e ofertas nunca precisam de ser restaurados.", "it": "Usalo se hai pagato Bobby Pro con il tuo Account Apple su un altro iPhone o dopo una reinstallazione. Codici e regali non vanno mai ripristinati.", "de": "Nutze das, wenn du Bobby Pro mit deinem Apple Account auf einem anderen iPhone bezahlt hast oder nach einer Neuinstallation. Codes und Geschenke müssen nie wiederhergestellt werden."]
        // What you have
        result["Quick reads"] = ["fr": "Analyses Rapides", "pt": "Análises Rápidas", "it": "Analisi Rapide", "de": "Schnelle Analysen"]
        result["Deep reads"] = ["fr": "Analyses Approfondies", "pt": "Análises Profundas", "it": "Analisi Approfondite", "de": "Vertiefte Analysen"]
        result["Max reads"] = ["fr": "Analyses Maximales", "pt": "Análises Máximas", "it": "Analisi Massime", "de": "Maximale Analysen"]
        result["Gifted Quick reads"] = ["fr": "Analyses Rapides offertes", "pt": "Análises Rápidas oferecidas", "it": "Analisi Rapide in regalo", "de": "Geschenkte Schnelle Analysen"]
        result["Gifted Deep reads"] = ["fr": "Analyses Approfondies offertes", "pt": "Análises Profundas oferecidas", "it": "Analisi Approfondite in regalo", "de": "Geschenkte Vertiefte Analysen"]
        result["Gifted Max reads"] = ["fr": "Analyses Maximales offertes", "pt": "Análises Máximas oferecidas", "it": "Analisi Massime in regalo", "de": "Geschenkte Maximale Analysen"]
        result["Unlimited"] = ["fr": "Illimitées", "pt": "Ilimitadas", "it": "Illimitate", "de": "Unbegrenzt"]
        result["With Bobby Pro, within fair use."] = ["fr": "Avec Bobby Pro, dans la limite d'un usage raisonnable.", "pt": "Com Bobby Pro, dentro de uma utilização razoável.", "it": "Con Bobby Pro, entro un uso corretto.", "de": "Mit Bobby Pro, im Rahmen fairer Nutzung."]
        result["{0} of {1} left this week"] = ["fr": "{0} sur {1} restantes cette semaine", "pt": "{0} de {1} restantes esta semana", "it": "{0} su {1} rimaste questa settimana", "de": "{0} von {1} diese Woche übrig"]
        result["{0} of {1} left"] = ["fr": "{0} sur {1} restantes", "pt": "{0} de {1} restantes", "it": "{0} su {1} rimaste", "de": "{0} von {1} übrig"]
        result["Create your free account to get {0} every week"] = ["fr": "Crée ton compte gratuit pour en avoir {0} chaque semaine", "pt": "Cria a tua conta gratuita para teres {0} todas as semanas", "it": "Crea il tuo account gratuito per averne {0} ogni settimana", "de": "Erstelle dein kostenloses Konto und erhalte jede Woche {0}"]
        result["Create your free account to keep reading"] = ["fr": "Crée ton compte gratuit pour continuer", "pt": "Cria a tua conta gratuita para continuares", "it": "Crea il tuo account gratuito per continuare", "de": "Erstelle dein kostenloses Konto, um weiterzulesen"]
        result["Resets on {0}"] = ["fr": "Renouvellement {0}", "pt": "Renovação: {0}", "it": "Rinnovo: {0}", "de": "Erneuerung am {0}"]
        result["Resets today"] = ["fr": "Renouvellement aujourd'hui", "pt": "Renova hoje", "it": "Si rinnova oggi", "de": "Erneuerung heute"]
        result["Every {0} days"] = ["fr": "Tous les {0} jours", "pt": "A cada {0} dias", "it": "Ogni {0} giorni", "de": "Alle {0} Tage"]
        result["Every {0} days · resets {1}"] = ["fr": "Tous les {0} jours · renouvellement le {1}", "pt": "A cada {0} dias · renova a {1}", "it": "Ogni {0} giorni · si rinnova il {1}", "de": "Alle {0} Tage · Erneuerung am {1}"]
        result["Used after your plan's reads run out."] = ["fr": "Utilisées quand les analyses de ton forfait sont épuisées.", "pt": "Usadas quando as análises do teu plano acabam.", "it": "Usate quando finiscono le analisi del tuo piano.", "de": "Werden genutzt, wenn die Analysen deines Plans aufgebraucht sind."]
        result["Kept for when you are not on Bobby Pro."] = ["fr": "Gardées pour quand tu n'auras plus Bobby Pro.", "pt": "Guardadas para quando não tiveres Bobby Pro.", "it": "Conservate per quando non avrai Bobby Pro.", "de": "Aufgehoben für die Zeit, in der du kein Bobby Pro hast."]
        result["Kept for when Quick reads have a weekly limit."] = ["fr": "Gardées pour quand les analyses Rapides auront une limite hebdomadaire.", "pt": "Guardadas para quando as análises Rápidas tiverem um limite semanal.", "it": "Conservate per quando le analisi Rapide avranno un limite settimanale.", "de": "Aufgehoben für die Zeit, in der Schnelle Analysen ein Wochenlimit haben."]
        result["Not active"] = ["fr": "Inactif", "pt": "Não ativo", "it": "Non attivo", "de": "Nicht aktiv"]
        result["Active"] = ["fr": "Actif", "pt": "Ativo", "it": "Attivo", "de": "Aktiv"]
        result["Active · renews {0}"] = ["fr": "Actif · renouvellement le {0}", "pt": "Ativo · renova a {0}", "it": "Attivo · si rinnova il {0}", "de": "Aktiv · verlängert sich am {0}"]
        result["Active · ends {0}"] = ["fr": "Actif · se termine le {0}", "pt": "Ativo · termina a {0}", "it": "Attivo · termina il {0}", "de": "Aktiv · endet am {0}"]
        result["Gifted until {0}"] = ["fr": "Offert jusqu'au {0}", "pt": "Oferecido até {0}", "it": "In regalo fino al {0}", "de": "Geschenkt bis {0}"]
        result["From your invitations."] = ["fr": "Grâce à tes invitations.", "pt": "Pelos teus convites.", "it": "Grazie ai tuoi inviti.", "de": "Durch deine Einladungen."]
        result["A gift from Bobby."] = ["fr": "Un cadeau de Bobby.", "pt": "Uma oferta do Bobby.", "it": "Un regalo di Bobby.", "de": "Ein Geschenk von Bobby."]
        result["Managed on the web."] = ["fr": "Géré sur le web.", "pt": "Gerido na web.", "it": "Gestito sul web.", "de": "Wird im Web verwaltet."]
        result["Your gifted days run until {0}."] = ["fr": "Tes jours offerts vont jusqu'au {0}.", "pt": "Os teus dias oferecidos vão até {0}.", "it": "I tuoi giorni in regalo arrivano fino al {0}.", "de": "Deine geschenkten Tage laufen bis {0}."]
        // The profile row's one line
        result["What you have and how to get more"] = ["fr": "Ce que tu as et comment en obtenir plus", "pt": "O que tens e como obter mais", "it": "Cosa hai e come averne di più", "de": "Was du hast und wie du mehr bekommst"]
        result["{0} of {1} reads"] = ["fr": "{0} analyses sur {1}", "pt": "{0} de {1} análises", "it": "{0} analisi su {1}", "de": "{0} von {1} Analysen"]
        result["Unlimited reads"] = ["fr": "Analyses illimitées", "pt": "Análises ilimitadas", "it": "Analisi illimitate", "de": "Unbegrenzte Analysen"]
        result["1 gifted"] = ["fr": "1 offerte", "pt": "1 oferecida", "it": "1 in regalo", "de": "1 geschenkt"]
        result["{0} gifted"] = ["fr": "{0} offertes", "pt": "{0} oferecidas", "it": "{0} in regalo", "de": "{0} geschenkt"]
        result["Bobby Pro until {0}"] = ["fr": "Bobby Pro jusqu'au {0}", "pt": "Bobby Pro até {0}", "it": "Bobby Pro fino al {0}", "de": "Bobby Pro bis {0}"]
        result["Bobby Pro active"] = ["fr": "Bobby Pro actif", "pt": "Bobby Pro ativo", "it": "Bobby Pro attivo", "de": "Bobby Pro aktiv"]
        // Restore, in words
        result["Restored. Bobby Pro is active on your account."] = ["fr": "Restauré. Bobby Pro est actif sur ton compte.", "pt": "Restaurado. Bobby Pro está ativo na tua conta.", "it": "Ripristinato. Bobby Pro è attivo sul tuo account.", "de": "Wiederhergestellt. Bobby Pro ist für dein Konto aktiv."]
        result["No Bobby Pro purchase was found on this Apple Account. If you paid with a different Apple Account, sign in to it on this iPhone and try again."] = ["fr": "Aucun achat Bobby Pro trouvé sur ce compte Apple. Si tu as payé avec un autre compte Apple, connecte-toi avec lui sur cet iPhone et réessaie.", "pt": "Não foi encontrada nenhuma compra de Bobby Pro nesta Conta Apple. Se pagaste com outra Conta Apple, inicia sessão com ela neste iPhone e tenta novamente.", "it": "Nessun acquisto di Bobby Pro trovato su questo Account Apple. Se hai pagato con un altro Account Apple, accedi con quello su questo iPhone e riprova.", "de": "Für diesen Apple Account wurde kein Bobby-Pro-Kauf gefunden. Wenn du mit einem anderen Apple Account bezahlt hast, melde dich auf diesem iPhone damit an und versuche es erneut."]
        result["Your account already has Bobby Pro until {0}, from an invitation. There is no App Store purchase to restore."] = ["fr": "Ton compte a déjà Bobby Pro jusqu'au {0}, grâce à une invitation. Il n'y a aucun achat App Store à restaurer.", "pt": "A tua conta já tem Bobby Pro até {0}, por um convite. Não há nenhuma compra da App Store para restaurar.", "it": "Il tuo account ha già Bobby Pro fino al {0}, grazie a un invito. Non c'è nessun acquisto App Store da ripristinare.", "de": "Dein Konto hat Bobby Pro bereits bis {0}, durch eine Einladung. Es gibt keinen App-Store-Kauf zum Wiederherstellen."]
        result["Your account already has Bobby Pro until {0}, as a gift from Bobby. There is no App Store purchase to restore."] = ["fr": "Ton compte a déjà Bobby Pro jusqu'au {0}, offert par Bobby. Il n'y a aucun achat App Store à restaurer.", "pt": "A tua conta já tem Bobby Pro até {0}, como oferta do Bobby. Não há nenhuma compra da App Store para restaurar.", "it": "Il tuo account ha già Bobby Pro fino al {0}, come regalo di Bobby. Non c'è nessun acquisto App Store da ripristinare.", "de": "Dein Konto hat Bobby Pro bereits bis {0}, als Geschenk von Bobby. Es gibt keinen App-Store-Kauf zum Wiederherstellen."]
        result["Your account already has Bobby Pro, paid by card on the web. There is no App Store purchase to restore."] = ["fr": "Ton compte a déjà Bobby Pro, payé par carte sur le web. Il n'y a aucun achat App Store à restaurer.", "pt": "A tua conta já tem Bobby Pro, pago com cartão na web. Não há nenhuma compra da App Store para restaurar.", "it": "Il tuo account ha già Bobby Pro, pagato con carta sul web. Non c'è nessun acquisto App Store da ripristinare.", "de": "Dein Konto hat Bobby Pro bereits, per Karte im Web bezahlt. Es gibt keinen App-Store-Kauf zum Wiederherstellen."]
        result["Your account already has Bobby Pro. There is no other App Store purchase to restore."] = ["fr": "Ton compte a déjà Bobby Pro. Il n'y a aucun autre achat App Store à restaurer.", "pt": "A tua conta já tem Bobby Pro. Não há outra compra da App Store para restaurar.", "it": "Il tuo account ha già Bobby Pro. Non c'è nessun altro acquisto App Store da ripristinare.", "de": "Dein Konto hat Bobby Pro bereits. Es gibt keinen weiteren App-Store-Kauf zum Wiederherstellen."]
        result["Sign in with Apple first: Bobby Pro belongs to your Bobby account. Bobby then checks this Apple Account for a purchase."] = ["fr": "Connecte-toi d'abord avec Apple : Bobby Pro est lié à ton compte Bobby. Bobby vérifie ensuite si ce compte Apple a un achat.", "pt": "Inicia sessão com a Apple primeiro: Bobby Pro pertence à tua conta Bobby. Depois o Bobby verifica se esta Conta Apple tem uma compra.", "it": "Accedi prima con Apple: Bobby Pro è associato al tuo account Bobby. Poi Bobby controlla se questo Account Apple ha un acquisto.", "de": "Melde dich zuerst mit Apple an: Bobby Pro gehört zu deinem Bobby-Konto. Danach prüft Bobby, ob es für diesen Apple Account einen Kauf gibt."]
        result["Accept the risk notice first; then you can restore here."] = ["fr": "Accepte d'abord l'avis de risque ; ensuite, tu pourras restaurer ici.", "pt": "Aceita primeiro o aviso de risco; depois podes restaurar aqui.", "it": "Accetta prima l'avviso sui rischi; poi potrai ripristinare qui.", "de": "Akzeptiere zuerst den Risikohinweis; danach kannst du hier wiederherstellen."]
        // On the glass (the page ellipsizes past 46 characters; the button holds 22)
        result["{0} reads left this week"] = ["fr": "Il te reste {0} analyses cette semaine", "pt": "Restam-te {0} análises esta semana", "it": "Ti restano {0} analisi questa settimana", "de": "Noch {0} Analysen diese Woche"]
        result["1 read left this week"] = ["fr": "Il te reste 1 analyse cette semaine", "pt": "Resta-te 1 análise esta semana", "it": "Ti resta 1 analisi questa settimana", "de": "Noch 1 Analyse diese Woche"]
        result["No reads left this week"] = ["fr": "Plus aucune analyse cette semaine", "pt": "Sem análises esta semana", "it": "Nessuna analisi rimasta questa settimana", "de": "Keine Analysen mehr diese Woche"]
        result["See credits"] = ["fr": "Voir mes crédits", "pt": "Ver créditos", "it": "Vedi crediti", "de": "Credits ansehen"]
        result["Bobby gave you {0} reads"] = ["fr": "Bobby t'a offert {0} analyses", "pt": "O Bobby ofereceu-te {0} análises", "it": "Bobby ti ha regalato {0} analisi", "de": "Bobby hat dir {0} Analysen geschenkt"]
        result["Bobby gave you 1 read"] = ["fr": "Bobby t'a offert 1 analyse", "pt": "O Bobby ofereceu-te 1 análise", "it": "Bobby ti ha regalato 1 analisi", "de": "Bobby hat dir 1 Analyse geschenkt"]
        // The detail lines of the profile rows for the theses and reminders tracks
        result["What you are looking at, and why"] = ["fr": "Ce que tu regardes, et pourquoi", "pt": "O que estás a ver, e porquê", "it": "Cosa stai guardando, e perché", "de": "Was du dir ansiehst und warum"]
        result["Review reminders you set"] = ["fr": "Les rappels de révision que tu as créés", "pt": "Lembretes de revisão que definiste", "it": "Promemoria di revisione che hai impostato", "de": "Erinnerungen zur Überprüfung, die du gesetzt hast"]
        return result
    }()
}
