package xyz.bobbyprotocol.android.ui

/** Matched coupon copy for iOS and Android. Source: shared/coupon-copy.json. */
object CouponCopy {
    fun text(key: String, count: Int? = null, language: String = "en"): String {
        val value = rows[key]?.get(language) ?: rows[key]?.get("en") ?: key
        return count?.let { value.replace("{n}", it.toString()) } ?: value
    }
    internal val rows: Map<String, Map<String, String>> = mapOf(
        "title" to mapOf("en" to "Redeem a code", "es" to "Canjear un código", "fr" to "Utiliser un code", "pt" to "Resgatar um código", "it" to "Riscatta un codice", "de" to "Code einlösen"),
        "intro" to mapOf("en" to "Your reads are added directly to your account.", "es" to "Las lecturas se añaden directamente a tu cuenta.", "fr" to "Tes analyses sont ajoutées directement à ton compte.", "pt" to "As leituras são adicionadas diretamente à tua conta.", "it" to "Le analisi vengono aggiunte direttamente al tuo account.", "de" to "Deine Analysen werden direkt deinem Konto gutgeschrieben."),
        "code" to mapOf("en" to "Coupon code", "es" to "Código del cupón", "fr" to "Code du coupon", "pt" to "Código do cupão", "it" to "Codice coupon", "de" to "Gutscheincode"),
        "redeem" to mapOf("en" to "Redeem", "es" to "Canjear", "fr" to "Utiliser", "pt" to "Resgatar", "it" to "Riscatta", "de" to "Einlösen"),
        "redeeming" to mapOf("en" to "Redeeming…", "es" to "Canjeando…", "fr" to "Utilisation…", "pt" to "A resgatar…", "it" to "Riscatto…", "de" to "Wird eingelöst…"),
        "applied" to mapOf("en" to "Your gift is ready!", "es" to "¡Tu regalo está listo!", "fr" to "Ton cadeau est prêt !", "pt" to "O teu presente está pronto!", "it" to "Il tuo regalo è pronto!", "de" to "Dein Geschenk ist da!"),
        "already" to mapOf("en" to "This code was already redeemed", "es" to "Este código ya fue canjeado", "fr" to "Ce code a déjà été utilisé", "pt" to "Este código já foi resgatado", "it" to "Questo codice è già stato riscattato", "de" to "Dieser Code wurde bereits eingelöst"),
        "oneRead" to mapOf("en" to "You have one more Quick read", "es" to "Tienes una lectura Rápido más", "fr" to "Tu as une analyse Rapide de plus", "pt" to "Tens mais uma leitura Rápida", "it" to "Hai un’analisi Rapida in più", "de" to "Du hast eine weitere Schnell-Analyse"),
        "manyReads" to mapOf("en" to "You have {n} more Quick reads", "es" to "Tienes {n} lecturas Rápido más", "fr" to "Tu as {n} analyses Rapides de plus", "pt" to "Tens mais {n} leituras Rápidas", "it" to "Hai {n} analisi Rapide in più", "de" to "Du hast {n} weitere Schnell-Analysen"),
        "profundoAdded" to mapOf("en" to "Deep reads: +{n}", "es" to "Lecturas Profundo: +{n}", "fr" to "Analyses Approfondies : +{n}", "pt" to "Leituras Profundas: +{n}", "it" to "Analisi Approfondite: +{n}", "de" to "Tiefe Analysen: +{n}"),
        "maximoAdded" to mapOf("en" to "Maximum reads: +{n}", "es" to "Lecturas Máximo: +{n}", "fr" to "Analyses Maximales : +{n}", "pt" to "Leituras Máximas: +{n}", "it" to "Analisi Massime: +{n}", "de" to "Maximale Analysen: +{n}"),
        "balance" to mapOf("en" to "Gifted reads available", "es" to "Lecturas de regalo disponibles", "fr" to "Analyses offertes disponibles", "pt" to "Leituras oferecidas disponíveis", "it" to "Analisi in regalo disponibili", "de" to "Verfügbare geschenkte Analysen"),
        "quickBalance" to mapOf("en" to "Quick: {n}", "es" to "Rápido: {n}", "fr" to "Rapide : {n}", "pt" to "Rápido: {n}", "it" to "Rapida: {n}", "de" to "Schnell: {n}"),
        "deepBalance" to mapOf("en" to "Deep: {n}", "es" to "Profundo: {n}", "fr" to "Approfondie : {n}", "pt" to "Profundo: {n}", "it" to "Approfondita: {n}", "de" to "Tief: {n}"),
        "maxBalance" to mapOf("en" to "Maximum: {n}", "es" to "Máximo: {n}", "fr" to "Maximale : {n}", "pt" to "Máximo: {n}", "it" to "Massima: {n}", "de" to "Maximal: {n}"),
        "next" to mapOf("en" to "They are in your account. Return to Bobby, choose a level and ask your question.", "es" to "Ya están en tu cuenta. Vuelve a Bobby, elige un nivel y escribe tu pregunta.", "fr" to "Elles sont sur ton compte. Reviens à Bobby, choisis un niveau et pose ta question.", "pt" to "Já estão na tua conta. Volta ao Bobby, escolhe um nível e faz a tua pergunta.", "it" to "Sono nel tuo account. Torna a Bobby, scegli un livello e fai la tua domanda.", "de" to "Sie sind in deinem Konto. Gehe zu Bobby, wähle eine Stufe und stelle deine Frage."),
        "noRestore" to mapOf("en" to "No need to restore purchases.", "es" to "No necesitas restaurar compras.", "fr" to "Pas besoin de restaurer tes achats.", "pt" to "Não precisas de restaurar compras.", "it" to "Non serve ripristinare gli acquisti.", "de" to "Du musst keine Käufe wiederherstellen."),
        "pending" to mapOf("en" to "Your gift is confirmed. The balance could not be loaded yet.", "es" to "Tu regalo está confirmado. Aún no pudimos consultar el saldo.", "fr" to "Ton cadeau est confirmé. Le solde n’a pas encore pu être chargé.", "pt" to "O teu presente está confirmado. Ainda não foi possível consultar o saldo.", "it" to "Il tuo regalo è confermato. Il saldo non è ancora disponibile.", "de" to "Dein Geschenk ist bestätigt. Der Kontostand konnte noch nicht geladen werden."),
        "read" to mapOf("en" to "Make a read", "es" to "Hacer una lectura", "fr" to "Faire une analyse", "pt" to "Fazer uma leitura", "it" to "Fai un’analisi", "de" to "Analyse starten"),
        "done" to mapOf("en" to "Done", "es" to "Listo", "fr" to "Terminé", "pt" to "Feito", "it" to "Fatto", "de" to "Fertig"),
        "checkBalance" to mapOf("en" to "Check my balance", "es" to "Comprobar mi saldo", "fr" to "Vérifier mon solde", "pt" to "Consultar o meu saldo", "it" to "Controlla il saldo", "de" to "Kontostand prüfen"),
        "accountRequired" to mapOf("en" to "Sign in to redeem this code.", "es" to "Inicia sesión para canjear este código.", "fr" to "Connecte-toi pour utiliser ce code.", "pt" to "Inicia sessão para resgatar este código.", "it" to "Accedi per riscattare questo codice.", "de" to "Melde dich an, um diesen Code einzulösen."),
        "invalidCode" to mapOf("en" to "Check the code and try again.", "es" to "Revisa el código e intenta de nuevo.", "fr" to "Vérifie le code et réessaie.", "pt" to "Verifica o código e tenta novamente.", "it" to "Controlla il codice e riprova.", "de" to "Prüfe den Code und versuche es erneut."),
        "expired" to mapOf("en" to "This code has expired.", "es" to "Este código ya venció.", "fr" to "Ce code a expiré.", "pt" to "Este código expirou.", "it" to "Questo codice è scaduto.", "de" to "Dieser Code ist abgelaufen."),
        "exhausted" to mapOf("en" to "This code has no redemptions left.", "es" to "Este código ya se agotó.", "fr" to "Ce code est épuisé.", "pt" to "Este código esgotou.", "it" to "Questo codice è esaurito.", "de" to "Dieser Code ist aufgebraucht."),
        "rateLimited" to mapOf("en" to "Too many attempts. Wait before trying again.", "es" to "Demasiados intentos. Espera antes de volver a probar.", "fr" to "Trop de tentatives. Attends avant de réessayer.", "pt" to "Demasiadas tentativas. Espera antes de tentar novamente.", "it" to "Troppi tentativi. Attendi prima di riprovare.", "de" to "Zu viele Versuche. Warte, bevor du es erneut versuchst."),
        "unavailable" to mapOf("en" to "We could not confirm the result. Check your balance before trying the code again.", "es" to "No pudimos confirmar el resultado. Comprueba tu saldo antes de volver a canjear.", "fr" to "Le résultat n’a pas pu être confirmé. Vérifie ton solde avant de réutiliser le code.", "pt" to "Não foi possível confirmar o resultado. Consulta o saldo antes de resgatar novamente.", "it" to "Non è stato possibile confermare il risultato. Controlla il saldo prima di riprovare.", "de" to "Das Ergebnis konnte nicht bestätigt werden. Prüfe deinen Kontostand, bevor du den Code erneut einlöst."),
        "balanceUnavailable" to mapOf("en" to "Your balance is unavailable. Try checking it again.", "es" to "Tu saldo no está disponible. Intenta consultarlo de nuevo.", "fr" to "Ton solde est indisponible. Essaie de le vérifier à nouveau.", "pt" to "O teu saldo está indisponível. Tenta consultá-lo novamente.", "it" to "Il saldo non è disponibile. Prova a controllarlo di nuovo.", "de" to "Dein Kontostand ist nicht verfügbar. Prüfe ihn erneut."),
        "bonusRow" to mapOf("en" to "Gifted reads: {n}", "es" to "Lecturas de regalo: {n}", "fr" to "Analyses offertes : {n}", "pt" to "Leituras oferecidas: {n}", "it" to "Analisi in regalo: {n}", "de" to "Geschenkte Analysen: {n}"),
        "restoreDetail" to mapOf("en" to "For subscriptions bought with your store account. Coupon reads are added automatically.", "es" to "Para suscripciones compradas con tu cuenta de la tienda. Las lecturas del cupón se añaden automáticamente.", "fr" to "Pour les abonnements achetés avec ton compte de boutique. Les analyses du coupon sont ajoutées automatiquement.", "pt" to "Para subscrições compradas com a tua conta da loja. As leituras do cupão são adicionadas automaticamente.", "it" to "Per abbonamenti acquistati con il tuo account dello store. Le analisi del coupon vengono aggiunte automaticamente.", "de" to "Für Abos, die du mit deinem Store-Konto gekauft hast. Gutschein-Analysen werden automatisch gutgeschrieben."),
        "alreadyNext" to mapOf("en" to "No new gift was added. Check your balance to see the reads available.", "es" to "No se añadió otro regalo. Comprueba tu saldo para ver las lecturas disponibles.", "fr" to "Aucun nouveau cadeau n’a été ajouté. Vérifie ton solde pour voir les analyses disponibles.", "pt" to "Não foi adicionado outro presente. Consulta o saldo para ver as leituras disponíveis.", "it" to "Non è stato aggiunto un altro regalo. Controlla il saldo per vedere le analisi disponibili.", "de" to "Es wurde kein neues Geschenk hinzugefügt. Prüfe deinen Kontostand für verfügbare Analysen."),
        "allowanceRow" to mapOf("en" to "Plan reads available: {n}", "es" to "Lecturas del plan disponibles: {n}", "fr" to "Analyses du forfait disponibles : {n}", "pt" to "Leituras do plano disponíveis: {n}", "it" to "Analisi del piano disponibili: {n}", "de" to "Verfügbare Analysen im Plan: {n}"),
        "unlimited" to mapOf("en" to "Unlimited Quick reads", "es" to "Lecturas Rápido sin límite", "fr" to "Analyses Rapides illimitées", "pt" to "Leituras Rápidas sem limite", "it" to "Analisi Rapide illimitate", "de" to "Unbegrenzte Schnell-Analysen"),
    )
}
