#!/usr/bin/env python3
"""Build the browser catalogue from native copy and explicit browser overrides."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ('fr', 'pt', 'it', 'de')
rows = {}
for line in (ROOT / 'ios/Bobby/Sources/NativeTranslations.swift').read_text().splitlines():
    match = re.match(r'\s*result\[("(?:\\.|[^"\\])*")\] = \[(.*)\]\s*$', line)
    if match:
        rows[json.loads(match[1])] = json.loads('{' + match[2] + '}')
assert rows, 'Native catalogue not found'
rows.update(json.loads((ROOT / 'src/lib/companions/web-translations-extra.json').read_text()))
for key, translations in rows.items():
    assert set(translations) == set(LANGUAGES), f'Incomplete languages: {key}'
    placeholders = sorted(re.findall(r'\{\d+\}', key))
    for language, value in translations.items():
        assert value and isinstance(value, str), f'Empty {language}: {key}'
        assert sorted(re.findall(r'\{\d+\}', value)) == placeholders, f'Placeholder mismatch {language}: {key}'
catalogue = {language: {key: translations[language] for key, translations in sorted(rows.items())} for language in LANGUAGES}
output = ROOT / 'src/lib/companions/web-translations.ts'
output.write_text('// Generated by scripts/build-web-locales.py. Edit native copy or web-translations-extra.json.\n'
                  + "export const WEB_TRANSLATIONS: Record<'fr' | 'pt' | 'it' | 'de', Record<string, string>> = "
                  + json.dumps(catalogue, ensure_ascii=False, indent=2) + ';\n')
print(f'PASS: {len(rows)} keys, {len(rows) * len(LANGUAGES)} browser translations, matching placeholders')
