// Codex round-4 P2: the backend ABI must come FROM the Foundry artifact, not from
// a hand-written list that a test merely compares. This writes the generated
// module the backend imports. Run after `forge build` and commit the result:
//   npm run gen:hardness-abi
import { readFileSync, writeFileSync } from 'node:fs';
const SRC = 'contracts/out/HardnessRegistry.sol/HardnessRegistry.json';
const OUT = 'api/_lib/hardness-registry.abi.ts';
const artifact = JSON.parse(readFileSync(SRC, 'utf8')) as { abi: unknown[] };
const body = `// GENERATED by scripts/gen-hardness-abi.mts from ${SRC} — do not edit by hand.
// scripts/test-hardness-abi-anvil.mts fails if this file drifts from the artifact.
export const HARDNESS_REGISTRY_ABI = ${JSON.stringify(artifact.abi, null, 1)} as const;
`;
writeFileSync(OUT, body);
console.log(`${OUT}: ${artifact.abi.length} ABI entries written from ${SRC}`);
