// Codex round-4 P2: the backend ABI must come FROM the Foundry artifact, not from
// a hand-written list that a test merely compares. This writes the generated
// modules the backend imports. Run after `forge build` and commit the result:
//   npm run gen:hardness-abi
//
// BP-07 (2026-09-04 review): BobbyAdversarialBounties joins the same rule — the
// MCP bounty tools decoded a hand-written 4-status enum and never read the
// per-bounty bond, so the unsigned challenge tx they handed out reverted.
import { readFileSync, writeFileSync } from 'node:fs';

const TARGETS = [
  {
    src: 'contracts/out/HardnessRegistry.sol/HardnessRegistry.json',
    out: 'api/_lib/hardness-registry.abi.ts',
    name: 'HARDNESS_REGISTRY_ABI',
    check: 'scripts/test-hardness-abi-anvil.mts',
  },
  {
    src: 'contracts/out/BobbyAdversarialBounties.sol/BobbyAdversarialBounties.json',
    out: 'api/_lib/adversarial-bounties.abi.ts',
    name: 'ADVERSARIAL_BOUNTIES_ABI',
    check: 'scripts/test-bounties-abi-anvil.mts',
  },
] as const;

for (const t of TARGETS) {
  const artifact = JSON.parse(readFileSync(t.src, 'utf8')) as { abi: unknown[] };
  const body = `// GENERATED by scripts/gen-hardness-abi.mts from ${t.src} — do not edit by hand.
// ${t.check} fails if this file drifts from the artifact.
export const ${t.name} = ${JSON.stringify(artifact.abi, null, 1)} as const;
`;
  writeFileSync(t.out, body);
  console.log(`${t.out}: ${artifact.abi.length} ABI entries written from ${t.src}`);
}
