// BP-10 (2026-09-04 review) against a real Postgres: registration is a
// compare-and-swap bound to the authorised owner and row version; ownership
// moves only through the explicit transfer with a single-use request id.
//
//   DATABASE_URL=postgres://postgres@127.0.0.1:54329/postgres npm run test:agent-registry-pg
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import pg from 'pg';

const url = process.env.DATABASE_URL;
if (!url) {
  // BP-06: skipping is a local convenience; in CI the database is a declared service and its absence must fail.
  if (process.env.CI === 'true') { console.error('test-agent-registry-pg: DATABASE_URL is required when CI=true'); process.exit(1); }
  console.log('test-agent-registry-pg: skipped (set DATABASE_URL to a scratch Postgres)'); process.exit(0);
}
{
  const host = new URL(url).hostname;
  if (!['localhost', '127.0.0.1', '::1', 'host.docker.internal'].includes(host) && process.env.SWAP_LEDGER_PG_ALLOW_REMOTE !== '1') {
    console.error(`test-agent-registry-pg: refusing non-local DATABASE_URL host "${host}"`); process.exit(2);
  }
}
const pool = new pg.Pool({ connectionString: url, max: 2 });
const S = `agents_test_${Date.now()}`;
const q = (sql: string) => sql.replaceAll('public.', `${S}.`).replaceAll('set search_path = public, pg_catalog', `set search_path = ${S}, pg_catalog`).replaceAll('S.', `${S}.`);
const migration = q(readFileSync('supabase/bobby-protocol/supabase/migrations/20260903000012_hardness_agent_cas.sql', 'utf8'));
const c = await pool.connect();
const fails = async (sql: string, params: unknown[], code: string) => {
  try { await c.query(q(sql), params); } catch (e: any) { assert.match(String(e.message), new RegExp(code), `expected ${code}, got ${e.message}`); return; }
  assert.fail(`expected failure ${code}`);
};
try {
  await c.query(`do $$ begin
    if not exists (select from pg_roles where rolname = 'anon') then create role anon noinherit; end if;
    if not exists (select from pg_roles where rolname = 'authenticated') then create role authenticated noinherit; end if;
    if not exists (select from pg_roles where rolname = 'service_role') then create role service_role noinherit bypassrls; end if;
  end $$;`);
  await c.query(`create schema ${S}`); await c.query(`set search_path to ${S}, public`);
  await c.query(q(`create table S.hardness_agents (id bigint generated by default as identity primary key, agent_id text not null unique, owner_address text not null, name text not null,
    agent_type text not null default 'trading-agent', version text, capabilities jsonb not null default '[]', mcp_endpoint text, webhook_url text, metadata_json jsonb not null default '{}',
    risk_policy_json jsonb not null default '{}', status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now())`));
  // the live table has a TEXT `version` (semver) — the migration's bigint row version must not collide with it
  await c.query(q(`alter table S.hardness_agents rename column version to semver`));
  await c.query(migration);
  const A = '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', B = '0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
  const row = (o: Record<string, unknown>) => JSON.stringify({ owner_address: A, name: 'A', ...o });
  // create: insert-only, version 1
  let r = await c.query(q(`select S.hardness_register_agent('ag', null, null, $1::jsonb) as r`), [row({})]);
  assert.equal(r.rows[0].r.version, 1); assert.equal(r.rows[0].r.owner_address, A);
  // creating again with "no expectation" is not an update
  await fails(`select S.hardness_register_agent('ag', null, null, $1::jsonb)`, [row({})], 'OWNER_MISMATCH');
  // update: must name the owner AND the version it authorised against
  r = await c.query(q(`select S.hardness_register_agent('ag', $2, 1, $1::jsonb) as r`), [row({ name: 'A2' }), A]);
  assert.equal(r.rows[0].r.version, 2); assert.equal(r.rows[0].r.name, 'A2');
  await fails(`select S.hardness_register_agent('ag', $2, 1, $1::jsonb)`, [row({ name: 'stale' }), A], 'STALE_VERSION');
  await fails(`select S.hardness_register_agent('ag', $2, 2, $1::jsonb)`, [row({}), B], 'OWNER_MISMATCH');
  // registration can never move the owner, even by the current owner with the right version
  await fails(`select S.hardness_register_agent('ag', $2, 2, $1::jsonb)`, [row({ owner_address: B }), A], 'OWNER_CHANGE_REQUIRES_TRANSFER');
  assert.equal((await c.query(q(`select owner_address from S.hardness_agents where agent_id = 'ag'`))).rows[0].owner_address, A, 'owner untouched');
  // transfer: current owner, exact version, single-use request id
  const rid = '11111111-2222-4333-8444-555555555555';
  await fails(`select S.hardness_transfer_agent('ag', $1, $2, 1, $3)`, [A, B, rid], 'STALE_VERSION');
  await fails(`select S.hardness_transfer_agent('ag', $1, $2, 2, $3)`, [B, A, rid], 'OWNER_MISMATCH');
  r = await c.query(q(`select S.hardness_transfer_agent('ag', $1, $2, 2, $3) as r`), [A, B, rid]);
  assert.equal(r.rows[0].r.owner_address, B); assert.equal(r.rows[0].r.version, 3);
  await fails(`select S.hardness_transfer_agent('ag', $1, $2, 3, $3)`, [B, A, rid], 'REQUEST_REPLAYED');
  // browser roles cannot call either function
  for (const role of ['anon', 'authenticated']) {
    for (const fn of ['hardness_register_agent(text,text,bigint,jsonb)', 'hardness_transfer_agent(text,text,text,bigint,uuid)']) {
      const p = await c.query('select has_function_privilege($1, $2, $3) as ok', [role, `${S}.${fn}`, 'EXECUTE']);
      assert.equal(p.rows[0].ok, false, `${role} can execute ${fn}`);
    }
  }
  console.log('BP-10: create is insert-only; update is CAS on owner + version; owner changes only via single-use transfer; browser roles excluded');
  console.log('agent registry (Postgres) tests passed');
} catch (e) { try { await c.query('rollback'); } catch { /* none */ } throw e; }
finally { await c.query(`drop schema if exists ${S} cascade`); c.release(); await pool.end(); }
