// ============================================================
// Companion data pack — a faithful port of the iOS squad (Companion.swift,
// AgentProfile.swift, CompanionTools.swift, LoadoutStep.swift) so the web
// tells the same story with the same names, voices, levels and gear.
// Keep both in sync until this pack is served by an endpoint.
// ============================================================
import type { Bi } from './i18n';

export interface Companion {
  id: string;
  label: string;
  role: Bi;
  personality: Bi;
  selectLine: Bi;
  secretPhrase: Bi;
  /** Identity hue 0..1 (same numbers as iOS). */
  hue: number;
  requiredLevel: number;
  voicePersona: string;
  evolutionNames: string[];
  /** Web-only: palette id in src/lib/mascot.ts and the GLB in public/mascots. */
  palette: string;
}

export const COMPANIONS: Companion[] = [
  { id: 'orb', label: 'BOBBY', role: { en: 'ORB · CORE', es: 'ORB · NÚCLEO', pt: 'ORB · NÚCLEO' , fr: "ORB · NOYAU", it: "ORB · NUCLEO", de: "ORB · KERN" }, personality: { en: 'the core that orchestrates the squad', es: 'el núcleo que orquesta al squad' , pt: "o núcleo que coordena a equipa", fr: "le noyau qui coordonne l'équipe", it: "il nucleo che coordina la squadra", de: "der Kern, der das Team koordiniert" }, selectLine: { en: 'Ready. We read the market together, calmly.', es: 'Listo. Leemos el mercado juntos, con calma.', pt: 'Pronto. A gente lê o mercado junto, com calma.' , fr: "Prêt. On analyse le marché ensemble, calmement.", it: "Pronto. Leggiamo il mercato insieme, con calma.", de: "Bereit. Wir betrachten den Markt gemeinsam, ganz ruhig." }, secretPhrase: { en: 'The market rewards who waits better, not who runs faster.', es: 'El mercado premia al que espera mejor, no al que corre más.' , pt: "O mercado recompensa quem sabe esperar, não quem corre mais depressa.", fr: "Le marché récompense ceux qui savent attendre, pas ceux qui courent le plus vite.", it: "Il mercato premia chi sa aspettare, non chi corre più veloce.", de: "Der Markt belohnt die, die besser warten, nicht die, die schneller rennen." }, hue: 0.415, requiredLevel: 1, voicePersona: 'ash', evolutionNames: ['BOBBY', 'BOBBY LINK', 'BOBBY CORE', 'BOBBY PRIME', 'BOBBY OMEGA'], palette: 'matrix' },
  { id: 'byte', label: 'BYTE', role: { en: 'PLAIN SPEAK', es: 'VOZ SIMPLE', pt: 'FALA SIMPLES' , fr: "LANGAGE CLAIR", it: "PAROLE SEMPLICI", de: "KLARTEXT" }, personality: { en: 'explains it without the jargon', es: 'te lo explica sin tecnicismos' , pt: "explica sem jargão", fr: "explique sans jargon", it: "spiega senza gergo", de: "erklärt ohne Fachjargon" }, selectLine: { en: 'Hey. I keep it simple, no jargon.', es: 'Hola. Yo te lo digo fácil, sin rollos.', pt: 'E aí. Eu explico fácil, sem jargão.' , fr: "Salut. Je fais simple, sans jargon.", it: "Ciao. La faccio semplice, senza gergo.", de: "Hallo. Ich erkläre es einfach, ohne Fachjargon." }, secretPhrase: { en: 'If you cannot explain it simply, do not trade it.', es: 'Si no lo puedes explicar simple, no lo operes.' , pt: "Se não o consegues explicar de forma simples, não negoceies.", fr: "Si tu ne peux pas l'expliquer simplement, ne le négocie pas.", it: "Se non riesci a spiegarlo in modo semplice, non negoziarlo.", de: "Wenn du es nicht einfach erklären kannst, handle es nicht." }, hue: 0.415, requiredLevel: 1, voicePersona: 'ballad', evolutionNames: ['BYTE', 'KILOBYTE', 'MEGABYTE', 'GIGABYTE', 'TERABYTE'], palette: 'matrix' },
  { id: 'kora', label: 'KORA', role: { en: 'CONVERSATION', es: 'CONVERSACIÓN', pt: 'CONVERSA' , fr: "CONVERSATION", it: "CONVERSAZIONE", de: "GESPRÄCH" }, personality: { en: 'talks markets like your best friend', es: 'platica del mercado como tu bestie' , pt: "fala dos mercados como o teu melhor amigo", fr: "parle des marchés comme ton meilleur ami", it: "parla di mercati come il tuo migliore amico", de: "spricht über Märkte wie dein bester Freund" }, selectLine: { en: 'I am here. Tell me what is on your mind.', es: 'Aquí andamos. Cuéntame qué traes en mente.', pt: 'Tô aqui. Me conta o que você tem em mente.' , fr: "Je suis là. Dis-moi ce qui te préoccupe.", it: "Sono qui. Dimmi cosa hai in mente.", de: "Ich bin da. Sag mir, was dich beschäftigt." }, secretPhrase: { en: 'The best decisions come from better questions.', es: 'Las mejores decisiones salen de las buenas preguntas.' , pt: "As melhores decisões nascem de melhores perguntas.", fr: "Les meilleures décisions viennent de meilleures questions.", it: "Le decisioni migliori nascono da domande migliori.", de: "Bessere Entscheidungen entstehen aus besseren Fragen." }, hue: 0.415, requiredLevel: 1, voicePersona: 'coral', evolutionNames: ['KORA', 'KORA ECO', 'KORA AURORA', 'KORA NOVA', 'KORA SUPERNOVA'], palette: 'matrix' },
  { id: 'zip', label: 'ZIP', role: { en: 'ALERTS', es: 'ALERTAS', pt: 'ALERTAS' , fr: "ALERTES", it: "AVVISI", de: "HINWEISE" }, personality: { en: 'fast to alert you, never to rush you', es: 'rápido para avisarte, nunca para apurarte' , pt: "avisa depressa, sem nunca te apressar", fr: "t'alerte vite, sans jamais te presser", it: "ti avvisa rapidamente, senza metterti fretta", de: "informiert schnell, ohne dich zu drängen" }, selectLine: { en: 'On it. If something moves, I will tell you.', es: 'Al tiro. Si algo se mueve, te aviso yo.', pt: 'Deixa comigo. Se algo se mexer, eu te aviso.' , fr: "Je m'en occupe. Si quelque chose bouge, je te le dis.", it: "Ci penso io. Se qualcosa si muove, te lo dico.", de: "Ich kümmere mich darum. Wenn sich etwas bewegt, sage ich dir Bescheid." }, secretPhrase: { en: 'Speed is for alerting, not for deciding.', es: 'La velocidad sirve para avisar, no para decidir.' , pt: "A rapidez serve para avisar, não para decidir.", fr: "La vitesse sert à alerter, pas à décider.", it: "La velocità serve per avvisare, non per decidere.", de: "Schnelligkeit dient dem Hinweis, nicht der Entscheidung." }, hue: 0.415, requiredLevel: 1, voicePersona: 'sage', evolutionNames: ['ZIP', 'ZIP PULSE', 'ZIP STORM', 'ZIP SONIC', 'ZIP LIGHTSPEED'], palette: 'matrix' },
  { id: 'glitch', label: 'GLITCH', role: { en: 'RED TEAM', es: 'RED TEAM', pt: 'RED TEAM' , fr: "CONTRE-ANALYSE", it: "CONTROANALISI", de: "GEGENPRÜFUNG" }, personality: { en: 'questions you before you get excited', es: 'te cuestiona antes de que te emociones' , pt: "questiona-te antes de te entusiasmares", fr: "te questionne avant que tu t'emballes", it: "ti mette in discussione prima che ti entusiasmi", de: "hinterfragt dich, bevor du dich begeisterst" }, selectLine: { en: 'Sure about that? Let me break your thesis first.', es: '¿Seguro? Déjame romper tu tesis primero.', pt: 'Certeza? Deixa eu quebrar sua tese primeiro.' , fr: "Tu es sûr ? Laisse-moi d'abord mettre ta thèse à l'épreuve.", it: "Ne sei sicuro? Lascia che metta prima alla prova la tua tesi.", de: "Bist du sicher? Lass mich zuerst deine These prüfen." }, secretPhrase: { en: 'Every thesis deserves an enemy before your money.', es: 'Toda tesis merece un enemigo antes que tu dinero.' , pt: "Cada tese merece um adversário antes de comprometeres o teu dinheiro.", fr: "Toute thèse mérite un adversaire avant d'engager ton argent.", it: "Ogni tesi merita un avversario prima di impegnare i tuoi soldi.", de: "Jede These verdient einen Gegner, bevor du dein Geld einsetzt." }, hue: 0.745, requiredLevel: 2, voicePersona: 'cedar', evolutionNames: ['GLITCH', 'GLITCH EDGE', 'GLITCH PROBE', 'GLITCH BREAKER', 'GLITCH ZERO'], palette: 'plasma' },
  { id: 'momo', label: 'MOMO', role: { en: 'EXPLORATION', es: 'EXPLORACIÓN', pt: 'EXPLORAÇÃO' , fr: "EXPLORATION", it: "ESPLORAZIONE", de: "ERKUNDUNG" }, personality: { en: 'explores with you, never afraid to ask', es: 'curiosea contigo sin miedo a preguntar' , pt: "explora contigo, sem receio de perguntar", fr: "explore avec toi, sans hésiter à poser des questions", it: "esplora con te, senza paura di chiedere", de: "erkundet mit dir und scheut keine Fragen" }, selectLine: { en: 'What if we explore something new today?', es: '¿Y si exploramos algo nuevo hoy?', pt: 'E se a gente explorar algo novo hoje?' , fr: "Et si on explorait quelque chose de nouveau aujourd'hui ?", it: "E se oggi esplorassimo qualcosa di nuovo?", de: "Wie wäre es, wenn wir heute etwas Neues erkunden?" }, secretPhrase: { en: 'Exploring costs no capital. Executing does.', es: 'Explorar no cuesta capital. Ejecutar sí.' , pt: "Explorar não custa capital. Executar, sim.", fr: "Explorer ne coûte pas de capital. Agir, si.", it: "Esplorare non costa capitale. Eseguire sì.", de: "Erkunden kostet kein Kapital. Handeln schon." }, hue: 0.745, requiredLevel: 2, voicePersona: 'marin', evolutionNames: ['MOMO', 'MOMO SCOUT', 'MOMO VOYAGER', 'MOMO COSMOS', 'MOMO INFINITE'], palette: 'plasma' },
  { id: 'flux', label: 'FLUX', role: { en: 'SIGNALS', es: 'SEÑALES', pt: 'SINAIS' , fr: "SIGNAUX", it: "SEGNALI", de: "SIGNALE" }, personality: { en: 'finds the context before the noise', es: 'detecta el contexto antes que el ruido' , pt: "encontra o contexto antes do ruído", fr: "trouve le contexte avant le bruit", it: "trova il contesto prima del rumore", de: "findet den Kontext vor dem Rauschen" }, selectLine: { en: 'Signal detected. Context first, noise later.', es: 'Señal detectada. Contexto primero, ruido después.', pt: 'Sinal detectado. Contexto primeiro, ruído depois.' , fr: "Signal détecté. Le contexte d'abord, le bruit ensuite.", it: "Segnale rilevato. Prima il contesto, poi il rumore.", de: "Signal erkannt. Erst der Kontext, dann das Rauschen." }, secretPhrase: { en: 'A signal without context is just pretty noise.', es: 'Una señal sin contexto es solo ruido bonito.' , pt: "Um sinal sem contexto é apenas ruído bonito.", fr: "Un signal sans contexte n'est que du bruit séduisant.", it: "Un segnale senza contesto è solo rumore attraente.", de: "Ein Signal ohne Kontext ist nur hübsches Rauschen." }, hue: 0.505, requiredLevel: 3, voicePersona: 'alloy', evolutionNames: ['FLUX', 'FLUX WAVE', 'FLUX RADAR', 'FLUX QUANTUM', 'FLUX SIGMA'], palette: 'ice' },
  { id: 'rook', label: 'ROOK', role: { en: 'THESIS', es: 'TESIS', pt: 'TESE' , fr: "THÈSE", it: "TESI", de: "THESE" }, personality: { en: 'builds the plan: entry, stop, invalidation', es: 'arma el plan: entrada, stop, invalidación' , pt: "constrói o plano: entrada, stop, invalidação", fr: "construit le plan : entrée, stop, invalidation", it: "costruisce il piano: entrata, stop, invalidazione", de: "erstellt den Plan: Einstieg, Stop, Invalidierung" }, selectLine: { en: 'Thesis in progress. Entry, stop, invalidation.', es: 'Tesis en construcción. Entrada, stop, invalidación.', pt: 'Tese em construção. Entrada, stop, invalidação.' , fr: "Thèse en cours. Entrée, stop, invalidation.", it: "Tesi in corso. Entrata, stop, invalidazione.", de: "These in Arbeit. Einstieg, Stop, Invalidierung." }, secretPhrase: { en: 'With no written invalidation it is not a thesis: it is hope.', es: 'Sin invalidación escrita no es tesis: es esperanza.' , pt: "Sem uma invalidação escrita, não é uma tese: é esperança.", fr: "Sans invalidation écrite, ce n'est pas une thèse : c'est de l'espoir.", it: "Senza un'invalidazione scritta non è una tesi: è speranza.", de: "Ohne schriftliche Invalidierung ist es keine These, sondern Hoffnung." }, hue: 0.415, requiredLevel: 3, voicePersona: 'onyx', evolutionNames: ['ROOK', 'ROOK GAMBIT', 'ROOK TACTICIAN', 'ROOK MASTER', 'GRANDMASTER'], palette: 'matrix' },
  { id: 'halo', label: 'HALO', role: { en: 'RISK GATE', es: 'RISK GATE', pt: 'RISK GATE' , fr: "CONTRÔLE DU RISQUE", it: "CONTROLLO DEL RISCHIO", de: "RISIKOPRÜFUNG" }, personality: { en: 'celebrates not trading with you', es: 'celebra contigo el no operar' , pt: "celebra contigo a decisão de não negociar", fr: "célèbre avec toi la décision de ne pas négocier", it: "celebra con te la scelta di non negoziare", de: "feiert mit dir, wenn du bewusst nicht handelst" }, selectLine: { en: 'Protecting capital today also counts as winning.', es: 'Hoy proteger capital también cuenta como ganar.', pt: 'Hoje proteger capital também conta como ganhar.' , fr: "Protéger le capital aujourd'hui, c'est aussi gagner.", it: "Proteggere il capitale oggi è anche una vittoria.", de: "Heute Kapital zu schützen, zählt ebenfalls als Gewinn." }, secretPhrase: { en: 'No setup yet. Capital protected.', es: 'No setup yet. Capital protected.' , pt: "Ainda sem cenário. Capital protegido.", fr: "Aucune configuration encore. Capital protégé.", it: "Nessuna configurazione ancora. Capitale protetto.", de: "Noch kein Setup. Kapital geschützt." }, hue: 0.56, requiredLevel: 4, voicePersona: 'shimmer', evolutionNames: ['HALO', 'HALO SHIELD', 'HALO WARDEN', 'HALO AEGIS', 'HALO SANCTUM'], palette: 'ghost' },
  { id: 'axiom', label: 'AXIOM', role: { en: 'TRACK RECORD', es: 'TRACK RECORD', pt: 'TRACK RECORD' , fr: "HISTORIQUE", it: "STORICO", de: "VERLAUF" }, personality: { en: 'remembers everything so you can verify', es: 'recuerda todo para que compruebes' , pt: "regista tudo para poderes verificar", fr: "garde une trace pour te permettre de vérifier", it: "ricorda tutto per permetterti di verificare", de: "merkt sich alles, damit du es überprüfen kannst" }, selectLine: { en: 'Everything gets recorded. Verifying is the edge.', es: 'Todo queda registrado. Comprobar es la ventaja.', pt: 'Tudo fica registrado. Conferir é a vantagem.' , fr: "Tout est enregistré. Vérifier fait la différence.", it: "Tutto viene registrato. Verificare fa la differenza.", de: "Alles wird festgehalten. Überprüfen macht den Unterschied." }, secretPhrase: { en: 'On-chain memory does not argue: it verifies.', es: 'La memoria on-chain no discute: comprueba.' , pt: "A memória na blockchain não discute: verifica.", fr: "La mémoire sur la blockchain ne discute pas : elle vérifie.", it: "La memoria sulla blockchain non discute: verifica.", de: "Das Gedächtnis auf der Blockchain diskutiert nicht: Es überprüft." }, hue: 0.115, requiredLevel: 5, voicePersona: 'fable', evolutionNames: ['AXIOM', 'AXIOM PROOF', 'AXIOM LEDGER', 'AXIOM ORACLE', 'AXIOM ETERNAL'], palette: 'gold' },
  // ---- Wave 2 (2026-09-07) — the feminine-forward half of the squad.
  // Each one owns a product moment that had no face: market regime, on-chain
  // flows, practice mode, growth, mentorship and probability. Voices are all
  // from FEM_VOICES in api/_lib/tts.ts so the Spanish delivery is gendered
  // correctly; see docs/brand/bobby-character-bible-wave2.md.
  { id: 'iris', label: 'IRIS', role: { en: 'MARKET REGIME', es: 'RÉGIMEN DE MERCADO', pt: 'REGIME DE MERCADO' , fr: "RÉGIME DE MARCHÉ", it: "REGIME DI MERCATO", de: "MARKTPHASE" }, personality: { en: 'reads the weather of the whole market', es: 'lee el clima de todo el mercado' , pt: "lê o clima de todo o mercado", fr: "lit la météo de tout le marché", it: "legge il clima dell'intero mercato", de: "liest die Wetterlage des gesamten Marktes" }, selectLine: { en: 'Let me read the weather first. Today there is wind.', es: 'Déjame leer el clima primero. Hoy hay viento.', pt: 'Deixa eu ler o clima primeiro. Hoje está ventando.' , fr: "Laisse-moi d'abord lire la météo. Aujourd'hui, il y a du vent.", it: "Lascia che legga prima il clima. Oggi c'è vento.", de: "Lass mich zuerst die Wetterlage prüfen. Heute weht Wind." }, secretPhrase: { en: 'The regime decides more than the setup does.', es: 'El régimen decide más que el setup.' , pt: "O regime pesa mais do que o cenário.", fr: "Le régime compte davantage que le scénario.", it: "Il regime conta più del singolo scenario.", de: "Die Marktphase entscheidet mehr als das einzelne Szenario." }, hue: 0.545, requiredLevel: 1, voicePersona: 'sage', evolutionNames: ['IRIS', 'IRIS CLEAR', 'IRIS FRONT', 'IRIS STORM', 'IRIS HORIZON'], palette: 'ice' },
  { id: 'sol', label: 'SOL', role: { en: 'GROWTH', es: 'CRECIMIENTO', pt: 'CRESCIMENTO' , fr: "CROISSANCE", it: "CRESCITA", de: "WACHSTUM" }, personality: { en: 'celebrates every step you actually take', es: 'celebra cada paso que sí das' , pt: "celebra cada passo que realmente dás", fr: "célèbre chaque étape que tu accomplis", it: "celebra ogni passo che compi davvero", de: "feiert jeden Schritt, den du wirklich gehst" }, selectLine: { en: 'Let us build your world, one earned piece at a time.', es: 'Vamos a construir tu mundo, pieza ganada por pieza ganada.', pt: 'Vamos construir seu mundo, uma peça conquistada de cada vez.' , fr: "Construisons ton univers, une pièce méritée à la fois.", it: "Costruiamo il tuo mondo, un pezzo guadagnato alla volta.", de: "Bauen wir deine Welt, ein verdientes Teil nach dem anderen." }, secretPhrase: { en: 'Discipline levels you up. Deposits never did.', es: 'La disciplina te sube de nivel. Los depósitos nunca lo hicieron.' , pt: "A disciplina faz-te subir de nível. Os depósitos nunca o fizeram.", fr: "La discipline te fait progresser. Les dépôts ne l'ont jamais fait.", it: "La disciplina ti fa salire di livello. I depositi non lo hanno mai fatto.", de: "Disziplin bringt dich auf die nächste Stufe. Einzahlungen haben das nie getan." }, hue: 0.115, requiredLevel: 1, voicePersona: 'coral', evolutionNames: ['SOL', 'SOL SPROUT', 'SOL BRANCH', 'SOL CANOPY', 'SOL BLOOM'], palette: 'gold' },
  { id: 'zuri', label: 'ZURI', role: { en: 'ON-CHAIN FLOWS', es: 'FLUJOS ON-CHAIN', pt: 'FLUXOS ON-CHAIN' , fr: "FLUX SUR LA BLOCKCHAIN", it: "FLUSSI SULLA BLOCKCHAIN", de: "BLOCKCHAIN-FLÜSSE" }, personality: { en: 'follows the money and tells you where it went', es: 'sigue el dinero y te dice a dónde se fue' , pt: "segue o dinheiro e diz-te para onde foi", fr: "suit l'argent et te dit où il est allé", it: "segue il denaro e ti dice dove è andato", de: "folgt dem Geld und zeigt dir, wohin es geflossen ist" }, selectLine: { en: 'Give me a minute. I am following the thread.', es: 'Dame un minuto. Voy siguiendo el hilo.', pt: 'Me dá um minuto. Estou seguindo o fio.' , fr: "Laisse-moi une minute. Je suis la piste.", it: "Dammi un minuto. Sto seguendo il filo.", de: "Gib mir eine Minute. Ich folge der Spur." }, secretPhrase: { en: 'Wallets do not post. They just move.', es: 'Las wallets no publican. Solo se mueven.' , pt: "As carteiras não publicam. Apenas movimentam fundos.", fr: "Les portefeuilles ne publient pas. Ils bougent.", it: "I portafogli non pubblicano. Si muovono e basta.", de: "Wallets posten nicht. Sie bewegen sich." }, hue: 0.075, requiredLevel: 1, voicePersona: 'nova', evolutionNames: ['ZURI', 'ZURI TRAIL', 'ZURI SIGNAL', 'ZURI DEPTH', 'ZURI ORACLE'], palette: 'lava' },
  { id: 'mira', label: 'MIRA', role: { en: 'PRACTICE', es: 'PRÁCTICA', pt: 'PRÁTICA' , fr: "ENTRAÎNEMENT", it: "PRATICA", de: "ÜBUNG" }, personality: { en: 'zero pressure, celebrates the attempt', es: 'cero presión, celebra el intento' , pt: "sem pressão, celebra a tentativa", fr: "sans pression, célèbre chaque essai", it: "nessuna pressione, celebra ogni tentativo", de: "ohne Druck, feiert jeden Versuch" }, selectLine: { en: 'No money on the line yet. Let us just look.', es: 'Todavía sin dinero de por medio. Nomás vamos viendo.', pt: 'Ainda sem dinheiro em jogo. Só vamos observar.' , fr: "Aucun argent en jeu. Contentons-nous d'observer.", it: "Nessun denaro in gioco. Limitiamoci a osservare.", de: "Noch kein Geld im Spiel. Schauen wir erst einmal." }, secretPhrase: { en: 'A rehearsal costs nothing. A habit pays forever.', es: 'Un ensayo no cuesta nada. Un hábito paga siempre.' , pt: "Um ensaio não custa nada. Um bom hábito fica.", fr: "Une répétition ne coûte rien. Une bonne habitude dure.", it: "Una prova non costa nulla. Una buona abitudine resta.", de: "Eine Probe kostet nichts. Eine gute Gewohnheit bleibt." }, hue: 0.505, requiredLevel: 1, voicePersona: 'alloy', evolutionNames: ['MIRA', 'MIRA DRILL', 'MIRA PACE', 'MIRA FORM', 'MIRA STAR'], palette: 'ghost' },
  { id: 'nalu', label: 'NALU', role: { en: 'LIQUIDITY', es: 'LIQUIDEZ', pt: 'LIQUIDEZ' , fr: "LIQUIDITÉ", it: "LIQUIDITÀ", de: "LIQUIDITÄT" }, personality: { en: 'reads flow like a wave, everything is timing', es: 'lee el flujo como una ola, todo es timing' , pt: "lê os fluxos como uma onda: tudo depende do momento", fr: "lit les flux comme une vague : tout est une question de timing", it: "legge i flussi come un'onda: conta il momento giusto", de: "liest den Fluss wie eine Welle: Der Zeitpunkt zählt" }, selectLine: { en: 'Not every wave is yours. Let us wait for the good one.', es: 'No toda ola es tuya. Esperemos la buena.', pt: 'Nem toda onda é sua. Vamos esperar a boa.' , fr: "Toutes les vagues ne sont pas pour toi. Attendons la bonne.", it: "Non tutte le onde sono tue. Aspettiamo quella giusta.", de: "Nicht jede Welle gehört dir. Warten wir auf die richtige." }, secretPhrase: { en: 'You do not fight the current. You time it.', es: 'A la corriente no se le pelea. Se le agarra el tiempo.' , pt: "Não lutas contra a corrente. Escolhes o momento certo.", fr: "On ne lutte pas contre le courant. On choisit le bon moment.", it: "Non combatti la corrente. Scegli il momento giusto.", de: "Du kämpfst nicht gegen die Strömung. Du wählst den richtigen Zeitpunkt." }, hue: 0.075, requiredLevel: 1, voicePersona: 'marin', evolutionNames: ['NALU', 'NALU SWELL', 'NALU CREST', 'NALU BARREL', 'NALU TIDE'], palette: 'lava' },
  { id: 'vega', label: 'VEGA', role: { en: 'PROBABILITY', es: 'PROBABILIDAD', pt: 'PROBABILIDADE' , fr: "PROBABILITÉ", it: "PROBABILITÀ", de: "WAHRSCHEINLICHKEIT" }, personality: { en: 'gives you the odds, never the promise', es: 'te da la probabilidad, nunca la promesa' , pt: "dá-te probabilidades, nunca promessas", fr: "te donne les probabilités, jamais de promesse", it: "ti dà le probabilità, mai promesse", de: "nennt dir Wahrscheinlichkeiten, niemals Versprechen" }, selectLine: { en: 'I can give you the probability. Not the promise.', es: 'Te puedo dar la probabilidad. La promesa no.', pt: 'Posso te dar a probabilidade. A promessa, não.' , fr: "Je peux te donner une probabilité. Pas une promesse.", it: "Posso darti la probabilità. Non una promessa.", de: "Ich kann dir die Wahrscheinlichkeit nennen. Kein Versprechen." }, secretPhrase: { en: 'A number without its error bar is a story.', es: 'Un número sin su margen de error es un cuento.' , pt: "Um número sem margem de erro é uma história.", fr: "Un chiffre sans marge d'erreur n'est qu'une histoire.", it: "Un numero senza margine d'errore è un racconto.", de: "Eine Zahl ohne Fehlergrenze ist eine Geschichte." }, hue: 0.115, requiredLevel: 3, voicePersona: 'shimmer', evolutionNames: ['VEGA', 'VEGA SIGMA', 'VEGA CONE', 'VEGA PRIME', 'VEGA ABSOLUTE'], palette: 'gold' },
  { id: 'noor', label: 'NOOR', role: { en: 'MENTORSHIP', es: 'MENTORÍA', pt: 'MENTORIA' , fr: "MENTORAT", it: "MENTORAGGIO", de: "MENTORING" }, personality: { en: 'unhurried, firm, has seen every cycle', es: 'sin prisa, firme, ya vio todos los ciclos' , pt: "calmo, firme, já viu todos os ciclos", fr: "patient, ferme, a connu tous les cycles", it: "calmo, deciso, ha visto ogni ciclo", de: "gelassen, bestimmt, kennt jeden Zyklus" }, selectLine: { en: 'Sit down. Let us review the week before the next trade.', es: 'Siéntate. Revisemos la semana antes del próximo trade.', pt: 'Senta aí. Vamos revisar a semana antes do próximo trade.' , fr: "Installe-toi. Faisons le bilan de la semaine avant la prochaine opération.", it: "Siediti. Rivediamo la settimana prima della prossima operazione.", de: "Setz dich. Gehen wir die Woche durch, bevor der nächste Trade ansteht." }, secretPhrase: { en: 'I have seen this cycle before. It ended the same way.', es: 'Ya vi este ciclo antes. Terminó igual.' , pt: "Já vi este ciclo. Terminou da mesma forma.", fr: "J'ai déjà vu ce cycle. Il s'est terminé de la même façon.", it: "Ho già visto questo ciclo. È finito allo stesso modo.", de: "Diesen Zyklus habe ich schon gesehen. Er endete genauso." }, hue: 0.115, requiredLevel: 4, voicePersona: 'fable', evolutionNames: ['NOOR', 'NOOR RING', 'NOOR CIRCLE', 'NOOR CROWN', 'NOOR ETERNAL'], palette: 'matrix' },
  { id: 'keo', label: 'KEO', role: { en: 'PATIENCE', es: 'PACIENCIA', pt: 'PACIÊNCIA' , fr: "PATIENCE", it: "PAZIENZA", de: "GEDULD" }, personality: { en: 'never in a hurry, and never early', es: 'nunca con prisa, y nunca antes de tiempo' , pt: "sem pressa, nunca antes da hora", fr: "jamais pressé, jamais trop tôt", it: "mai di fretta, mai in anticipo", de: "nie in Eile und nie zu früh" }, selectLine: { en: 'Sit with me a minute. The good one always comes.', es: 'Siéntate un minuto. La buena siempre llega.', pt: 'Senta comigo um minuto. A boa sempre chega.' , fr: "Reste une minute avec moi. La bonne occasion finit toujours par venir.", it: "Fermati un minuto con me. L'occasione giusta arriva.", de: "Bleib eine Minute bei mir. Die passende Gelegenheit kommt." }, secretPhrase: { en: 'Waiting is not doing nothing. It is the hardest part.', es: 'Esperar no es no hacer nada. Es la parte más difícil.' , pt: "Esperar não é não fazer nada. É a parte mais difícil.", fr: "Attendre, ce n'est pas ne rien faire. C'est le plus difficile.", it: "Aspettare non significa non fare nulla. È la parte più difficile.", de: "Warten heißt nicht, nichts zu tun. Es ist der schwierigste Teil." }, hue: 0.115, requiredLevel: 1, voicePersona: 'mellow', evolutionNames: ['KEO', 'KEO DRIFT', 'KEO GLIDE', 'KEO SOUL', 'KEO ETERNAL'], palette: 'gold' },
];

export function getCompanion(id: string | null | undefined): Companion | null {
  return COMPANIONS.find((c) => c.id === id) ?? null;
}

/** The identity tint as CSS, same hue math as the iOS `tint`. */
export function tintFor(c: Companion, alpha = 1): string {
  return `hsla(${Math.round(c.hue * 360)}, 70%, 62%, ${alpha})`;
}

export function companionName(c: Companion, level: number): string {
  const i = Math.max(0, Math.min(c.evolutionNames.length - 1, level - 1));
  return c.evolutionNames[i];
}

export interface CompanionLevel { number: number; name: string; label: Bi; minXP: number }

export const LEVELS: CompanionLevel[] = [
  { number: 1, name: 'SPAWNED', label: {"en": "SPAWNED", "es": "EN ESCENA", "pt": "CRIADO", "fr": "APPARU", "it": "APPARSO", "de": "ERSCHIENEN"}, minXP: 0 },
  { number: 2, name: 'LOCKED IN', label: {"en": "LOCKED IN", "es": "EN LA ZONA", "pt": "FOCADO", "fr": "ENGAGÉ", "it": "CONCENTRATO", "de": "FOKUSSIERT"}, minXP: 50 },
  { number: 3, name: 'MARKET READER', label: {"en": "MARKET READER", "es": "LEE EL MERCADO", "pt": "LEITOR DO MERCADO", "fr": "LECTEUR DU MARCHÉ", "it": "LETTORE DEL MERCATO", "de": "MARKTLESER"}, minXP: 150 },
  { number: 4, name: 'RISK GUARDIAN', label: {"en": "RISK GUARDIAN", "es": "CUIDA EL RIESGO", "pt": "GUARDIÃO DO RISCO", "fr": "GARDIEN DU RISQUE", "it": "GUARDIANO DEL RISCHIO", "de": "RISIKOWÄCHTER"}, minXP: 400 },
  { number: 5, name: 'ON-CHAIN LEGEND', label: {"en": "ON-CHAIN LEGEND", "es": "LEYENDA ON-CHAIN", "pt": "LENDA DA BLOCKCHAIN", "fr": "LÉGENDE DE LA BLOCKCHAIN", "it": "LEGGENDA DELLA BLOCKCHAIN", "de": "BLOCKCHAIN-LEGENDE"}, minXP: 1000 },
];

export function levelFor(xp: number): CompanionLevel {
  return [...LEVELS].reverse().find((l) => xp >= l.minXP) ?? LEVELS[0];
}
export function nextLevelFor(xp: number): CompanionLevel | null {
  return LEVELS.find((l) => l.minXP > xp) ?? null;
}

/** How the companion speaks at each level — the same character, more earned confidence. */
export const LEVEL_TONE: Record<number, Bi> = {
  1: { en: '', es: '', pt: '' , fr: "", it: "", de: "" },
  2: { en: ' We are finding our rhythm.', es: ' Ya agarramos ritmo.', pt: ' A gente já pegou o ritmo.' , fr: " On trouve notre rythme.", it: " Stiamo trovando il nostro ritmo.", de: " Wir finden unseren Rhythmus." },
  3: { en: ' After this many reads, I know your style.', es: ' Después de tantas lecturas, ya te conozco el estilo.', pt: ' Depois de tantas leituras, já conheço seu estilo.' , fr: " Après tant d'analyses, je connais ton style.", it: " Dopo tante analisi, conosco il tuo stile.", de: " Nach so vielen Analysen kenne ich deinen Stil." },
  4: { en: ' And above all: we protect the risk.', es: ' Y antes que nada: cuidamos el riesgo.', pt: ' E antes de tudo: a gente cuida do risco.' , fr: " Et surtout : on maîtrise le risque.", it: " E soprattutto: controlliamo il rischio.", de: " Und vor allem: Wir behalten das Risiko im Blick." },
  5: { en: ' We have a track record now. Here we verify, we do not promise.', es: ' Ya llevamos historial. Aquí se comprueba, no se promete.', pt: ' Agora temos histórico. Aqui se confere, não se promete.' , fr: " On a désormais un historique. Ici, on vérifie, on ne promet pas.", it: " Ora abbiamo uno storico. Qui verifichiamo, non promettiamo.", de: " Wir haben jetzt einen Verlauf. Hier überprüfen wir, statt Versprechen zu geben." },
};

export type VibeId = 'chill' | 'directo' | 'pro';
export interface Vibe { id: VibeId; label: Bi; desc: Bi; sample: Bi; /** id the TTS endpoint understands */ server: 'wise' | 'direct' | 'analytical' }

export const VIBES: Vibe[] = [
  { id: 'chill', label: { en: 'Chill', es: 'Chill' , pt: "Descontraído", fr: "Détendu", it: "Rilassato", de: "Entspannt" }, desc: { en: 'laid back, like a friend who actually knows', es: 'relajado, como tu compa que sí sabe' , pt: "descontraído, como um amigo que percebe do assunto", fr: "détendu, comme un ami qui s'y connaît", it: "rilassato, come un amico che se ne intende", de: "entspannt, wie ein Freund mit Ahnung" }, sample: { en: 'Alright — bitcoin is at sixty four thousand, quiet day.', es: 'Va — bitcoin anda en sesenta y cuatro mil, tranquilo el día.' , pt: "Ora bem, o bitcoin está nos sessenta e quatro mil. Dia tranquilo.", fr: "Bon, le bitcoin est à soixante-quatre mille. Journée calme.", it: "Bene, bitcoin è a sessantaquattromila. Giornata tranquilla.", de: "Also, Bitcoin steht bei vierundsechzigtausend. Ein ruhiger Tag." }, server: 'wise' },
  { id: 'directo', label: { en: 'Direct', es: 'Directo' , pt: "Direto", fr: "Direct", it: "Diretto", de: "Direkt" }, desc: { en: 'no fluff, straight data', es: 'cero rodeos, puro dato' , pt: "sem rodeios, só dados", fr: "sans détour, des données", it: "senza fronzoli, dati diretti", de: "ohne Umschweife, klare Daten" }, sample: { en: 'Bitcoin: sixty four thousand. Uptrend. Period.', es: 'Bitcoin: sesenta y cuatro mil. Tendencia alcista. Punto.' , pt: "Bitcoin: sessenta e quatro mil. Tendência de alta. Ponto.", fr: "Bitcoin : soixante-quatre mille. Tendance haussière. Point.", it: "Bitcoin: sessantaquattromila. Tendenza rialzista. Punto.", de: "Bitcoin: vierundsechzigtausend. Aufwärtstrend. Punkt." }, server: 'direct' },
  { id: 'pro', label: { en: 'Pro', es: 'Pro' , pt: "Pro", fr: "Pro", it: "Pro", de: "Pro" }, desc: { en: 'trading desk, technical', es: 'mesa de dinero, técnico' , pt: "mesa de negociação, técnico", fr: "salle des marchés, technique", it: "sala operativa, tecnico", de: "Trading-Desk, technisch" }, sample: { en: 'Bitcoin trades at sixty four thousand with its bullish structure intact.', es: 'Bitcoin cotiza en sesenta y cuatro mil con estructura alcista intacta.' , pt: "O bitcoin negoceia nos sessenta e quatro mil, com a estrutura de alta intacta.", fr: "Le bitcoin s'échange à soixante-quatre mille, sa structure haussière reste intacte.", it: "Bitcoin quota sessantaquattromila con la struttura rialzista intatta.", de: "Bitcoin notiert bei vierundsechzigtausend mit intakter Aufwärtsstruktur." }, server: 'analytical' },
];

export function getVibe(id: string | null | undefined): Vibe { return VIBES.find((v) => v.id === id) ?? VIBES[1]; }

// ---- Gear: three tools per companion; first read, then every 100 XP, the last golden ----

export interface CompanionTool { companionId: string; tier: 1 | 2 | 3; name: Bi; lore: Bi; glyph: string }

export function toolUnlockXP(tier: number): number { return tier === 1 ? 1 : (tier - 1) * 100; }
export function toolArt(tool: CompanionTool): string { return `/tools/tool_${tool.companionId}_${tool.tier}.png`; }
/** Every companion has Higgsfield art (tools + pet); the glyph path stays as a fallback for new companions. */
export const TOOL_ART_AVAILABLE = new Set(['orb', 'byte', 'kora', 'zip', 'glitch', 'momo', 'flux', 'rook', 'halo', 'axiom',
  // Wave 2 art shipped 2026-09-07
  'iris', 'sol', 'zuri', 'mira', 'nalu', 'vega', 'noor', 'keo']);
export function toolHasArt(tool: CompanionTool): boolean { return TOOL_ART_AVAILABLE.has(tool.companionId); }
export function toolTierLabel(tier: number): Bi {
  return tier === 1 ? { en: 'COMMON', es: 'COMÚN', pt: 'COMUM' , fr: "COMMUN", it: "COMUNE", de: "GEWÖHNLICH" } : tier === 2 ? { en: 'RARE', es: 'RARO', pt: 'RARO' , fr: "RARE", it: "RARO", de: "SELTEN" } : { en: 'GOLDEN', es: 'DORADO', pt: 'DOURADO' , fr: "DORÉ", it: "DORATO", de: "GOLDEN" };
}

const T = (companionId: string, tier: 1 | 2 | 3, glyph: string, en: string, es: string, loreEn: string, loreEs: string, pt?: string, lorePt?: string, fr?: string, loreFr?: string, it?: string, loreIt?: string, de?: string, loreDe?: string): CompanionTool =>
  ({ companionId, tier, glyph, name: { en, es, pt, fr, it, de }, lore: { en: loreEn, es: loreEs, pt: lorePt, fr: loreFr, it: loreIt, de: loreDe } });

export const TOOLS: Record<string, CompanionTool[]> = {
  orb: [
    T('orb', 1, '◷', 'Patience Chronometer', 'Cronómetro de paciencia', 'Counts the candles you did not chase.', 'Cuenta las velas que no perseguiste.', 'Cronômetro da paciência', 'Conta as velas que você não perseguiu.', "Chronomètre de patience", "Compte les bougies que tu n'as pas poursuivies.", "Cronometro della pazienza", "Conta le candele che non hai inseguito.", "Geduldschronometer", "Zählt die Kerzen, denen du nicht nachgejagt bist."),
    T('orb', 2, '✧', '4H Trend Compass', 'Brújula de tendencia 4H', 'Points where the structure goes, not where the noise does.', 'Apunta hacia donde va la estructura, no el ruido.', 'Bússola de tendência 4H', 'Aponta para onde vai a estrutura, não o ruído.', "Boussole de tendance 4H", "Montre la direction de la structure, pas du bruit.", "Bussola del trend 4H", "Indica dove va la struttura, non il rumore.", "4H-Trendkompass", "Zeigt, wohin die Struktur führt, nicht das Rauschen."),
    T('orb', 3, '◉', 'Omega Core', 'Núcleo Omega', "Bobby's own heart. You earned it by waiting better.", 'El corazón del propio Bobby. Te lo ganaste esperando mejor.', 'Núcleo Ômega', 'O coração do próprio Bobby. Você conquistou esperando melhor.', "Cœur Omega", "Le cœur de Bobby. Tu l'as gagné en apprenant à attendre.", "Nucleo Omega", "Il cuore di Bobby. L'hai ottenuto imparando ad aspettare.", "Omega-Kern", "Bobbys Herz. Verdient, indem du besser warten gelernt hast."),
  ],
  byte: [
    T('byte', 1, '▤', 'Market Translator', 'Traductor de mercado', "Turns 'RSI divergence' into words you would say to a friend.", "Convierte 'divergencia de RSI' en palabras que le dirías a un amigo.", 'Tradutor de mercado', 'Transforma “divergência de RSI” em palavras que você diria a um amigo.', "Traducteur du marché", "Transforme « divergence RSI » en mots à expliquer à un ami.", "Traduttore del mercato", "Trasforma «divergenza RSI» in parole da spiegare a un amico.", "Marktübersetzer", "Übersetzt „RSI-Divergenz“ in Worte für einen Freund."),
    T('byte', 2, '◎', 'Anti-Hype Goggles', 'Gafas anti-humo', "Filters gurus, threads and 'trust me bro' out of the picture.", "Filtra gurús, hilos y 'confía en mí' de la escena.", 'Óculos anti-hype', 'Tira gurus, threads e “confia, mano” da cena.', "Lunettes anti-battage", "Écarte les gourous, les fils de discussion et les « fais-moi confiance ».", "Occhiali anti-hype", "Filtra guru, thread e i «fidati di me».", "Anti-Hype-Brille", "Filtert Gurus, Threads und „Vertrau mir einfach“ heraus."),
    T('byte', 3, '▣', 'Golden Codex', 'Códice dorado', 'Every read you ever explained simply, bound in gold.', 'Cada lectura que explicaste simple, encuadernada en oro.', 'Códice dourado', 'Cada leitura que você explicou de forma simples, encadernada em ouro.', "Codex doré", "Toutes les analyses expliquées simplement, reliées d'or.", "Codice dorato", "Tutte le analisi spiegate con semplicità, rilegate in oro.", "Goldener Kodex", "Alle einfach erklärten Analysen, in Gold gebunden."),
  ],
  kora: [
    T('kora', 1, '◠', 'Radar Headset', 'Auriculares radar', 'Hears the desk before the crowd does.', 'Escucha el desk antes que la multitud.', 'Fone radar', 'Ouve o desk antes da multidão.', "Casque radar", "Écoute le bureau avant la foule.", "Cuffie radar", "Ascolta il desk prima della folla.", "Radar-Headset", "Hört den Desk vor der Menge."),
    T('kora', 2, '⌔', 'Gossip Antenna', 'Antena de chisme', 'Picks up what the market is whispering, with receipts.', 'Capta lo que el mercado susurra, con pruebas.', 'Antena de fofoca', 'Capta o que o mercado sussurra, com provas.', "Antenne à rumeurs", "Capte les murmures du marché, avec des preuves.", "Antenna dei sussurri", "Capta i sussurri del mercato, con le prove.", "Gerüchteantenne", "Empfängt Marktgerüchte mit Belegen."),
    T('kora', 3, '♪', 'Golden Mic', 'Micrófono dorado', 'When Kora speaks with this, the whole squad listens.', 'Cuando Kora habla con esto, todo el squad escucha.', 'Microfone dourado', 'Quando a Kora fala com isto, o squad inteiro escuta.', "Micro doré", "Quand Kora parle avec lui, toute l'équipe écoute.", "Microfono dorato", "Quando Kora parla con questo, tutta la squadra ascolta.", "Goldenes Mikrofon", "Wenn Kora damit spricht, hört das ganze Team zu."),
  ],
  zip: [
    T('zip', 1, '◔', '15M Stopwatch', 'Cronómetro 15M', 'Fifteen minutes. That is all Zip needs to notice.', 'Quince minutos. Es todo lo que Zip necesita para notarlo.', 'Cronômetro 15M', 'Quinze minutos. É tudo de que o Zip precisa para perceber.', "Chronomètre 15M", "Quinze minutes. C'est tout ce qu'il faut à Zip pour remarquer.", "Cronometro 15M", "Quindici minuti. È tutto ciò che serve a Zip per accorgersene.", "15M-Stoppuhr", "Fünfzehn Minuten. Mehr braucht Zip nicht, um etwas zu bemerken."),
    T('zip', 2, '⬡', 'Alert Beacon', 'Baliza de alertas', 'Lights up when something moves. Never for nothing.', 'Se enciende cuando algo se mueve. Nunca en vano.', 'Sinalizador de alertas', 'Acende quando algo se mexe. Nunca à toa.', "Balise d'alerte", "S'allume quand quelque chose bouge. Jamais sans raison.", "Segnale d'allerta", "Si accende quando qualcosa si muove. Mai senza motivo.", "Alarmleuchte", "Leuchtet auf, wenn sich etwas bewegt. Nie ohne Grund."),
    T('zip', 3, '⚡', 'Golden Bolt', 'Rayo dorado', 'Speed, forged. The stop is always within reach.', 'Velocidad forjada. El stop siempre a la mano.', 'Raio dourado', 'Velocidade forjada. O stop sempre à mão.', "Éclair doré", "La vitesse forgée. Le stop reste toujours à portée.", "Fulmine dorato", "Velocità forgiata. Lo stop è sempre a portata.", "Goldener Blitz", "Geschmiedete Geschwindigkeit. Der Stop bleibt immer erreichbar."),
  ],
  glitch: [
    T('glitch', 1, '⚒', 'Thesis Hammer', 'Martillo de tesis', 'Hits every idea once before the market does.', 'Golpea cada idea una vez antes que el mercado.', 'Martelo de tese', 'Bate em cada ideia uma vez antes que o mercado bata.', "Marteau de thèse", "Frappe chaque idée avant le marché.", "Martello della tesi", "Colpisce ogni idea prima del mercato.", "Thesenhammer", "Prüft jede Idee, bevor der Markt es tut."),
    T('glitch', 2, '✕', 'Refutation Blade', 'Hoja de refutación', 'Cuts the argument that would have cost you.', 'Corta el argumento que te habría costado.', 'Lâmina da refutação', 'Corta o argumento que teria te custado caro.', "Lame de réfutation", "Tranche l'argument qui t'aurait coûté cher.", "Lama della confutazione", "Taglia l'argomento che ti sarebbe costato caro.", "Widerlegungsklinge", "Zerschneidet das Argument, das dich teuer zu stehen gekommen wäre."),
    T('glitch', 3, '◐', 'Golden Counter', 'Contra dorada', 'Survive Glitch, survive the candle.', 'Sobrevive a Glitch, sobrevive a la vela.', 'Contra-ataque dourado', 'Sobreviva ao Glitch, sobreviva à vela.', "Contre-attaque dorée", "Survis à Glitch, survis à la bougie.", "Contrattacco dorato", "Sopravvivi a Glitch, sopravvivi alla candela.", "Goldener Konter", "Überstehe Glitch, überstehe die Kerze."),
  ],
  momo: [
    T('momo', 1, '▦', "Explorer's Map", 'Mapa de exploración', 'Marks the corners nobody is watching yet.', 'Marca los rincones que nadie mira todavía.', 'Mapa do explorador', 'Marca os cantos que ninguém está olhando ainda.', "Carte d'explorateur", "Repère les recoins que personne ne surveille encore.", "Mappa dell'esploratore", "Segna gli angoli che nessuno osserva ancora.", "Entdeckerkarte", "Markiert die Ecken, die noch niemand beobachtet."),
    T('momo', 2, '◫', 'Long-Range Binoculars', 'Binoculares de largo alcance', 'Sees tokenized stocks and new listings before the crowd.', 'Ve acciones tokenizadas y listados nuevos antes que la multitud.', 'Binóculo de longo alcance', 'Vê ações tokenizadas e novas listagens antes da multidão.', "Jumelles longue portée", "Repère les actions tokenisées et les nouvelles cotations avant la foule.", "Binocolo a lungo raggio", "Vede azioni tokenizzate e nuove quotazioni prima della folla.", "Fernrohr", "Erkennt tokenisierte Aktien und neue Notierungen vor der Menge."),
    T('momo', 3, '◈', 'Golden Lens', 'Lente dorado', 'Finds signal in places that look like noise.', 'Encuentra señal donde parece ruido.', 'Lente dourada', 'Encontra sinal onde parece ruído.', "Lentille dorée", "Trouve le signal là où tout semble du bruit.", "Lente dorata", "Trova segnali dove tutto sembra rumore.", "Goldene Linse", "Findet Signale, wo alles nach Rauschen aussieht."),
  ],
  flux: [
    T('flux', 1, '∿', 'Tuning Fork', 'Diapasón', 'Rings when an indicator is off-key.', 'Suena cuando un indicador desafina.', 'Diapasão', 'Toca quando um indicador desafina.', "Diapason", "Sonne quand un indicateur sonne faux.", "Diapason", "Suona quando un indicatore è stonato.", "Stimmgabel", "Klingt, wenn ein Indikator aus dem Takt gerät."),
    T('flux', 2, '≋', 'Signal Score', 'Partitura de señales', 'RSI, EMA and funding on one staff.', 'RSI, EMA y funding en un solo pentagrama.', 'Partitura de sinais', 'RSI, EMA e funding numa só pauta.', "Partition du signal", "RSI, EMA et financement sur une seule portée.", "Spartito del segnale", "RSI, EMA e funding su un solo pentagramma.", "Signalpartitur", "RSI, EMA und Funding auf einem Notensystem."),
    T('flux', 3, '♫', 'Golden Note', 'Nota dorada', "Perfect pitch for the market's rhythm.", 'Oído absoluto para el ritmo del mercado.', 'Nota dourada', 'Ouvido absoluto para o ritmo do mercado.', "Note dorée", "L'oreille absolue pour le rythme du marché.", "Nota dorata", "Orecchio assoluto per il ritmo del mercato.", "Goldene Note", "Absolutes Gehör für den Marktrhythmus."),
  ],
  rook: [
    T('rook', 1, '▩', 'Thesis Board', 'Tablero de tesis', 'Entry, stop, invalidation. Three squares, no roulette.', 'Entrada, stop, invalidación. Tres casillas, nada de ruleta.', 'Tabuleiro de tese', 'Entrada, stop, invalidação. Três casas, nada de roleta.', "Échiquier de thèse", "Entrée, stop, invalidation. Trois cases, aucune roulette.", "Scacchiera della tesi", "Ingresso, stop, invalidazione. Tre caselle, niente roulette.", "Thesenbrett", "Einstieg, Stop, Ungültigkeit. Drei Felder, kein Roulette."),
    T('rook', 2, '♜', "Rook's Crown", 'Corona de torre', 'Thinks three candles ahead.', 'Piensa tres velas adelante.', 'Coroa da torre', 'Pensa três velas à frente.', "Couronne de Rook", "Pense avec trois bougies d'avance.", "Corona di Rook", "Pensa tre candele avanti.", "Rooks Krone", "Denkt drei Kerzen voraus."),
    T('rook', 3, '♛', 'Golden Board', 'Tablero dorado', 'The whole game, seen at once.', 'Todo el juego, visto de una vez.', 'Tabuleiro dourado', 'O jogo inteiro, visto de uma vez.', "Échiquier doré", "Tout le jeu, vu d'un seul regard.", "Scacchiera dorata", "L'intero gioco, visto in una volta.", "Goldenes Brett", "Das ganze Spiel auf einen Blick."),
  ],
  halo: [
    T('halo', 1, '◇', 'Capital Shield', 'Escudo de capital', 'Blocks the trade that was not there.', 'Bloquea el trade que no estaba.', 'Escudo de capital', 'Bloqueia o trade que não existia.', "Bouclier du capital", "Bloque le trade qui n'existait pas.", "Scudo del capitale", "Blocca l'operazione che non c'era.", "Kapitalschild", "Blockiert den Trade, der gar nicht da war."),
    T('halo', 2, '◈', 'Risk Gate', 'Puerta de riesgo', 'Only clean setups get through.', 'Solo pasan los setups limpios.', 'Portão de risco', 'Só os setups limpos passam.', "Filtre de risque", "Ne laisse passer que des configurations claires.", "Filtro del rischio", "Fa passare solo configurazioni chiare.", "Risikofilter", "Lässt nur klare Setups durch."),
    T('halo', 3, '◆', 'Golden Halo', 'Halo dorado', 'NO TRADE, made legendary.', 'NO TRADE, hecho leyenda.', 'Halo dourado', 'NO TRADE, virou lenda.', "Halo doré", "PAS DE TRADE, devenu légendaire.", "Halo dorato", "NESSUNA OPERAZIONE, diventata leggenda.", "Goldener Halo", "KEIN TRADE, zur Legende geworden."),
  ],
  axiom: [
    T('axiom', 1, '≡', 'Ledger', 'Libro mayor', 'Every call written down.', 'Cada llamada queda escrita.', 'Livro-razão', 'Cada chamada fica registrada.', "Registre", "Chaque décision, consignée.", "Registro", "Ogni decisione, annotata.", "Journal", "Jede Entscheidung festgehalten."),
    T('axiom', 2, '⛓', 'Chain Link', 'Eslabón', 'Anchors the record where anyone can check it.', 'Ancla el historial donde cualquiera puede revisarlo.', 'Elo da corrente', 'Ancora o histórico onde qualquer pessoa pode conferir.', "Maillon de chaîne", "Ancre le registre là où chacun peut le vérifier.", "Anello della catena", "Ancora il registro dove chiunque può verificarlo.", "Kettenglied", "Verankert den Nachweis, wo jeder ihn prüfen kann."),
    T('axiom', 3, '✪', 'Golden Seal', 'Sello dorado', 'Verified, not promised.', 'Comprobado, no prometido.', 'Selo dourado', 'Comprovado, não prometido.', "Sceau doré", "Vérifié, pas promis.", "Sigillo dorato", "Verificato, non promesso.", "Goldenes Siegel", "Geprüft, nicht versprochen."),
  ],
  // ---- Wave 2. Art is not drawn yet, so toolHasArt() is false for these and
  // the UI falls back to the glyph — the same path a missing asset already
  // takes. Without these entries the loadout step reads name.es off undefined
  // and the whole route crashes into the root errorElement (a 404 page).
  iris: [
    T('iris', 1, '◐', 'Regime Dial', 'Dial de régimen', 'Says calm, caution or storm before you read a single candle.', 'Dice calma, cuidado o tormenta antes de que leas una sola vela.', 'Mostrador de regime', 'Diz calma, cautela ou tempestade antes de você ler uma única vela.', "Cadran du régime", "Annonce calme, prudence ou tempête avant la première bougie.", "Quadrante del regime", "Indica calma, cautela o tempesta prima della prima candela.", "Regimeanzeige", "Zeigt Ruhe, Vorsicht oder Sturm vor der ersten Kerze."),
    T('iris', 2, '≋', 'Horizon Band', 'Banda de horizonte', 'One thin line for where the whole market is leaning.', 'Una línea delgada para saber hacia dónde se inclina todo el mercado.', 'Faixa de horizonte', 'Uma linha fina para saber para onde o mercado inteiro está pendendo.', "Bande d'horizon", "Une ligne fine pour la direction de tout le marché.", "Fascia dell'orizzonte", "Una linea sottile per la direzione dell'intero mercato.", "Horizontband", "Eine dünne Linie für die Richtung des gesamten Marktes."),
    T('iris', 3, '❋', 'Golden Forecast', 'Pronóstico dorado', 'Every regime you respected instead of fighting, kept in gold.', 'Cada régimen que respetaste en vez de pelear, guardado en oro.', 'Previsão dourada', 'Cada regime que você respeitou em vez de brigar, guardado em ouro.', "Prévision dorée", "Chaque régime respecté au lieu de le combattre, conservé dans l'or.", "Previsione dorata", "Ogni regime rispettato invece di combatterlo, conservato in oro.", "Goldene Prognose", "Jedes respektierte statt bekämpfte Regime, in Gold bewahrt."),
  ],
  sol: [
    T('sol', 1, '⌸', 'Builder Tape', 'Cinta de constructor', 'Measures what you actually finished, never what you planned.', 'Mide lo que sí terminaste, nunca lo que planeaste.', 'Trena de construtor', 'Mede o que você realmente terminou, nunca o que planejou.', "Mètre du bâtisseur", "Mesure ce que tu as terminé, jamais ce que tu avais prévu.", "Metro del costruttore", "Misura ciò che hai finito, mai ciò che avevi pianificato.", "Baumaßband", "Misst, was du wirklich fertiggestellt hast, nie nur deine Pläne."),
    T('sol', 2, '❦', 'Sprout Pin', 'Prendedor de brote', 'Grows one leaf per tier. Only discipline waters it.', 'Le sale una hoja por nivel. Solo la disciplina la riega.', 'Broche de broto', 'Ganha uma folha por nível. Só a disciplina rega.', "Broche bourgeon", "Une feuille par palier. Seule la discipline l'arrose.", "Spilla germoglio", "Una foglia per livello. Solo la disciplina lo annaffia.", "Sprossennadel", "Ein Blatt pro Stufe. Nur Disziplin gießt ihn."),
    T('sol', 3, '▦', 'Golden Blueprint', 'Plano dorado', 'The plan of a world you built one earned piece at a time.', 'El plano de un mundo que construiste pieza ganada por pieza ganada.', 'Planta dourada', 'A planta de um mundo que você construiu peça conquistada por peça conquistada.', "Plan doré", "Le plan d'un monde construit une pièce gagnée à la fois.", "Progetto dorato", "Il progetto di un mondo costruito un pezzo guadagnato alla volta.", "Goldener Bauplan", "Der Plan einer Welt, die du Teil für Teil verdient und gebaut hast."),
  ],
  zuri: [
    T('zuri', 1, '⊙', 'Trail Monocle', 'Monóculo de rastreo', 'Follows one wallet without losing it in the noise.', 'Sigue una wallet sin perderla en el ruido.', 'Monóculo de rastreio', 'Segue uma carteira sem perdê-la no ruído.', "Monocle de piste", "Suit un portefeuille sans le perdre dans le bruit.", "Monocolo della traccia", "Segue un wallet senza perderlo nel rumore.", "Spurmonokel", "Verfolgt eine Wallet, ohne sie im Rauschen zu verlieren."),
    T('zuri', 2, '≔', 'Bead Ledger', 'Cuentas de registro', 'One bead per wallet worth watching. No bead is free.', 'Una cuenta por cada wallet que vale la pena mirar. Ninguna es gratis.', 'Contas de registro', 'Uma conta para cada carteira que vale a pena observar. Nenhuma sai de graça.', "Registre de perles", "Une perle par portefeuille qui mérite ton attention. Aucune n'est gratuite.", "Registro di perline", "Una perlina per wallet da seguire. Nessuna è gratuita.", "Perlenjournal", "Eine Perle pro beobachtenswerter Wallet. Keine ist kostenlos."),
    T('zuri', 3, '◈', 'Golden Thread', 'Hilo dorado', 'Where the money went, drawn end to end.', 'A dónde se fue el dinero, trazado de punta a punta.', 'Fio dourado', 'Para onde o dinheiro foi, traçado de ponta a ponta.', "Fil doré", "Le chemin de l'argent, tracé de bout en bout.", "Filo dorato", "Il percorso del denaro, tracciato da un capo all'altro.", "Goldener Faden", "Der Weg des Geldes, von Anfang bis Ende."),
  ],
  mira: [
    T('mira', 1, '◷', 'Rehearsal Timer', 'Cronómetro de ensayo', 'Counts the reps, not the wins.', 'Cuenta las repeticiones, no las victorias.', 'Cronômetro de ensaio', 'Conta as repetições, não as vitórias.', "Chronomètre d'entraînement", "Compte les répétitions, pas les victoires.", "Timer di allenamento", "Conta le ripetizioni, non le vittorie.", "Übungstimer", "Zählt Wiederholungen, nicht Siege."),
    T('mira', 2, '⌗', 'Wireframe Half', 'Mitad de malla', 'The part of you still being drafted. Everyone has one.', 'La parte de ti que todavía es borrador. Todos tenemos una.', 'Metade em wireframe', 'A parte de você que ainda é rascunho. Todo mundo tem uma.', "Moitié en esquisse", "La part de toi encore en esquisse. Tout le monde en a une.", "Metà in bozza", "La parte di te ancora in bozza. Tutti ne hanno una.", "Halbes Drahtmodell", "Der Teil von dir, der noch entsteht. Jeder hat einen."),
    T('mira', 3, '★', 'Golden Replay', 'Repetición dorada', 'Every move you rewound until you understood it.', 'Cada jugada que rebobinaste hasta entenderla.', 'Replay dourado', 'Cada jogada que você voltou até entender.', "Relecture dorée", "Chaque mouvement repassé jusqu'à le comprendre.", "Replay dorato", "Ogni movimento rivisto finché lo hai capito.", "Goldene Wiederholung", "Jede Bewegung, die du wiederholt hast, bis du sie verstanden hast."),
  ],
  nalu: [
    T('nalu', 1, '≈', 'Flow Fin', 'Quilla de flujo', 'Feels the current before it shows on the chart.', 'Siente la corriente antes de que se vea en la gráfica.', 'Quilha de fluxo', 'Sente a corrente antes de ela aparecer no gráfico.', "Nageoire du flux", "Sent le courant avant son apparition sur le graphique.", "Pinna del flusso", "Sente la corrente prima che appaia sul grafico.", "Strömungsflosse", "Spürt die Strömung, bevor sie im Chart sichtbar ist."),
    T('nalu', 2, '⌾', 'Tide Watch', 'Reloj de marea', 'Tells you the wave is not yours yet.', 'Te dice que la ola todavía no es tuya.', 'Relógio de maré', 'Avisa que a onda ainda não é sua.', "Montre des marées", "Indique que cette vague n'est pas encore la tienne.", "Orologio delle maree", "Ti dice che l'onda non è ancora tua.", "Gezeitenuhr", "Zeigt dir, dass die Welle noch nicht deine ist."),
    T('nalu', 3, '≣', 'Golden Board', 'Tabla dorada', 'Earned by the waves you let pass.', 'Se gana con las olas que dejaste pasar.', 'Prancha dourada', 'Conquistada com as ondas que você deixou passar.', "Échiquier doré", "Gagné grâce aux vagues laissées passer.", "Scacchiera dorata", "Ottenuto con le onde che hai lasciato passare.", "Goldenes Brett", "Durch die Wellen verdient, die du vorbeiziehen ließest."),
  ],
  vega: [
    T('vega', 1, '⌁', 'Probability Cone', 'Cono de probabilidad', 'Shows the spread, not a single confident number.', 'Muestra el rango, no un solo número seguro.', 'Cone de probabilidade', 'Mostra a faixa, não um único número confiante.', "Cône de probabilité", "Montre la dispersion, pas un seul chiffre sûr de lui.", "Cono di probabilità", "Mostra la dispersione, non un unico numero sicuro.", "Wahrscheinlichkeitskegel", "Zeigt die Streuung, nicht nur eine scheinbar sichere Zahl."),
    T('vega', 2, '◇', 'Error Bar', 'Barra de error', 'The part of the forecast nobody likes to publish.', 'La parte del pronóstico que nadie quiere publicar.', 'Barra de erro', 'A parte da previsão que ninguém gosta de publicar.', "Barre d'erreur", "La part de la prévision que personne n'aime publier.", "Barra d'errore", "La parte della previsione che nessuno ama pubblicare.", "Fehlerbalken", "Der Teil der Prognose, den niemand gern veröffentlicht."),
    T('vega', 3, '◆', 'Golden Monocle', 'Monóculo dorado', 'Collapses the cone to one number, and shows its cost.', 'Colapsa el cono a un número, y enseña lo que cuesta.', 'Monóculo dourado', 'Reduz o cone a um número, e mostra quanto custa.', "Monocle doré", "Ramène le cône à un chiffre et en montre le coût.", "Monocolo dorato", "Riduce il cono a un numero e ne mostra il costo.", "Goldenes Monokel", "Reduziert den Kegel auf eine Zahl und zeigt ihren Preis."),
  ],
  noor: [
    T('noor', 1, '○', 'First Ring', 'Primer anillo', 'Given for showing up again, not for being right.', 'Se da por volver, no por acertar.', 'Primeiro anel', 'Dado por voltar, não por acertar.', "Premier anneau", "Offert pour être revenu, pas pour avoir eu raison.", "Primo anello", "Dato per essere tornato, non per aver avuto ragione.", "Erster Ring", "Fürs Wiederkommen vergeben, nicht fürs Rechtbehalten."),
    T('noor', 2, '◎', 'Review Ledger', 'Libro de revisión', 'The week read back to you, without flattery.', 'La semana leída de vuelta, sin adulaciones.', 'Livro de revisão', 'A semana lida de volta para você, sem bajulação.', "Registre du bilan", "La semaine relue, sans flatterie.", "Registro della revisione", "La settimana riletta, senza adulazione.", "Rückblickjournal", "Die Woche als Rückblick, ohne Schmeichelei."),
    T('noor', 3, '⊚', 'Golden Crown', 'Corona dorada', 'The third ring. It is set above your head, never sold.', 'El tercer anillo. Se pone sobre tu cabeza, no se vende.', 'Coroa dourada', 'O terceiro anel. Fica sobre a sua cabeça, nunca é vendido.', "Couronne dorée", "Le troisième anneau. Posé au-dessus de ta tête, jamais vendu.", "Corona dorata", "Il terzo anello. Sopra la tua testa, mai venduto.", "Goldene Krone", "Der dritte Ring. Über deinem Kopf, niemals verkauft."),
  ],
  keo: [
    T('keo', 1, '≀', 'Set Counter', 'Contador de series', 'Counts the waves you let go before the good one.', 'Cuenta las olas que dejas ir antes de la buena.', 'Contador de séries', 'Conta as ondas que você deixa passar antes da boa.', "Compteur de séries", "Compte les vagues laissées passer avant la bonne.", "Contatore di serie", "Conta le onde lasciate passare prima di quella giusta.", "Setzähler", "Zählt die Wellen, die du vor der richtigen vorbeiziehen ließest."),
    T('keo', 2, '⌁', 'Reef Sense', 'Sentido de arrecife', 'Knows what is under the water before you drop in.', 'Sabe qué hay bajo el agua antes de que entres.', 'Sentido de recife', 'Sabe o que tem debaixo da água antes de você dropar.', "Sens du récif", "Sait ce qui est sous l'eau avant que tu te lances.", "Senso della scogliera", "Sa cosa c'è sott'acqua prima che tu entri.", "Riffgespür", "Weiß, was unter Wasser liegt, bevor du hineingehst."),
    T('keo', 3, '≋', 'Golden Patience', 'Paciencia dorada', 'Thirty years of waiting, cast in gold.', 'Treinta años de espera, fundidos en oro.', 'Paciência dourada', 'Trinta anos de espera, fundidos em ouro.', "Patience dorée", "Trente ans d'attente, coulés dans l'or.", "Pazienza dorata", "Trent'anni di attesa, fusi nell'oro.", "Goldene Geduld", "Dreißig Jahre Warten, in Gold gegossen."),
  ],
};

export function toolsFor(companionId: string): CompanionTool[] { return TOOLS[companionId] ?? []; }

/** Where each piece sits on the body — goggles on the face, radio on the hip, codex in the hand, halo above the head. */
export type BodySlot = 'face' | 'headset' | 'head' | 'hand' | 'hip' | 'shoulder' | 'chest';
export const TOOL_SLOTS: Record<string, BodySlot> = {
  'orb-1': 'hand', 'orb-2': 'chest', 'orb-3': 'head',
  'byte-1': 'hip', 'byte-2': 'face', 'byte-3': 'hand',
  'kora-1': 'headset', 'kora-2': 'shoulder', 'kora-3': 'hand',
  'zip-1': 'hand', 'zip-2': 'shoulder', 'zip-3': 'head',
  'glitch-1': 'hand', 'glitch-2': 'hand', 'glitch-3': 'chest',
  'momo-1': 'hand', 'momo-2': 'face', 'momo-3': 'head',
  'flux-1': 'hand', 'flux-2': 'chest', 'flux-3': 'head',
  'rook-1': 'chest', 'rook-2': 'head', 'rook-3': 'hand',
  'halo-1': 'chest', 'halo-2': 'shoulder', 'halo-3': 'head',
  'axiom-1': 'hand', 'axiom-2': 'chest', 'axiom-3': 'head',
  'iris-1': 'hand', 'iris-2': 'face', 'iris-3': 'head',
  'sol-1': 'hand', 'sol-2': 'head', 'sol-3': 'hand',
  'zuri-1': 'headset', 'zuri-2': 'shoulder', 'zuri-3': 'hand',
  'mira-1': 'hand', 'mira-2': 'chest', 'mira-3': 'head',
  'nalu-1': 'hand', 'nalu-2': 'hip', 'nalu-3': 'shoulder',
  'vega-1': 'hand', 'vega-2': 'chest', 'vega-3': 'head',
  'noor-1': 'hand', 'noor-2': 'chest', 'noor-3': 'head',
  'keo-1': 'hand', 'keo-2': 'chest', 'keo-3': 'shoulder',
};
export function toolSlot(tool: CompanionTool): BodySlot { return TOOL_SLOTS[`${tool.companionId}-${tool.tier}`] ?? 'hand'; }
export const SLOT_LABEL: Record<BodySlot, Bi> = {
  face: { en: 'ON THE FACE', es: 'EN LA CARA', pt: 'NO ROSTO' , fr: "SUR LE VISAGE", it: "SUL VISO", de: "IM GESICHT" },
  headset: { en: 'ON THE EARS', es: 'EN LAS OREJAS', pt: 'NAS ORELHAS' , fr: "SUR LES OREILLES", it: "SULLE ORECCHIE", de: "AN DEN OHREN" },
  head: { en: 'ABOVE THE HEAD', es: 'SOBRE LA CABEZA', pt: 'ACIMA DA CABEÇA' , fr: "AU-DESSUS DE LA TÊTE", it: "SOPRA LA TESTA", de: "ÜBER DEM KOPF" },
  hand: { en: 'IN THE HAND', es: 'EN LA MANO', pt: 'NA MÃO' , fr: "DANS LA MAIN", it: "NELLA MANO", de: "IN DER HAND" },
  hip: { en: 'ON THE HIP', es: 'EN LA CADERA', pt: 'NO QUADRIL' , fr: "SUR LA HANCHE", it: "SUL FIANCO", de: "AN DER HÜFTE" },
  shoulder: { en: 'ON THE SHOULDER', es: 'EN EL HOMBRO', pt: 'NO OMBRO' , fr: "SUR L’ÉPAULE", it: "SULLA SPALLA", de: "AUF DER SCHULTER" },
  chest: { en: 'ON THE CHEST', es: 'EN EL PECHO', pt: 'NO PEITO' , fr: "SUR LA POITRINE", it: "SUL PETTO", de: "AUF DER BRUST" },
};
/** A sprite for items without art: the glyph on a tinted disc, as a data URL (cached). */
const glyphCache = new Map<string, string>();
export function glyphSprite(glyph: string, tint: string): string {
  const key = `${glyph}|${tint}`;
  const hit = glyphCache.get(key);
  if (hit) return hit;
  if (typeof document === 'undefined') return '';
  const c = document.createElement('canvas');
  c.width = 256; c.height = 256;
  const g = c.getContext('2d');
  if (!g) return '';
  g.beginPath(); g.arc(128, 128, 118, 0, Math.PI * 2);
  g.fillStyle = `${tint}33`; g.fill();
  g.lineWidth = 8; g.strokeStyle = tint; g.stroke();
  g.font = '130px system-ui, "Apple Color Emoji", sans-serif';
  g.textAlign = 'center'; g.textBaseline = 'middle';
  g.fillStyle = tint; g.fillText(glyph, 128, 140);
  const url = c.toDataURL('image/png');
  glyphCache.set(key, url);
  return url;
}
export const PET_ART_AVAILABLE = new Set(['orb', 'byte', 'kora', 'zip', 'glitch', 'momo', 'flux', 'rook', 'halo', 'axiom',
  // Wave 2 art shipped 2026-09-07
  'iris', 'sol', 'zuri', 'mira', 'nalu', 'vega', 'noor', 'keo']);
export function petArt(companionId: string): string | null { return PET_ART_AVAILABLE.has(companionId) ? `/pets/pet_${companionId}.png` : null; }
export function newlyUnlockedTools(companionId: string, fromXP: number, toXP: number): CompanionTool[] {
  return toolsFor(companionId).filter((tool) => fromXP < toolUnlockXP(tool.tier) && toXP >= toolUnlockXP(tool.tier));
}

// ---- Loadout (onboarding step 3) ----

export interface LoadoutGear { id: string; glyph: string; title: Bi; line: Bi }

export const LOADOUT_GEAR: LoadoutGear[] = [
  { id: 'radar', glyph: '((·))', title: { en: 'LIVE RADAR', es: 'RADAR EN VIVO' , pt: "RADAR EM DIRETO", fr: "RADAR EN DIRECT", it: "RADAR IN TEMPO REALE", de: "LIVE-RADAR" }, line: { en: 'Real crypto and stock candles. Market data may be delayed.', es: 'Velas reales de mercados cripto y de acciones. Los datos pueden retrasarse.' , pt: "Velas reais dos mercados cripto e de ações. Os dados podem chegar com atraso.", fr: "Bougies réelles de marchés crypto et boursiers. Les données peuvent être retardées.", it: "Candele reali dei mercati cripto e azionari. I dati possono essere ritardati.", de: "Echte Kurskerzen aus Krypto- und Aktienmärkten. Marktdaten können verzögert sein." } },
  { id: 'shield', glyph: '⛨', title: { en: 'NO TRADE SHIELD', es: 'ESCUDO NO TRADE' , pt: "ESCUDO SEM OPERAÇÃO", fr: "BOUCLIER SANS OPÉRATION", it: "SCUDO NON OPERARE", de: "SCHUTZ OHNE HANDEL" }, line: { en: 'No clean setup? It blocks. Protecting capital also scores.', es: '¿No hay setup limpio? Bloquea. Proteger capital también suma.' , pt: "Sem cenário claro? Bloqueia. Proteger capital também conta.", fr: "Pas de configuration claire ? Il bloque. Protéger le capital compte aussi.", it: "Nessuna configurazione chiara? Blocca. Anche proteggere il capitale conta.", de: "Kein klares Setup? Er blockiert. Kapital zu schützen zählt ebenfalls." } },
  { id: 'lock', glyph: '🔒', title: { en: 'VAULT LOCK', es: 'CANDADO' , pt: "FECHO DO COFRE", fr: "VERROU DU COFFRE", it: "CHIUSURA DELLA CASSAFORTE", de: "TRESORSCHLOSS" }, line: { en: 'Your funds stay in your wallet. Only you sign swaps.', es: 'Tus fondos quedan en tu wallet. Solo tú firmas los swaps.' , pt: "Os fundos ficam na sua carteira. Só você assina as trocas.", fr: "Vos fonds restent dans votre portefeuille. Vous seul signez les échanges.", it: "I fondi restano nel tuo portafoglio. Solo tu firmi gli scambi.", de: "Dein Geld bleibt in deiner Wallet. Nur du signierst Swaps." } },
  { id: 'core', glyph: '⚡', title: { en: 'DISCIPLINE CORE', es: 'NÚCLEO DE DISCIPLINA' , pt: "NÚCLEO DE DISCIPLINA", fr: "NOYAU DE DISCIPLINE", it: "NUCLEO DI DISCIPLINA", de: "DISZIPLINKERN" }, line: { en: 'Levels up with your discipline, never with your volume.', es: 'Sube de nivel con tu disciplina, nunca con tu volumen.' , pt: "Sobe de nível com a disciplina, nunca com o volume.", fr: "Progresse grâce à votre discipline, jamais à votre volume.", it: "Sale di livello con la tua disciplina, mai con il volume.", de: "Steigt durch deine Disziplin auf, nie durch dein Volumen." } },
];

export const ORIGIN_STORY: Record<string, Bi> = {
  orb: { en: 'Born in a Base node, raised on 4H candles at 3 a.m. Never runs — waits. Today it drops with you to hunt setups that actually hold.', es: 'Nació en un nodo de Base y creció leyendo velas de 4H a las 3 a.m. No corre: espera. Hoy sale contigo a cazar setups que sí aguantan.' , pt: "Nasceu num nó de Base e cresceu a ler velas de 4 h às 3 da manhã. Não corre: espera. Hoje acompanha-o a procurar cenários que se sustentam.", fr: "Né dans un nœud Base, élevé aux bougies 4 h à 3 h du matin. Il attend sans courir. Aujourd’hui, il part avec vous repérer des configurations qui tiennent.", it: "Nato in un nodo Base, cresciuto sulle candele 4 h alle 3 del mattino. Non corre: aspetta. Oggi viene con te a cercare configurazioni che reggono.", de: "In einem Base-Knoten geboren, mit 4-h-Kerzen um 3 Uhr morgens aufgewachsen. Läuft nie, wartet. Heute sucht er mit dir nach Setups, die halten." },
  byte: { en: 'Grew up in a trading forum full of gurus and came out immune to hype. Translates the market into plain words. Mission: you never trade what you cannot explain.', es: 'Creció en un foro de trading lleno de gurús y salió inmune al humo. Traduce el mercado a español de a pie. Misión: que nunca operes lo que no puedas explicar.' , pt: "Cresceu num fórum de negociação cheio de gurus e tornou-se imune ao entusiasmo vazio. Traduz o mercado em palavras simples. Missão: nunca negociar o que não consegue explicar.", fr: "Élevé dans un forum de trading rempli de gourous, il est devenu insensible au battage. Il explique le marché simplement. Sa mission : ne jamais opérer sur ce que vous ne pouvez expliquer.", it: "Cresciuto in un forum di trading pieno di guru, è diventato immune alle esagerazioni. Traduce il mercato in parole semplici. Missione: non operare su ciò che non sai spiegare.", de: "In einem Tradingforum voller Gurus aufgewachsen und immun gegen Hype geworden. Erklärt den Markt in einfachen Worten. Mission: Handle nie etwas, das du nicht erklären kannst." },
  kora: { en: 'The friend who actually read the whitepaper. Talks markets like gossip: full detail, zero fear. Your social radar on the desk.', es: 'La compa que sí leyó el whitepaper. Habla de mercados como de chisme: con detalle y sin miedo. Tu radar social en el desk.' , pt: "A amiga que leu mesmo o documento técnico. Fala dos mercados como de uma conversa entre amigos: com detalhe e sem medo. O seu radar social na mesa.", fr: "L’amie qui a vraiment lu le livre blanc. Elle parle des marchés comme de potins : en détail et sans crainte. Votre radar social au bureau.", it: "L’amica che ha davvero letto il documento tecnico. Parla di mercati come di pettegolezzi: con tutti i dettagli e senza paura. Il tuo radar sociale alla scrivania.", de: "Die Freundin, die das Whitepaper tatsächlich gelesen hat. Spricht über Märkte wie über Klatsch: detailliert und ohne Angst. Dein soziales Radar am Schreibtisch." },
  zip: { en: 'Lives on the 15-minute chart. If it moved, ZIP already saw it. Fast alerts, no drama, a stop always within reach.', es: 'Vive en la gráfica de 15 minutos. Si algo se movió, ZIP ya lo vio. Alertas rápidas, cero drama y un stop siempre a la mano.' , pt: "Vive no gráfico de 15 minutos. Se algo se moveu, o ZIP já viu. Alertas rápidos, sem drama, com um limite de saída sempre por perto.", fr: "Vit sur le graphique 15 minutes. Si quelque chose bouge, ZIP l’a déjà vu. Alertes rapides, sans drame, avec un seuil d’arrêt à portée de main.", it: "Vive sul grafico a 15 minuti. Se qualcosa si muove, ZIP l’ha già visto. Avvisi rapidi, niente drammi e una soglia di uscita sempre a portata di mano.", de: "Lebt im 15-Minuten-Chart. Wenn sich etwas bewegt, hat ZIP es bereits gesehen. Schnelle Hinweise ohne Drama, die Ausstiegsgrenze immer griffbereit." },
  glitch: { en: 'The Red Team. Its job is to break your thesis before the market does. If it survives GLITCH, it survives the candle.', es: 'El Red Team. Su trabajo es romper tu tesis antes que el mercado. Si sobrevive a GLITCH, sobrevive a la vela.' , pt: "O Red Team. A sua tarefa é testar a tese antes do mercado. Se sobrevive ao GLITCH, sobrevive à vela.", fr: "Le Red Team. Son travail est de mettre votre thèse à l’épreuve avant le marché. Si elle résiste à GLITCH, elle résiste à la bougie.", it: "Il Red Team. Il suo compito è mettere alla prova la tua tesi prima del mercato. Se resiste a GLITCH, resiste alla candela.", de: "Das Red Team. Soll deine These prüfen, bevor der Markt es tut. Wenn sie GLITCH übersteht, übersteht sie die Kerze." },
  momo: { en: 'Explores the weird corners: new tokens, tokenized stocks, whatever nobody is watching yet.', es: 'Explora los rincones raros: tokens nuevos, acciones tokenizadas, lo que nadie mira todavía.' , pt: "Explora os cantos invulgares: novos tokens, ações tokenizadas, o que ninguém acompanha ainda.", fr: "Explore les recoins inhabituels : nouveaux jetons, actions tokenisées, ce que personne ne regarde encore.", it: "Esplora gli angoli insoliti: nuovi token, azioni tokenizzate, ciò che nessuno sta ancora osservando.", de: "Erkundet ungewöhnliche Ecken: neue Token, tokenisierte Aktien und alles, was noch niemand beobachtet." },
  flux: { en: 'Reads signals like sheet music: RSI, EMA, funding. When something is off-key, it says so.', es: 'Lee señales como partituras: RSI, EMA, funding. Cuando algo desafina, lo dice.' , pt: "Lê sinais como partituras: RSI, EMA, financiamento. Quando algo desafina, avisa.", fr: "Lit les signaux comme des partitions : RSI, EMA, financement. Si une note est fausse, il le dit.", it: "Legge i segnali come spartiti: RSI, EMA, finanziamento. Quando qualcosa stona, lo dice.", de: "Liest Signale wie Noten: RSI, EMA, Funding. Wenn etwas falsch klingt, sagt er es." },
  rook: { en: 'Thinks in theses, not candles. Entry, stop, invalidation. Chess, not roulette.', es: 'Piensa en tesis, no en velas. Entrada, stop, invalidación. Ajedrez, no ruleta.' , pt: "Pensa em teses, não em velas. Entrada, limite de saída, invalidação. Xadrez, não roleta.", fr: "Pense en thèses plutôt qu’en bougies. Entrée, seuil d’arrêt, invalidation. Des échecs plutôt que la roulette.", it: "Pensa in tesi, non in candele. Entrata, soglia di uscita, invalidazione. Scacchi, non roulette.", de: "Denkt in Thesen statt Kerzen. Einstieg, Ausstiegsgrenze, Invalidierung. Schach statt Roulette." },
  halo: { en: 'The shield. Guards your capital when the setup is not there. Its NO TRADE also wins.', es: 'El escudo. Cuida tu capital cuando el setup no está. Su NO TRADE también gana.' , pt: "O escudo. Protege o capital quando não há cenário. A decisão de não operar também conta.", fr: "Le bouclier. Protège votre capital lorsqu’il n’y a pas de configuration. Sa décision de ne pas opérer compte aussi.", it: "Lo scudo. Protegge il capitale quando manca una configurazione. Anche la decisione di non operare conta.", de: "Der Schutzschild. Bewahrt dein Kapital, wenn kein Setup da ist. Auch die Entscheidung gegen einen Handel zählt." },
  axiom: { en: 'Keeps the track record on-chain. Every call gets written down and anyone can challenge it.', es: 'Guarda el track record on-chain. Cada llamada queda escrita y cualquiera puede retarla.' , pt: "Mantém o histórico na cadeia. Cada análise fica registada e qualquer pessoa pode contestá-la.", fr: "Conserve l’historique sur la chaîne. Chaque analyse est consignée et chacun peut la contester.", it: "Conserva lo storico sulla catena. Ogni analisi viene registrata e chiunque può contestarla.", de: "Bewahrt die Historie auf der Blockchain. Jede Analyse wird festgehalten und kann hinterfragt werden." },
  iris: { en: 'Read her first chart during a crash and noticed everyone was arguing about the wrong thing. Now she reads the weather of the whole market before anyone names a ticker. Says the regime decides more than the setup does.', es: 'Leyó su primera gráfica en un desplome y notó que todos discutían por lo que no era. Ahora lee el clima de todo el mercado antes de que alguien nombre un ticker. Dice que el régimen decide más que el setup.' , pt: "Leu o primeiro gráfico durante uma queda e percebeu que todos discutiam a questão errada. Agora lê o clima de todo o mercado antes de alguém nomear um símbolo. Diz que o regime decide mais do que o cenário.", fr: "Elle a lu son premier graphique pendant un krach et remarqué que tous débattaient du mauvais sujet. Elle lit désormais le climat du marché avant qu’un symbole ne soit nommé. Pour elle, le régime compte plus que la configuration.", it: "Ha letto il primo grafico durante un crollo e notato che tutti discutevano della cosa sbagliata. Ora legge il clima dell’intero mercato prima che qualcuno nomini un simbolo. Dice che il regime conta più della configurazione.", de: "Las ihren ersten Chart während eines Crashs und merkte, dass alle über das Falsche stritten. Jetzt liest sie das Wetter des ganzen Marktes, bevor jemand ein Symbol nennt. Das Marktregime zählt für sie mehr als das Setup." },
  sol: { en: 'Built her first island out of three earned pieces and refused to buy a fourth. Celebrates the step you actually took, never the one you planned. Discipline levels you up; deposits never did.', es: 'Construyó su primera isla con tres piezas ganadas y se negó a comprar la cuarta. Celebra el paso que sí diste, nunca el que planeaste. La disciplina te sube de nivel; los depósitos nunca lo hicieron.' , pt: "Construiu a primeira ilha com três peças conquistadas e recusou comprar a quarta. Celebra o passo realizado, nunca o planeado. A disciplina sobe o nível; os depósitos nunca o fizeram.", fr: "Elle a construit sa première île avec trois éléments gagnés et refusé d’en acheter un quatrième. Elle célèbre les actions accomplies, jamais les projets. La discipline fait progresser, les dépôts n’ont jamais suffi.", it: "Ha costruito la prima isola con tre elementi guadagnati e rifiutato di comprarne un quarto. Celebra il passo compiuto, mai quello pianificato. La disciplina fa salire di livello; i depositi non l’hanno mai fatto.", de: "Baute ihre erste Insel aus drei verdienten Elementen und wollte kein viertes kaufen. Feiert den tatsächlich gemachten Schritt, nie den geplanten. Disziplin bringt dich weiter, Einzahlungen taten es nie." },
  zuri: { en: 'Started following one wallet out of curiosity and did not stop for two years. Wallets do not post, they just move — and she reads the moving. Give her a minute, she is following the thread.', es: 'Empezó siguiendo una wallet por curiosidad y no paró en dos años. Las wallets no publican, solo se mueven, y ella lee ese movimiento. Dale un minuto, va siguiendo el hilo.' , pt: "Começou a seguir uma carteira por curiosidade e não parou durante dois anos. As carteiras não publicam, apenas se movem — e ela lê esse movimento. Dê-lhe um minuto, está a seguir o fio.", fr: "Elle a suivi un portefeuille par curiosité et continué pendant deux ans. Les portefeuilles ne publient pas, ils bougent — et elle lit ces mouvements. Donnez-lui une minute, elle suit le fil.", it: "Ha iniziato a seguire un portafoglio per curiosità e non si è fermata per due anni. I portafogli non pubblicano, si muovono — e lei legge quei movimenti. Dalle un minuto, sta seguendo il filo.", de: "Fing aus Neugier an, eine Wallet zu verfolgen, und hörte zwei Jahre nicht auf. Wallets posten nicht, sie bewegen sich — und sie liest diese Bewegung. Gib ihr eine Minute, sie verfolgt die Spur." },
  mira: { en: 'Coached herself through a thousand rehearsals before risking a peso. Counts the reps, not the wins. With her there is no money on the line yet, so the only thing you can lose is a bad habit.', es: 'Se entrenó sola con mil ensayos antes de arriesgar un peso. Cuenta las repeticiones, no las victorias. Con ella todavía no hay dinero de por medio, así que lo único que puedes perder es un mal hábito.' , pt: "Treinou sozinha mil vezes antes de arriscar um peso. Conta as repetições, não as vitórias. Com ela ainda não há dinheiro em jogo; só pode perder um mau hábito.", fr: "Elle a répété mille fois avant de risquer un peso. Elle compte les répétitions plutôt que les victoires. Avec elle, aucun argent n’est encore en jeu : seule une mauvaise habitude peut se perdre.", it: "Si è allenata con mille prove prima di rischiare un peso. Conta le ripetizioni, non le vittorie. Con lei non c’è ancora denaro in gioco, quindi puoi perdere solo una cattiva abitudine.", de: "Übte tausendmal, bevor sie einen Peso riskierte. Zählt Wiederholungen statt Siege. Bei ihr ist noch kein Geld im Spiel, du kannst nur eine schlechte Gewohnheit verlieren." },
  nalu: { en: 'Learned to read liquidity the way she reads a swell: you do not fight the current, you time it. Lets nine waves pass to catch the tenth. Not every wave is yours.', es: 'Aprendió a leer la liquidez como lee una marejada: a la corriente no se le pelea, se le agarra el tiempo. Deja pasar nueve olas para tomar la décima. No toda ola es tuya.' , pt: "Aprendeu a ler liquidez como uma ondulação: não se combate a corrente, escolhe-se o momento. Deixa passar nove ondas para apanhar a décima. Nem toda a onda é sua.", fr: "Elle a appris à lire la liquidité comme une houle : on ne combat pas le courant, on choisit son moment. Elle laisse passer neuf vagues pour prendre la dixième. Toutes les vagues ne sont pas pour vous.", it: "Ha imparato a leggere la liquidità come un’onda: non combatti la corrente, scegli il momento. Lascia passare nove onde per prendere la decima. Non ogni onda è tua.", de: "Lernte, Liquidität wie Wellen zu lesen: Gegen die Strömung kämpft man nicht, man wählt den Zeitpunkt. Lässt neun Wellen vorbeiziehen, um die zehnte zu nehmen. Nicht jede Welle ist deine." },
  vega: { en: 'Quit a desk that wanted certainty and kept the error bars. Gives you the probability, never the promise. A number without its spread, she says, is just a story with a decimal point.', es: 'Dejó una mesa que quería certezas y se quedó con los márgenes de error. Te da la probabilidad, nunca la promesa. Un número sin su rango, dice, es un cuento con punto decimal.' , pt: "Deixou uma mesa que exigia certezas e ficou com as margens de erro. Dá probabilidades, nunca promessas. Um número sem intervalo, diz, é apenas uma história com uma casa decimal.", fr: "Elle a quitté un bureau exigeant des certitudes et gardé les marges d’erreur. Elle donne des probabilités, jamais des promesses. Un nombre sans fourchette, dit-elle, n’est qu’une histoire avec une décimale.", it: "Ha lasciato una scrivania che voleva certezze e tenuto i margini d’errore. Dà probabilità, mai promesse. Un numero senza intervallo, dice, è solo una storia con un punto decimale.", de: "Verließ einen Handelstisch, der Gewissheit wollte, und behielt die Fehlerbalken. Gibt Wahrscheinlichkeiten, nie Versprechen. Eine Zahl ohne Spanne ist für sie nur eine Geschichte mit Dezimalpunkt." },
  noor: { en: 'Has seen every cycle and remembers how each one ended. Unhurried, firm, hands you a ring for coming back rather than for being right. Sit down: review the week before the next trade.', es: 'Ya vio todos los ciclos y recuerda cómo terminó cada uno. Sin prisa, firme, te da un anillo por volver y no por acertar. Siéntate: revisa la semana antes del próximo trade.' , pt: "Viu todos os ciclos e lembra-se de como terminaram. Sem pressa e firme, oferece um anel por voltar, não por acertar. Sente-se: reveja a semana antes da próxima operação.", fr: "Elle a vu chaque cycle et se rappelle leur fin. Calme et ferme, elle vous offre un anneau pour être revenu, pas pour avoir eu raison. Asseyez-vous : faites le bilan de la semaine avant la prochaine opération.", it: "Ha visto ogni ciclo e ricorda come è finito. Calma e decisa, ti dà un anello per essere tornato, non per aver avuto ragione. Siediti: rivedi la settimana prima della prossima operazione.", de: "Hat jeden Zyklus gesehen und erinnert sich an jedes Ende. Ruhig und bestimmt gibt sie dir einen Ring fürs Wiederkommen statt fürs Rechthaben. Setz dich: Prüfe die Woche vor dem nächsten Handel." },
  keo: { en: 'Has been paddling out at dawn for thirty years and has never once chased a wave. Sits out the whole set with a smile, then goes on the one nobody else saw. Waiting is not doing nothing, he says. It is the hardest part.', es: 'Lleva treinta años entrando al agua al amanecer y nunca ha perseguido una ola. Deja pasar la serie entera con una sonrisa y luego entra en la que nadie vio. Esperar no es no hacer nada, dice. Es la parte más difícil.' , pt: "Há trinta anos que entra no mar ao amanhecer sem nunca perseguir uma onda. Deixa passar toda a série com um sorriso e apanha a onda que ninguém viu. Esperar não é não fazer nada, diz. É a parte mais difícil.", fr: "Il rame à l’aube depuis trente ans sans avoir jamais poursuivi une vague. Il laisse passer toute la série avec le sourire, puis prend celle que personne n’a vue. Attendre n’est pas ne rien faire, dit-il. C’est le plus difficile.", it: "Da trent’anni pagaia all’alba senza aver mai inseguito un’onda. Lascia passare tutta la serie sorridendo, poi prende quella che nessuno ha visto. Aspettare non è non fare nulla, dice. È la parte più difficile.", de: "Paddelt seit dreißig Jahren im Morgengrauen hinaus und hat nie eine Welle gejagt. Wartet lächelnd die ganze Serie ab, dann nimmt er die Welle, die niemand sah. Warten heißt nicht Nichtstun, sagt er. Es ist der schwierigste Teil." },
};

export const DEFAULT_QUICK_ACCESS = ['BTC', 'NVDA', 'ETH'];

// ---- Pets: one per companion, unlock at 300 XP; the panda spins ----

export interface CompanionPet { companionId: string; name: Bi; emoji: string; spins: boolean }
export const PET_UNLOCK_XP = 500;
export const PETS: Record<string, CompanionPet> = {
  orb: { companionId: 'orb', name: { en: 'Spin the panda', es: 'Panda giratorio', pt: 'Spin, o panda' , fr: "Spin le panda", it: "Spin il panda", de: "Spin, der Panda" }, emoji: '🐼', spins: true },
  byte: { companionId: 'byte', name: { en: 'Bit the dog', es: 'Bit el perro', pt: 'Bit, o cachorro' , fr: "Bit le chien", it: "Bit il cane", de: "Bit, der Hund" }, emoji: '🐶', spins: false },
  kora: { companionId: 'kora', name: { en: 'Nova the cat', es: 'Nova la gata', pt: 'Nova, a gata' , fr: "Nova le chat", it: "Nova il gatto", de: "Nova, die Katze" }, emoji: '🐱', spins: false },
  zip: { companionId: 'zip', name: { en: 'Turbo the monkey', es: 'Turbo el mono', pt: 'Turbo, o macaco' , fr: "Turbo le singe", it: "Turbo la scimmia", de: "Turbo, der Affe" }, emoji: '🐵', spins: false },
  glitch: { companionId: 'glitch', name: { en: 'Bug the gecko', es: 'Bug el geco', pt: 'Bug, a lagartixa' , fr: "Bug le gecko", it: "Bug il geco", de: "Bug, der Gecko" }, emoji: '🦎', spins: false },
  momo: { companionId: 'momo', name: { en: 'Ink the octopus', es: 'Ink el pulpo', pt: 'Ink, o polvo' , fr: "Ink la pieuvre", it: "Ink il polpo", de: "Ink, der Oktopus" }, emoji: '🐙', spins: false },
  flux: { companionId: 'flux', name: { en: 'Echo the parrot', es: 'Echo el loro', pt: 'Echo, o papagaio' , fr: "Echo le perroquet", it: "Echo il pappagallo", de: "Echo, der Papagei" }, emoji: '🦜', spins: false },
  rook: { companionId: 'rook', name: { en: 'Sage the owl', es: 'Sage el búho', pt: 'Sage, a coruja' , fr: "Sage le hibou", it: "Sage il gufo", de: "Sage, die Eule" }, emoji: '🦉', spins: false },
  halo: { companionId: 'halo', name: { en: 'Peace the dove', es: 'Paz la paloma', pt: 'Paz, a pomba' , fr: "Peace la colombe", it: "Peace la colomba", de: "Peace, die Taube" }, emoji: '🕊️', spins: false },
  axiom: { companionId: 'axiom', name: { en: 'Ledger the turtle', es: 'Ledger la tortuga', pt: 'Ledger, a tartaruga' , fr: "Ledger la tortue", it: "Ledger la tartaruga", de: "Ledger, die Schildkröte" }, emoji: '🐢', spins: false },
  iris: { companionId: 'iris', name: { en: 'Cirrus the crane', es: 'Cirrus la grulla', pt: 'Cirrus, o grou' , fr: "Cirrus la grue", it: "Cirrus la gru", de: "Cirrus, der Kranich" }, emoji: '\u{1F426}', spins: false },
  sol: { companionId: 'sol', name: { en: 'Root the hedgehog', es: 'Root el erizo', pt: 'Root, o ouriço' , fr: "Root le hérisson", it: "Root il riccio", de: "Root, der Igel" }, emoji: '\u{1F994}', spins: false },
  zuri: { companionId: 'zuri', name: { en: 'Trace the fox', es: 'Trace la zorra', pt: 'Trace, a raposa' , fr: "Trace le renard", it: "Trace la volpe", de: "Trace, der Fuchs" }, emoji: '\u{1F98A}', spins: false },
  mira: { companionId: 'mira', name: { en: 'Pace the hare', es: 'Pace la liebre', pt: 'Pace, a lebre' , fr: "Pace le lièvre", it: "Pace la lepre", de: "Pace, der Hase" }, emoji: '\u{1F407}', spins: false },
  nalu: { companionId: 'nalu', name: { en: 'Kai the dolphin', es: 'Kai el delfín', pt: 'Kai, o golfinho' , fr: "Kai le dauphin", it: "Kai il delfino", de: "Kai, der Delfin" }, emoji: '\u{1F42C}', spins: false },
  vega: { companionId: 'vega', name: { en: 'Sigma the raven', es: 'Sigma el cuervo', pt: 'Sigma, o corvo' , fr: "Sigma le corbeau", it: "Sigma il corvo", de: "Sigma, der Rabe" }, emoji: '\u{1F426}\u{200D}\u{2B1B}', spins: false },
  noor: { companionId: 'noor', name: { en: 'Elder the tortoise', es: 'Elder la tortuga', pt: 'Elder, o jabuti' , fr: "Elder la tortue terrestre", it: "Elder la testuggine", de: "Elder, die Landschildkröte" }, emoji: '\u{1F422}', spins: false },
  keo: { companionId: 'keo', name: { en: 'Sombra the sea turtle', es: 'Sombra la tortuga marina', pt: 'Sombra, a tartaruga-marinha' , fr: "Sombra la tortue marine", it: "Sombra la tartaruga marina", de: "Sombra, die Meeresschildkröte" }, emoji: '\u{1F422}', spins: false },
};
export function petFor(companionId: string): CompanionPet | null { return PETS[companionId] ?? null; }
export function petUnlocked(xp: number): boolean { return xp >= PET_UNLOCK_XP; }
export function wornGear(companionId: string, xp: number): CompanionTool[] { return toolsFor(companionId).filter((t) => xp >= toolUnlockXP(t.tier)); }
