import { t } from './i18n';

const SPANISH: Record<string, string> = {
  "// RECENT LOSSES & CONTRADICTIONS": "// PÉRDIDAS Y CONTRADICCIONES RECIENTES",
  "3 AI agents debate": "3 agentes de IA debaten",
  "> ANALYZING SELF-CORRECTION PATTERNS...": "> ANALIZANDO PATRONES DE AUTOCORRECCIÓN...",
  "> COMPUTING CALIBRATION CURVE...": "> CALCULANDO CURVA DE CALIBRACIÓN...",
  "> CROSS-REFERENCING 12 DATA SOURCES...": "> CRUZANDO 12 FUENTES DE DATOS...",
  "> EVALUATING DEBATE QUALITY SCORES [HAIKU_JUDGE]...": "> EVALUANDO CALIDAD DEL DEBATE [HAIKU_JUDGE]...",
  "> FETCHING POLYMARKET SMART MONEY DATA...": "> OBTENIENDO DATOS DE CAPITAL INFORMADO DE POLYMARKET...",
  "> FETCHING RSI, MACD, BOLLINGER, SUPERTREND, AHR999...": "> OBTENIENDO RSI, MACD, BOLLINGER, SUPERTREND, AHR999...",
  "> INITIATING METACOGNITION SEQUENCE...": "> INICIANDO SECUENCIA DE METACOGNICIÓN...",
  "> LOADING PUBLIC MARKET CONTEXT...": "> CARGANDO CONTEXTO PÚBLICO DEL MERCADO...",
  "> LOADING TECHNICAL INDICATORS...": "> CARGANDO INDICADORES TÉCNICOS...",
  "> LOADING WHALE SIGNALS + FUNDING RATES...": "> CARGANDO SEÑALES DE GRANDES INVERSORES Y TASAS DE FINANCIAMIENTO...",
  "> READING FEAR & GREED INDEX...": "> LEYENDO ÍNDICE DE MIEDO Y CODICIA...",
  "> SYNTHESIZING METACOGNITION REPORT...": "> SINTETIZANDO INFORME DE METACOGNICIÓN...",
  "ACTION": "ACCIÓN",
  "ACTIVATE BOBBY IN YOUR GROUP": "ACTIVA BOBBY EN TU GRUPO",
  "ACTIVE": "ACTIVO",
  "ACTIVE_SIGNALS": "SEÑALES_ACTIVAS",
  "ADD BOT TO GROUP →": "AÑADIR BOT AL GRUPO →",
  "ADJUSTMENT:": "AJUSTE:",
  "AGENT": "AGENTE",
  "AGGREGATE AVERAGE • LAST {0} DEBATES": "PROMEDIO AGREGADO • ÚLTIMOS {0} DEBATES",
  "AGREEMENT RATE": "TASA DE ACUERDO",
  "ALERTS": "ALERTAS",
  "AWAITING EVALUATION": "ESPERANDO EVALUACIÓN",
  "AWAITING_POST_MORTEM_EVALUATION": "ESPERANDO_EVALUACIÓN_POSTERIOR",
  "Actionability": "Aplicabilidad",
  "Activate Bobby in your Telegram group. Multi-agent trading intelligence, voice notes, real-time signals.": "Activa Bobby en tu grupo de Telegram. Inteligencia de trading con varios agentes, notas de voz y señales en tiempo real.",
  "Actual:": "Real:",
  "Agent Leaderboard | Bobby Agent Trader": "Clasificación de agentes | Bobby Agent Trader",
  "Audio responses": "Respuestas de audio",
  "BOBBY IS LIVE": "BOBBY ESTÁ ACTIVO",
  "BOBBY SQUAD // SHOWCASE 3D": "BOBBY SQUAD // GALERÍA 3D",
  "BOBBY_ACTUAL": "BOBBY_REAL",
  "BOBBY_CORE_V1.0 // SELF-AWARENESS ENGINE": "BOBBY_CORE_V1.0 // MOTOR DE AUTOEVALUACIÓN",
  "BOBBY_METACOGNITION_ENGINE": "MOTOR_DE_METACOGNICIÓN_BOBBY",
  "BREAK_EVEN_EXCLUDED:": "RESULTADOS_NEUTROS_EXCLUIDOS:",
  "BULLISH": "ALCISTA",
  "Base proof record": "Registro de pruebas en Base",
  "Bobby is now fully integrated.": "Bobby ya está completamente integrado.",
  "Bobby never sends a wallet or payment prompt from this flow.": "Bobby nunca solicita una cartera o un pago desde este flujo.",
  "Bobby's Verdict": "Veredicto de Bobby",
  "Bobby's public track record · Confirmed Base receipts ·": "Historial público de Bobby · Comprobantes confirmados en Base ·",
  "Bobby, should I long BTC?": "Bobby, ¿debería abrir un long de BTC?",
  "Bot not responding? Make sure Bobby has admin privileges.": "¿El bot no responde? Asegúrate de que Bobby tenga permisos de administrador.",
  "Bucket:": "Intervalo:",
  "Bullish structure valid but macro risk demands caution. Half-size entry at $64.2k with tight stop at $63.6k. Scale in after CPI if structure holds.": "La estructura alcista es válida, pero el riesgo macro exige cautela. Entrada de media posición en $64.2k con stop ajustado en $63.6k. Aumentar después del CPI si la estructura se mantiene.",
  "CALIBRATION CURVE": "CURVA DE CALIBRACIÓN",
  "CALIBRATION ERROR": "ERROR DE CALIBRACIÓN",
  "CAUTION": "CAUTELA",
  "CAUTIOUS": "CAUTELOSO",
  "CHALLENGE": "DESAFÍO",
  "COMPANIONS": "COMPAÑEROS",
  "CONFIDENT": "CONFIADO",
  "CONFIRMED_RECEIPT_LEDGER": "REGISTRO_DE_COMPROBANTES_CONFIRMADOS",
  "CONVERSATION": "CONVERSACIÓN",
  "COUNCIL_OVERVIEW": "RESUMEN_DEL_CONSEJO",
  "CPI data release in 6 hours — high volatility expected. Liquidity grab below $63.8k likely before any sustained move. Risk of fake breakout.": "Publicación del CPI en 6 horas: se espera alta volatilidad. Es probable una barrida de liquidez bajo $63.8k antes de cualquier movimiento sostenido. Riesgo de ruptura falsa.",
  "CUMULATIVE_GROWTH_INDEX": "ÍNDICE_DE_CRECIMIENTO_ACUMULADO",
  "CURRENT_EQUITY": "PATRIMONIO_ACTUAL",
  "Collecting data... Need 5+ resolved debates.": "Recopilando datos... Se necesitan al menos 5 debates resueltos.",
  "Contact Support": "Contactar soporte",
  "DAILY_PNL": "PNL_DIARIO",
  "Data Citation": "Citas de datos",
  "Desktop? Click to copy link": "¿En computadora? Haz clic para copiar el enlace",
  "ENTRY": "ENTRADA",
  "ERRORS ACKNOWLEDGED (72H)": "ERRORES RECONOCIDOS (72H)",
  "EXECUTED": "EJECUTADO",
  "EXPLAIN DASHBOARD WITH AI": "EXPLICAR PANEL CON IA",
  "EXPLORATION": "EXPLORACIÓN",
  "Example conversation · 14:02 UTC": "Conversación de ejemplo · 14:02 UTC",
  "Extreme Fear": "Miedo extremo",
  "Extreme Greed": "Codicia extrema",
  "FROM ${0} INITIAL": "DESDE ${0} INICIALES",
  "FUNDS": "FONDOS",
  "Fear": "Miedo",
  "Fear & Greed:": "Miedo y codicia:",
  "Final Decision Maker": "Responsable de la decisión final",
  "Final decision maker": "Responsable de la decisión final",
  "From ${0} initial capital": "Desde ${0} de capital inicial",
  "GROUP SETUP PAUSED FOR": "CONFIGURACIÓN DEL GRUPO EN PAUSA PARA",
  "GROWTH": "CRECIMIENTO",
  "Get your agent's debates and signals directly in Telegram. Three agents debate — you decide.": "Recibe los debates y señales de tu agente directamente en Telegram. Tres agentes debaten; tú decides.",
  "Greed": "Codicia",
  "Group": "Grupo",
  "IDLE": "EN REPOSO",
  "Illustrative prices, not a current recommendation.": "Precios ilustrativos, no una recomendación actual.",
  "LATEST SNAPSHOT": "ÚLTIMA CAPTURA",
  "LATEST_CRITICAL_WEAKNESS": "ÚLTIMA_DEBILIDAD_CRÍTICA",
  "LEADERBOARD": "CLASIFICACIÓN",
  "LIQUIDITY": "LIQUIDEZ",
  "LISTENING": "ESCUCHANDO",
  "LIVE": "EN VIVO",
  "LOADING AGENTS...": "CARGANDO AGENTES...",
  "LOADING ANALYTICS...": "CARGANDO ANALÍTICA...",
  "LOADING...": "CARGANDO...",
  "LOSS": "PÉRDIDA",
  "Link not working? Click to copy: t.me/Bobbyagentraderbot": "¿El enlace no funciona? Haz clic para copiar: t.me/Bobbyagentraderbot",
  "Live market context": "Contexto del mercado en vivo",
  "MARKET REGIME": "RÉGIMEN DE MERCADO",
  "MAX_DRAWDOWN": "CAÍDA_MÁXIMA",
  "MENTORING": "MENTORÍA",
  "METACOGNITION MODULE": "MÓDULO DE METACOGNICIÓN",
  "METACOGNITION_METRICS": "MÉTRICAS_DE_METACOGNICIÓN",
  "MODERATE LONG": "LONG MODERADO",
  "MULTI_AGENT": "VARIOS_AGENTES",
  "Metacognition | Bobby Agent Trader": "Metacognición | Bobby Agent Trader",
  "NEEDS DATA": "NECESITA DATOS",
  "NO DATA": "SIN DATOS",
  "Neutral": "Neutral",
  "New activations paused": "Nuevas activaciones en pausa",
  "New group activation is paused while Bobby moves to a Base-only architecture. Existing active groups keep working.": "La activación de nuevos grupos está en pausa mientras Bobby adopta una arquitectura exclusiva de Base. Los grupos activos existentes siguen funcionando.",
  "No analytics data available": "No hay datos de analítica disponibles",
  "No data available": "Sin datos disponibles",
  "No payment requested": "No se solicita pago",
  "No public protocol trades have been recorded yet.": "Todavía no se han registrado operaciones públicas del protocolo.",
  "No publicly attributable protocol trades have been recorded yet.": "Todavía no se han registrado operaciones atribuibles públicamente al protocolo.",
  "No publicly attributable protocol trades have been recorded yet. Performance metrics need confirmed public receipts.": "Todavía no se han registrado operaciones atribuibles públicamente al protocolo. Las métricas de rendimiento necesitan comprobantes públicos confirmados.",
  "No recent contradictions — record clean.": "Sin contradicciones recientes: registro sin incidencias.",
  "Novel Insight": "Perspectiva novedosa",
  "OFFLINE": "DESCONECTADO",
  "ON-CHAIN FLOWS": "FLUJOS EN CADENA",
  "ON_CHAIN": "EN_CADENA",
  "OPEN IN TELEGRAM →": "ABRIR EN TELEGRAM →",
  "OPEN_TERMINAL": "ABRIR_TERMINAL",
  "ORB · CORE": "ORB · NÚCLEO",
  "OVERCONFIDENT": "EXCESO DE CONFIANZA",
  "Opportunity Scanner": "Buscador de oportunidades",
  "Opportunity scanner": "Buscador de oportunidades",
  "Order flow accumulation at $64.2k support. Rising wedge breakout on 4H. Volume divergence confirms buyer pressure. Entry zone: $64,100–$64,400.": "Acumulación del flujo de órdenes en el soporte de $64.2k. Ruptura de cuña ascendente en 4H. La divergencia de volumen confirma presión compradora. Zona de entrada: $64,100–$64,400.",
  "PATIENCE": "PACIENCIA",
  "PENDING": "PENDIENTE",
  "PERFECT": "IDEAL",
  "PERFORMANCE INDEX": "ÍNDICE DE RENDIMIENTO",
  "PERFORMANCE_ANALYTICS": "ANALÍTICA_DE_RENDIMIENTO",
  "PNL": "PNL",
  "PNL_BY_ASSET": "PNL_POR_ACTIVO",
  "PRACTICE": "PRÁCTICA",
  "PREDICTED vs ACTUAL WIN RATE": "TASA DE ACIERTO PREVISTA vs REAL",
  "PRELIMINARY_DATA • n={0}": "DATOS_PRELIMINARES • n={0}",
  "PROBABILITY": "PROBABILIDAD",
  "PROFIT_FACTOR": "FACTOR_DE_GANANCIA",
  "PROOFS": "PRUEBAS",
  "PUBLIC PROTOCOL EQUITY · CONFIRMED BASE RECEIPTS": "PATRIMONIO PÚBLICO DEL PROTOCOLO · COMPROBANTES CONFIRMADOS EN BASE",
  "PUBLIC_PROTOCOL_EQUITY": "PATRIMONIO_PÚBLICO_DEL_PROTOCOLO",
  "Perfect": "Ideal",
  "Perfect:": "Ideal:",
  "Performance Analytics | Bobby Agent Trader": "Analítica de rendimiento | Bobby Agent Trader",
  "Portfolio | Bobby Agent Trader": "Portafolio | Bobby Agent Trader",
  "REAL_TIME": "TIEMPO_REAL",
  "RED TEAM": "RED TEAM",
  "REJECTED": "RECHAZADO",
  "RETURN": "RENDIMIENTO",
  "RISK GATE": "FILTRO DE RIESGO",
  "Recent_Council_Decisions": "Decisiones_Recientes_Del_Consejo",
  "Red Team Rigor": "Rigor de Red Team",
  "SAMPLE_SIZE:": "TAMAÑO_DE_MUESTRA:",
  "SELF-CORRECTION LOG": "REGISTRO DE AUTOCORRECCIÓN",
  "SELF-CORRECTIONS": "AUTOCORRECCIONES",
  "SERVICE": "SERVICIO",
  "SIGNALS": "SEÑALES",
  "SIMPLE VOICE": "VOZ SIMPLE",
  "SPEAKING": "HABLA",
  "START": "INICIO",
  "STATUS": "ESTADO",
  "SYMBOL": "SÍMBOLO",
  "SYSTEM_LOGS": "REGISTROS_DEL_SISTEMA",
  "Specificity": "Especificidad",
  "Squad Showcase | Bobby Agent Trader": "Galería del equipo | Bobby Agent Trader",
  "TELEGRAM_INTEGRATION": "INTEGRACIÓN_CON_TELEGRAM",
  "THESIS": "TESIS",
  "THINKING": "PIENSA",
  "TILTED": "DESEQUILIBRADO",
  "TIMESTAMP": "FECHA Y HORA",
  "TOTAL DEBATES": "TOTAL DE DEBATES",
  "TOTAL_RETURN": "RENDIMIENTO_TOTAL",
  "TOTAL_TRADES": "OPERACIONES_TOTALES",
  "TRACK RECORD": "HISTORIAL",
  "TRADE": "OPERACIÓN",
  "TRADES": "OPERACIONES",
  "TRADE_OUTCOMES": "RESULTADOS_DE_OPERACIONES",
  "Telegram | Bobby Agent Trader": "Telegram | Bobby Agent Trader",
  "The AI judge evaluates debates asynchronously.": "El juez de IA evalúa los debates de forma asíncrona.",
  "The public endpoint provides aggregate totals only. Individual receipts and trade-level charts are not published here.": "El endpoint público solo ofrece totales agregados. Aquí no se publican comprobantes individuales ni gráficos por operación.",
  "Thesis Destroyer": "Cuestiona la tesis",
  "Thesis destroyer": "Cuestiona la tesis",
  "This page never connects a wallet, requests payment or moves funds. A payment request is not from Bobby.": "Esta página nunca conecta una cartera, solicita pagos ni mueve fondos. Una solicitud de pago no viene de Bobby.",
  "This public endpoint reports aggregates; individual trade receipts are not published here.": "Este endpoint público muestra datos agregados; aquí no se publican comprobantes individuales de operaciones.",
  "They all follow your gaze · tap one for a larger view · SPEAKING animates their mouths": "Todos te siguen con la mirada · toca cualquiera para verlo en grande · HABLA anima sus bocas",
  "VOICE_NOTES": "NOTAS_DE_VOZ",
  "View the public record →": "Ver el historial público →",
  "WELL CALIBRATED": "BIEN CALIBRADO",
  "WIN": "GANANCIA",
  "WIN RATE": "TASA DE ACIERTO",
  "WIN_RATE": "TASA_DE_ACIERTO",
  "YOUR GROUP": "TU GRUPO",
  "Your Agent on Telegram": "Tu agente en Telegram",
  "Your Group": "Tu grupo",
  "Your group": "Tu grupo",
  "Your private trade receipts are available in the Record page after wallet sign-in.": "Tus comprobantes privados de operaciones están disponibles en la página Historial después de iniciar sesión con tu cartera.",
  "trades": "operaciones",
  "{0} losses": "{0} pérdidas",
  "{0} wins": "{0} ganancias",
  "{0}% win rate": "{0}% de acierto",
  "← BACK_TO_TERMINAL": "← VOLVER_AL_TERMINAL",
  "← VIEW ALL": "← VER TODOS",
  "EXPLAIN WITH AI": "EXPLICAR CON IA",
  "Sign in to use the AI Analyzer": "Inicia sesión para usar el analizador de IA",
  "SIGN IN": "INICIAR SESIÓN",
  "SIGN UP": "CREAR CUENTA",
  "Run again": "Ejecutar otra vez",
  "Connecting to AI analyst...": "Conectando con el analista de IA...",
  "ERROR:": "ERROR:",
  "The explanation is temporarily unavailable. Try again.": "La explicación no está disponible temporalmente. Inténtalo otra vez.",
  "Enable AI permission in the Desk before sending dashboard data for an explanation.": "Activa el permiso de IA en el Desk antes de enviar datos del dashboard para una explicación.",
  "Open Desk": "Abrir Desk",
};

/** Product copy only; placeholders preserve caller values without HTML or evaluation. */
export function kineticText(en: string, ...values: unknown[]): string {
  return t(en, SPANISH[en] ?? en).replace(/\{(\d+)\}/g, (token, index) => Number(index) < values.length ? String(values[Number(index)]) : token);
}

const STATUS_LABELS = new Set(['ACTIVE', 'IDLE', 'OFFLINE', 'PENDING', 'EXECUTED', 'REJECTED', 'WIN', 'LOSS', 'BULLISH', 'CAUTION', 'Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']);
/** Translate known display labels; unfamiliar provider values remain intact. */
export function kineticStatus(value: string): string {
  return STATUS_LABELS.has(value) ? kineticText(value) : value;
}
