create table if not exists public.hardness_agents (
  id bigint generated by default as identity primary key,
  agent_id text not null unique,
  owner_address text not null,
  name text not null,
  agent_type text not null default 'trading-agent',
  version text,
  capabilities jsonb not null default '[]'::jsonb,
  mcp_endpoint text,
  webhook_url text,
  metadata_json jsonb not null default '{}'::jsonb,
  risk_policy_json jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hardness_agent_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  agent_id text not null references public.hardness_agents(agent_id) on delete cascade,
  intent text not null,
  symbol text,
  direction text,
  request_json jsonb not null default '{}'::jsonb,
  context_json jsonb not null default '{}'::jsonb,
  decision_json jsonb not null default '{}'::jsonb,
  policy_result text,
  hardness_score integer,
  status text not null default 'received',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hardness_agent_proofs (
  id bigint generated by default as identity primary key,
  session_id text not null references public.hardness_agent_sessions(session_id) on delete cascade,
  prediction_hash text,
  commit_tx_hash text,
  signal_tx_hash text,
  resolve_tx_hash text,
  chain_id integer not null default 196,
  created_at timestamptz not null default now()
);

create index if not exists hardness_agent_sessions_agent_id_idx
  on public.hardness_agent_sessions(agent_id, created_at desc);

create index if not exists hardness_agent_sessions_symbol_idx
  on public.hardness_agent_sessions(symbol, created_at desc);

create index if not exists hardness_agent_proofs_session_id_idx
  on public.hardness_agent_proofs(session_id);

alter table public.hardness_agents enable row level security;
alter table public.hardness_agent_sessions enable row level security;
alter table public.hardness_agent_proofs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hardness_agents' and policyname = 'Service role full access hardness_agents'
  ) then
    create policy "Service role full access hardness_agents"
      on public.hardness_agents
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hardness_agent_sessions' and policyname = 'Service role full access hardness_agent_sessions'
  ) then
    create policy "Service role full access hardness_agent_sessions"
      on public.hardness_agent_sessions
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hardness_agent_proofs' and policyname = 'Service role full access hardness_agent_proofs'
  ) then
    create policy "Service role full access hardness_agent_proofs"
      on public.hardness_agent_proofs
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
